const worksData = [

    // ==========================================
    // 👑 不朽の名作 (Masterpieces)
    // ==========================================
    {
      genreId: "masterpiece",
      titleJa: "作りたい女と食べたい女",
      titleEn: "She Loves to Cook, and She Loves to Eat",
      castJa: "比嘉愛未, 西野恵未, 森田望智",
      castEn: "Manami Higa, Emi Nishino, Misato Morita",
      dirJa: "松嵜由衣, 中田博之",
      dirEn: "Yui Matsuzaki, Hiroyuki Nakata",
      infoJa: "2022年 / ドラマ全29話 / 日本",
      infoEn: "2022 / TV Series (29 episodes) / Japan",
      quoteJa: "「一緒においしいものを食べる、それだけのことがこんなに嬉しい」",
      quoteEn: "“Sharing a delicious meal with you makes me happier than anything else.”",
      descJa: "食を通じて心の距離を縮めていく2人の女性。自らの生き方や性的指向、アイデンティティに向き合う姿を心温まる繊細さで丁寧に描き出し、多くの共感と絶賛を集めたNHKドラマの金字塔。",
      descEn: "Two women form a deep, healing connection through home-cooked meals. This highly acclaimed drama thoughtfully portrays self-discovery, identity, sexual orientation, and quiet emotional intimacy in modern Japan."
    },
    {
      genreId: "masterpiece",
      titleJa: "キャロル",
      titleEn: "Carol",
      castJa: "ケイト・ブランシェット, ルーニー・マーラ",
      castEn: "Cate Blanchett, Rooney Mara",
      dirJa: "トッド・ヘインズ",
      dirEn: "Todd Haynes",
      infoJa: "2015年 / 118分 / アメリカ・イギリス",
      infoEn: "2015 / 118 min / USA, UK",
      quoteJa: "「ただ、あなたに会いたかった」",
      quoteEn: "“I just wanted to see you.”",
      descJa: "1950年代のニューヨークを舞台に、気品溢れる裕福な既婚女性と若きカメラマン志望の高級百貨店店員の運命的な恋と葛藤を描いた至高の純愛映画史的名作。",
      descEn: "Set in conservative 1950s New York, this film cinematic masterpiece depicts the transformative and deeply emotional love story between an elegant married socialite and a aspiring young photographer."
    },
    {
      genreId: "masterpiece",
      titleJa: "燃ゆる女の肖像",
      titleEn: "Portrait of a Lady on Fire",
      castJa: "ノエミ・メルラン, アデル・エネル",
      castEn: "Noémie Merlant, Adèle Haenel",
      dirJa: "セリーヌ・シアマ",
      dirEn: "Céline Sciamma",
      infoJa: "2019年 / 122分 / フランス",
      infoEn: "2019 / 122 min / France",
      quoteJa: "「私を見て。あなたを覚えているから」",
      quoteEn: "“Look at me. Remember.”",
      descJa: "18世紀末のフランス孤島。見つめ合う女性画家と結婚を目前に控えた令嬢の静謐で激しい愛を描き、カンヌ国際映画祭で脚本賞とクィア・パルム賞を受賞した歴史的傑作。",
      descEn: "On an isolated island in 18th-century Brittany, a female painter and her reluctant subject fall deeply in love, captured through poetic artistic gaze, profound passion, and mutual respect."
    },
    {
      genreId: "masterpiece",
      titleJa: "オーシャンズ8",
      titleEn: "Ocean's 8",
      castJa: "サンドラ・ブロック, ケイト・ブランシェット, アン・ハサウェイ",
      castEn: "Sandra Bullock, Cate Blanchett, Anne Hathaway",
      dirJa: "ゲイリー・ロス",
      dirEn: "Gary Ross",
      infoJa: "2018年 / 110分 / アメリカ",
      infoEn: "2018 / 110 min / USA",
      quoteJa: "「どこかでこれを見ている、犯罪者を目指す8歳の少女のために」",
      quoteEn: "“To some 8-year-old girl lying in bed, dreaming of becoming a criminal.”",
      descJa: "固い絆と阿吽の呼吸で結ばれた強烈なカリスマ相棒コンビが率いる最強の女性犯罪プロフェッショナル集団。メットガラで極上の宝石奪取に挑む爽快エンタテインメント。",
      descEn: "An all-female crew led by two fiercely loyal, highly synchronized long-time partners plots an audacious high-stakes heist at New York's Met Gala in this stylish crime comedy."
    },
    {
      genreId: "masterpiece",
      titleJa: "アデル、ブルーは熱い色",
      titleEn: "Blue Is the Warmest Color",
      castJa: "レア・セドゥ, アデル・エグザルホプロス",
      castEn: "Léa Seydoux, Adèle Exarchopoulos",
      dirJa: "アブデラティフ・ケシシュ",
      dirEn: "Abdellatif Kechiche",
      infoJa: "2013年 / 179分 / フランス",
      infoEn: "2013 / 179 min / France",
      quoteJa: "「私にはあなたとの無限の温もりが必要なの」",
      quoteEn: "“I have infinite tenderness for you. I always will.”",
      descJa: "青い髪をした美大生との出会いによって情熱的な愛を知る少女の成長、すれ違い、そして愛の変遷。カンヌ国際映画祭でパルム・ドールを獲得した圧倒的官能ドラマ。",
      descEn: "A French teenager experiences intense passion, emotional growth, and heartrending artistic and romantic devotion after falling in love with a charismatic, blue-haired art student."
    },
    {
      genreId: "masterpiece",
      titleJa: "彼女が好きなものは、彼女の愛したすべて",
      titleEn: "The World to Come",
      castJa: "キャサリン・ウォーターストン, ヴァネッサ・カービー",
      castEn: "Katherine Waterston, Vanessa Kirby",
      dirJa: "モナ・ファストヴォルド",
      dirEn: "Mona Fastvold",
      infoJa: "2020年 / 100分 / アメリカ",
      infoEn: "2020 / 100 min / USA",
      quoteJa: "「あなたと過ごす時間が、私に生命を与えてくれる」",
      quoteEn: "“Astonishment and joy are what I feel in your presence.”",
      descJa: "19世紀半ばのアメリカ東海岸の開拓地。苛酷な自然環境と孤独な日常の中で、隣同士の農家に暮らす2人の既婚女性が魂を揺さぶる強い精神的・身体的絆で結ばれていく抒情詩。",
      descEn: "In mid-19th century rural America, two neighboring farm wives enduring severe personal loss find solace, emotional liberation, and passionate intimacy in each other's arms."
    },
    {
      genreId: "masterpiece",
      titleJa: "お嬢さん",
      titleEn: "The Handmaiden",
      castJa: "キム・ミニ, キム・テリ",
      castEn: "Kim Min-hee, Kim Tae-ri",
      dirJa: "パク・チャヌク",
      dirEn: "Park Chan-wook",
      infoJa: "2016年 / 145分 / 韓国",
      infoEn: "2016 / 145 min / South Korea",
      quoteJa: "「私の人生を壊しに来た私の救世主」",
      quoteEn: "“My destroyer, my savior.”",
      descJa: "1930年代の日本統治下の朝鮮。莫大な遺産を継いだ謎めいた令嬢と、彼女を騙すために潜入したスリの少女。陰謀と愛憎を打ち破り真実の愛で連帯する極上の愛憎サスペンス。",
      descEn: "Set during 1930s Japanese-occupied Korea, a wealthy heiress and her newly hired Korean maid become unexpectedly enraptured in a passionate relationship, subverting a complex swindle plot."
    },
    {
      genreId: "masterpiece",
      titleJa: "海街diary",
      titleEn: "Our Little Sister",
      castJa: "綾瀬はるか, 長澤まさみ, 夏帆, 広瀬すず",
      castEn: "Haruka Ayase, Masami Nagasawa, Kaho, Suzu Hirose",
      dirJa: "是枝裕和",
      dirEn: "Hirokazu Kore-eda",
      infoJa: "2015年 / 128分 / 日本",
      infoEn: "2015 / 128 min / Japan",
      quoteJa: "「美しいものを美しいと思えることが、幸せなんだと思う」",
      quoteEn: "“To find beautiful things beautiful is happiness in itself.”",
      descJa: "鎌倉の古い一軒家で暮らす三姉妹が、父の死亡をきっかけに異母妹を引き取り、互いを慈しみながら真の家族として絆を深めていく、四姉妹の静けさと温もりに満ちた佳作。",
      descEn: "Three sisters living together in Kamakura invite their young half-sister into their home following their father's death, building an irreplaceable sisterly bond across passing seasons."
    },
    {
      genreId: "masterpiece",
      titleJa: "彼女（映画）",
      titleEn: "Ride or Die",
      castJa: "水原希子, さとうほなみ",
      castEn: "Kiko Mizuhara, Honami Sato",
      dirJa: "廣木隆一",
      dirEn: "Ryuichi Hiroki",
      infoJa: "2021年 / 142分 / 日本",
      infoEn: "2021 / 142 min / Japan",
      quoteJa: "「あなたのためなら、なんだってできる」",
      quoteEn: "“I would do absolutely anything for you.”",
      descJa: "夫から凄惨な家庭内暴力を受けていた女性と、彼女の哀しみを見かねて夫を殺害したかつての同級生。逃避行の中で狂おしく交錯する愛執と解放を描いた極限のロードムービー。",
      descEn: "A woman kills her high school crush's abusive husband to protect her. Together, the two women embark on a desperate road trip filled with raw, conflicting, and inescapable desire."
    },
    {
      genreId: "masterpiece",
      titleJa: "あのこは貴族",
      titleEn: "Aristocrats",
      castJa: "門脇麦, 水原希子",
      castEn: "Mugi Kadowaki, Kiko Mizuhara",
      dirJa: "岨手由貴子",
      dirEn: "Yukiko Sode",
      infoJa: "2021年 / 124分 / 日本",
      infoEn: "2021 / 124 min / Japan",
      quoteJa: "「私たちは、別の世界を生きているわけじゃない」",
      quoteEn: "“We are not living in entirely separate worlds after all.”",
      descJa: "東京の政財界家系で生まれ育った箱入り娘と、地方から自力で上京し都会の壁に突き当たる女性。男性社会の分断を超えて共鳴し、自立への道を歩み出す美しい連帯の物語。",
      descEn: "Two women from vastly different social strata in contemporary Tokyo cross paths, overcoming invisible societal barriers to form a quiet mutual understanding and claim their independence."
    },
  
    // ==========================================
    // 💖 ときめき (Romance)
    // ==========================================
    {
      genreId: "romance",
      titleJa: "彩香ちゃんは弘子先輩に恋してる",
      titleEn: "Ayaka is in Love with Hiroko-senpai",
      castJa: "加藤史帆, 森カンナ",
      castEn: "Shiho Kato, Kanna Mori",
      dirJa: "のむらなお, 枝優花",
      dirEn: "Nao Nomura, Yuka Eda",
      infoJa: "2024年 / ドラマ全8話 / 日本",
      infoEn: "2024 / TV Series (8 episodes) / Japan",
      quoteJa: "「先輩の特別になりたいんです！」",
      quoteEn: "“I want to be someone truly special to you, Senpai!”",
      descJa: "猛烈アタックを繰り広げる猪突猛進な後輩社員と、過去のトラウマから自身がレズビアンであることを隠すクールな先輩。すれ違いがもどかしくも最高に愛おしいオフィス・オフィスラブコメディ。",
      descEn: "An enthusiastic, headstrong junior office worker openly courts her cool, secretly lesbian senior colleague in this delightfully sweet and hilarious office romance drama."
    },
    {
      genreId: "romance",
      titleJa: "チェイサーゲームW パワハラ上司は私の元カノ",
      titleEn: "Chaser Game W",
      castJa: "菅井友香, 中村ゆりか",
      castEn: "Yuka Sugai, Yurika Nakamura",
      dirJa: "太田勇, 山口将幸",
      dirEn: "Yu Ota, Masayuki Yamaguchi",
      infoJa: "2024年 / ドラマ全8話 / 日本",
      infoEn: "2024 / TV Series (8 episodes) / Japan",
      quoteJa: "「忘れたなんて言わせないから」",
      quoteEn: "“Don't you dare pretend you've forgotten about us.”",
      descJa: "大手ゲーム開発会社でプロジェクトリーダーを務める主人公の前に、クライアント側の冷徹な上司としてあらわれたのは、かつて姿を消した大学時代の元カノだった。愛憎が交錯する愛憎劇。",
      descEn: "A gaming producer is shocked when her demanding new foreign client boss turns out to be her college ex-girlfriend, leading to a passionate blend of resentment, dynamic tension, and reignited love."
    },
    {
      genreId: "romance",
      titleJa: "チェイサーゲームW2 美しい僕ら",
      titleEn: "Chaser Game W Season 2",
      castJa: "菅井友香, 中村ゆりか",
      castEn: "Yuka Sugai, Yurika Nakamura",
      dirJa: "太田勇, 山口将幸",
      dirEn: "Yu Ota, Masayuki Yamaguchi",
      infoJa: "2024年 / ドラマ全8話 / 日本",
      infoEn: "2024 / TV Series (8 episodes) / Japan",
      quoteJa: "「今度こそ、もう二度と離さない」",
      quoteEn: "“This time, I will never let you go again.”",
      descJa: "数々の試練とすれ違いを乗り越えて再び結ばれた樹と冬雨。揺るぎない絆を深める2人が、互いの将来や社会の現実に立ち向かいながら歩む真実の愛の続編。",
      descEn: "Having reunited after painful misunderstandings, Itsuki and Fuyu navigate the realities of family expectations and career obstacles to protect their unwavering commitment to each other."
    },
    {
      genreId: "romance",
      titleJa: "ボトムス ～最底辺の私たち～",
      titleEn: "Bottoms",
      castJa: "レイチェル・セノット, アヨ・エデビリ",
      castEn: "Rachel Sennott, Ayo Edebiri",
      dirJa: "エマ・セリグマン",
      dirEn: "Emma Seligman",
      infoJa: "2023年 / 91分 / アメリカ",
      infoEn: "2023 / 91 min / USA",
      quoteJa: "「チアリーダーと付き合うために護身術クラブを作るの」",
      quoteEn: "“We are starting a self-defense club to get closer to cheerleaders.”",
      descJa: "スクールカースト最底辺のクィアな女子高生コンビが、憧れのチアリーダーたちと仲良くなるために「女子護身術クラブ」をでっち上げる、破天荒でエネルギッシュな青春ブラックコメディ。",
      descEn: "Two awkward, unpopular queer high school girls found a fight club under the guise of self-defense as a hilarious, chaotic strategy to win over the school's top cheerleaders."
    },
    {
      genreId: "romance",
      titleJa: "トランジットガールズ",
      titleEn: "Transit Girls",
      castJa: "伊藤沙莉, 佐久間由衣",
      castEn: "Sairi Ito, Yui Sakuma",
      dirJa: "前田真人",
      dirEn: "Masato Maeda",
      infoJa: "2015年 / ドラマ全8話 / 日本",
      infoEn: "2015 / TV Series (8 episodes) / Japan",
      quoteJa: "「お姉ちゃんのこと、好きになっちゃいけない？」",
      quoteEn: "“Is it wrong for me to fall in love with you, sis?”",
      descJa: "親同士の再婚によって急に義理の姉妹となったスタイリッシュな姉とボーイッシュな妹。ひとつ屋根の下で惹かれ合い、世間の目や複雑な感情に揺れ動く甘酸っぱい初恋ストーリー。",
      descEn: "Two young women suddenly become stepsisters due to their parents' remarriage. Living under one roof, subtle affection turns into a poignant, heart-pounding first love."
    },
    {
      genreId: "romance",
      titleJa: "ハーフ・オブ・イット: はじまりの物語",
      titleEn: "The Half of It",
      castJa: "リア・ルイス, ダニエル・ディマー, アレクシス・レミル",
      castEn: "Leah Lewis, Daniel Diemer, Alexxis Lemire",
      dirJa: "アリス・ウー",
      dirEn: "Alice Wu",
      infoJa: "2020年 / 104分 / アメリカ",
      infoEn: "2020 / 104 min / USA",
      quoteJa: "「愛とは完璧なものを見つけることじゃない」",
      quoteEn: "“Love isn't finding your perfect complement.”",
      descJa: "内気な中国系移民の優等生少女が、不器用なフットボール男子から頼まれてラブレターの代筆を引き受けるが、その手紙の相手は自身もひそかに恋焦がれる学校マドンナだった青春ラブストーリー。",
      descEn: "A quiet Asian-American honors student helps a well-meaning jock write love letters to a beautiful classmate whom she secretly harbors romantic feelings for herself."
    },
    {
      genreId: "romance",
      titleJa: "百合だのかんだの",
      titleEn: "Yuri or Something",
      castJa: "馬場ふみか, 小島藤子",
      castEn: "Fumika Baba, Fujiko Kojima",
      dirJa: "加藤裕将",
      dirEn: "Yusuke Kato",
      infoJa: "2019年 / ドラマ全8話 / 日本",
      infoEn: "2019 / TV Series (8 episodes) / Japan",
      quoteJa: "「友情とか恋愛とか、名前なんてどうでもいい」",
      quoteEn: "“Friendship, love... labels don't matter between us.”",
      descJa: "ストーカー被害に悩む女子大生が、再会した小学生時代の親友と同居を開始。単なる友情や従来の恋愛の範疇に収まらない、現代女性たちの繊細で特別なグラデーションの関係性を描く。",
      descEn: "A college girl experiencing stalking encounters her childhood best female friend and moves in together, developing an indefinable yet deeply vital emotional connection."
    },
    {
      genreId: "romance",
      titleJa: "ブックスマート 卒業前夜のパーティーデビュー",
      titleEn: "Booksmart",
      castJa: "ビーニー・フェルドスタイン, ケイトリン・デヴァー",
      castEn: "Beanie Feldstein, Kaitlyn Dever",
      dirJa: "オリヴィア・ワイルド",
      dirEn: "Olivia Wilde",
      infoJa: "2019年 / 102分 / アメリカ",
      infoEn: "2019 / 102 min / USA",
      quoteJa: "「私たちは勉強だけじゃなく、遊びだって全力でやるべきだった」",
      quoteEn: "“We should have worked less and partied way more.”",
      descJa: "高校生活のすべてを勉強に捧げてきた優等生コンビ（うち一人はオープンなレズビアン）。卒業前夜に「遊ぶことも諦めない」と誓い、爆笑の爆走パーティー巡りに繰り出す最高のバディ＆ガールズ映画。",
      descEn: "On the night before high school graduation, two academic overachievers—one of whom is openly gay—realize they missed out on fun and cram four years of partying into one wild night."
    },
    {
      genreId: "romance",
      titleJa: "片想いスパイラル",
      titleEn: "Unrequited Love Spiral",
      castJa: "知英, 佐津川愛美, TAKUYA",
      castEn: "Ji-young, Aimi Satsukawa, TAKUYA",
      dirJa: "原桂之介",
      dirEn: "Keinosuke Hara",
      infoJa: "2016年 / 82分 / 日本",
      infoEn: "2016 / 82 min / Japan",
      quoteJa: "「心は男でも、体は女。そんな僕が君を好きになった」",
      quoteEn: "“Though I have a woman's body, my heart fell deeply in love with you.”",
      descJa: "体は女性でありながら心は男性である性同一性障害（FTM）を抱える主人公。シェアハウスの同居人である親友女性への報われない秘めた想いと複雑な三角関係を描く純愛ドラマ。",
      descEn: "A transgender man with a female body struggles with his secret, intense romantic feelings for his female roommate, navigating a complex triangular affection."
    },
    {
      genreId: "romance",
      titleJa: "イマジナリーライン（パス・イン・ライフ）",
      titleEn: "Saving Face",
      castJa: "ミシェル・クルージ, リン・チェン, ジョアン・チェン",
      castEn: "Michelle Krusiec, Lynn Chen, Joan Chen",
      dirJa: "アリス・ウー",
      dirEn: "Alice Wu",
      infoJa: "2004年 / 91分 / アメリカ",
      infoEn: "2004 / 91 min / USA",
      quoteJa: "「本当の自分を隠して生きるのに疲れたの」",
      quoteEn: "“I'm tired of hiding who I really am.”",
      descJa: "ニューヨークに住む中国系アメリカ人の外科医女性が、ダンサーの女性と恋に落ちる。世間体を気にする保守的な親類と未婚で妊娠した実母とのコミカルで情に厚いファミリーロマンス。",
      descEn: "A young Chinese-American surgeon falling for a beautiful dancer must navigate her conservative family's expectations while her unmarried mother suddenly becomes pregnant."
    },
  
    // ==========================================
    // 🍂 大人の葛藤 (Drama & Bitter)
    // ==========================================
    {
      genreId: "bitter",
      titleJa: "TAR/ター",
      titleEn: "TÁR",
      castJa: "ケイト・ブランシェット, ニーナ・ホス, ノエミ・メルラン",
      castEn: "Cate Blanchett, Nina Hoss, Noémie Merlant",
      dirJa: "トッド・フィールド",
      dirEn: "Todd Field",
      infoJa: "2022年 / 158分 / アメリカ",
      infoEn: "2022 / 158 min / USA",
      quoteJa: "「時間は私がコントロールする」",
      quoteEn: "“Time is the essential piece of interpretation.”",
      descJa: "世界最高峰のオーケストラで指揮者を務める天才絶対君主ター。同性のパートナーであるコンサートマスターとの冷え切った関係、権力濫用疑惑から狂気と落日へ向かう圧巻の心理サスペンス。",
      descEn: "A world-renowned lesbian conductor at the peak of her career sees her personal life and artistic empire collapse as secrets and allegations of abuse of power emerge."
    },
    {
      genreId: "bitter",
      titleJa: "Daughters",
      titleEn: "Daughters",
      castJa: "三吉彩花, 阿部純子",
      castEn: "Ayaka Miyoshi, Junko Abe",
      dirJa: "津田肇",
      dirEn: "Hajime Tsuda",
      infoJa: "2020年 / 104分 / 日本",
      infoEn: "2020 / 104 min / Japan",
      quoteJa: "「友達の妊娠、それは私たちの関係も変えていく」",
      quoteEn: "“Her unexpected pregnancy gradually changes everything between us.”",
      descJa: "東京・中目黒でルームシェア生活を送る2人の働く女性。一人の予期せぬ妊娠をきっかけに、家族でも恋人でもない二人の絶妙な関係性がグラデーションのように変化していくスタイリッシュなビタードラマ。",
      descEn: "Two female roommates in Tokyo navigate the subtle shift in their deep friendship and personal independence when one discovers she is pregnant and decides to keep the baby."
    },
    {
      genreId: "bitter",
      titleJa: "カケラ",
      titleEn: "A Piece of Our Life",
      castJa: "満島ひかり, 中村映里子",
      castEn: "Hikari Mitsushima, Eriko Nakamura",
      dirJa: "安藤桃子",
      dirEn: "Momoko Ando",
      infoJa: "2010年 / 107分 / 日本",
      infoEn: "2010 / 107 min / Japan",
      quoteJa: "「女の子同士の恋愛って、そんなに特別なこと？」",
      quoteEn: "“Is love between two women really something so strange?”",
      descJa: "自分勝手な彼氏との関係に虚しさを抱く女子大生が、意思の強いメディカル・アーティストの女性と出会い恋に落落つ。歪んだ独占欲や依存心が交錯するリアルで切ない女性同士の愛憎劇。",
      descEn: "Unfulfilled in her relationship with her boyfriend, a college student falls for a confident female prosthetic artist, embarking on a turbulent journey of desire, possessiveness, and passion."
    },
    {
      genreId: "bitter",
      titleJa: "パッセージ",
      titleEn: "Passages",
      castJa: "フランツ・ロゴフスキ, アデル・エグザルホプロス, ベン・ウィショー",
      castEn: "Franz Rogowski, Adèle Exarchopoulos, Ben Whishaw",
      dirJa: "アイラ・サックス",
      dirEn: "Ira Sachs",
      infoJa: "2023年 / 91分 / フランス・ドイツ",
      infoEn: "2023 / 91 min / France, Germany",
      quoteJa: "「誰かを愛することは、こんなにも身勝手で切ない」",
      quoteEn: "“Loving someone can be so destructive and utterly selfish.”",
      descJa: "パリを舞台に、同性婚関係にある映画監督の男が若き女性と一夜を共にしたことで巻き起こる愛憎。男女の境界を超えて人間のエゴと愛の脆さを剥き出しにしたビターな人間ドラマ。",
      descEn: "In Paris, a narcissistic male filmmaker's long-term marriage to his husband unravels after he begins an impulsive affair with a young schoolteacher, exploring painful relationship dynamics."
    },
    {
      genreId: "bitter",
      titleJa: "Blue",
      titleEn: "Blue",
      castJa: "市川実日子, 小西真奈美",
      castEn: "Mikako Ichikawa, Manami Konishi",
      dirJa: "安藤尋",
      dirEn: "Hiroshi Ando",
      infoJa: "2002年 / 116分 / 日本",
      infoEn: "2002 / 116 min / Japan",
      quoteJa: "「息が苦しくなるほど、あなたに触れていたい」",
      quoteEn: "“I want to feel you close, so deeply that it leaves me breathless.”",
      descJa: "日本海の海辺の町。どこか孤立した空気を纏う2人の女子高生が密かに惹かれ合い、寄り添うように身体を重ねる。思春期特有の痛切な孤独と静寂を描いた至高の百合作品。",
      descEn: "In a quiet coastal town in Japan, two isolated high school girls forge a secret physical and emotional bond, offering each other escape from unbearable loneliness."
    },
    {
      genreId: "bitter",
      titleJa: "ふたりのマイルーム",
      titleEn: "The Feels",
      castJa: "コンスタンス・ウー, アンジェラ・トリンバー",
      castEn: "Constance Wu, Angela Trimbur",
      dirJa: "ジェンジ・コーハン",
      dirEn: "Jenée LaMarque",
      infoJa: "2017年 / 88分 / アメリカ",
      infoEn: "2017 / 88 min / USA",
      quoteJa: "「完璧に見える関係にも、秘密はある」",
      quoteEn: "“Even the most perfect relationship has its hidden truths.”",
      descJa: "結婚を目前に控えたレズビアンカップルが、友人たちを集めて開催した独身サヨナラパーティー。酒席でのふとした告白から互いの本音と葛藤が浮き彫りになるビターな群像コメディドラマ。",
      descEn: "A group of friends gathers for a bachelorette weekend to celebrate a lesbian couple's upcoming wedding, but an unexpected confession leads to deep emotional friction and self-discovery."
    },
    {
      genreId: "bitter",
      titleJa: "わたしはロランス",
      titleEn: "Laurence Anyways",
      castJa: "メルヴィル・プポー, スザンヌ・クレマン",
      castEn: "Melvil Poupaud, Suzanne Clément",
      dirJa: "グザヴィエ・ドラン",
      dirEn: "Xavier Dolan",
      infoJa: "2012年 / 168分 / カナダ・フランス",
      infoEn: "2012 / 168 min / Canada, France",
      quoteJa: "「君を愛している。でも、自分自身を偽ることはできない」",
      quoteEn: "“I love you, but I cannot go on living a lie.”",
      descJa: "30歳の誕生日に「女性として生きたい」と打ち明けた男性国語教師と、彼を深く愛しながらも激しく葛藤する恋人フレッド。10年間にわたる2人の揺れ動く愛の葛藤と絆を描いた圧倒的色彩の人間ドラマ。",
      descEn: "When a high school teacher reveals his inner truth to live as a woman, he and his passionate girlfriend navigate a complex, decade-long journey of enduring love, identity, and heartbreak."
    },
    {
      genreId: "bitter",
      titleJa: "彼女のいない部屋",
      titleEn: "Hold Me Tight",
      castJa: "ヴィッキー・クリープス, マチュー・アマルリック",
      castEn: "Vicky Krieps, Mathieu Amalric",
      dirJa: "マチュー・アマルリック",
      dirEn: "Mathieu Amalric",
      infoJa: "2021年 / 97分 / フランス",
      infoEn: "2021 / 97 min / France",
      quoteJa: "「立ち止まれば、哀しみに押しつぶされてしまうから」",
      quoteEn: "“If I stop moving, the sorrow will overwhelm me completely.”",
      descJa: "ある朝、夫と子どもたちを残して家を出た一人の女性。彼女のあてのない孤独な旅路と、残された家族の日常が交錯する中で明かされる、抱えきれない喪失感と愛のビターな記憶。",
      descEn: "A woman appears to abandon her family one morning, embarking on a solitary journey. As past memories and current realities merge, a deeply moving story of grief and emotional resilience unfolds."
    },
    {
      genreId: "bitter",
      titleJa: "マイ・ファースト・サマー",
      titleEn: "My First Summer",
      castJa: "マークエラ・カヴェナ, メイヴ・ディモディ",
      castEn: "Markella Kavenagh, Maiah Stewardson",
      dirJa: "ケイティ・ファウンド",
      dirEn: "Katie Found",
      infoJa: "2020年 / 78分 / オーストラリア",
      infoEn: "2020 / 78 min / Australia",
      quoteJa: "「世界が私達を見つけるまで、ここでふたりだけでいよう」",
      quoteEn: "“Until the world finds us, let's stay right here together.”",
      descJa: "世間から隔離された隠れ家で母を亡くした少女が、町からやってきた天真爛漫な少女と出会う。美しく密やかな湖畔で傷を舐め合い育まれる悲しくも眩しい秘密のロマンス。",
      descEn: "Raised in isolation from the outside world, a grieving 16-year-old girl meets an adventurous teenager, creating a fragile sanctuary of healing love and discovery."
    },
    {
      genreId: "bitter",
      titleJa: "クロゼットの失楽園",
      titleEn: "Lost and Delirious",
      castJa: "パイパー・ペラーボ, ミーシャ・バートン",
      castEn: "Piper Perabo, Mischa Barton",
      dirJa: "レア・プール",
      dirEn: "Léa Pool",
      infoJa: "2001年 / 103分 / カナダ",
      infoEn: "2001 / 103 min / Canada",
      quoteJa: "「偽りの自分を演じるくらいなら、狂気に沈む方がマシだ」",
      quoteEn: "“I'd rather be madly in love than pretend to be normal.”",
      descJa: "全寮制の女子校。ルームメイトとして深く愛し合っていた2人の少女。だが世間の目を恐れた一方が男性との交際を選んだことで、もう一人の情熱は純粋ゆえの狂気へと加速していく悲劇。",
      descEn: "At a prestigious boarding school, two roommates share a passionate secret romance. When fear of social rejection forces one back into conformity, it drives the other to heartbreaking extremes."
    },
  
    // ==========================================
    // 🌱 あの頃の青春 (Youth)
    // ==========================================
    {
      genreId: "youth",
      titleJa: "さよならくちびる",
      titleEn: "Farewell Song",
      castJa: "小松菜奈, 門脇麦, 成田凌",
      castEn: "Nana Komatsu, Mugi Kadowaki, Ryo Narita",
      dirJa: "塩田明彦",
      dirEn: "Akihiko Shiota",
      infoJa: "2019年 / 116分 / 日本",
      infoEn: "2019 / 116 min / Japan",
      quoteJa: "「この歌が終わったら、私たちは解散する」",
      quoteEn: "“Once this song is finished, our road together ends.”",
      descJa: "解散を決めた人気女性アコースティックデュオ「ハルレオ」。ローディの男性を交えた解散ツアーの途上、互いへの切ない恋心と言葉にできない執着が音楽に乗せて響き合う感動の音楽青春映画。",
      descEn: "During a farewell concert tour across Japan, two female indie folk duo partners confront their complex, unspoken romantic feelings and emotional dependance through music."
    },
    {
      genreId: "youth",
      titleJa: "志乃ちゃんは自分の名前が言えない",
      titleEn: "Shino Cannot Say Her Own Name",
      castJa: "南沙良, 蒔田彩珠",
      castEn: "Sara Minami, Aju Makita",
      dirJa: "湯浅弘章",
      dirEn: "Hiroaki Yuasa",
      infoJa: "2018年 / 110分 / 日本",
      infoEn: "2018 / 110 min / Japan",
      quoteJa: "「上手にしゃべれなくても、私の歌は届くのかな」",
      quoteEn: "“Even if I stumble over words, can you still hear my true voice?”",
      descJa: "吃音のため上手く話せない少女と、音楽を愛しながら音痴な少女。孤独を抱えた2人が校舎の屋上で音楽を通じて心を通わせ、世界の不器用さと対峙する感動的な青春模様。",
      descEn: "A high school girl who stutters forms a unique musical bond with an outcast guitarist classmate, building a powerful friendship that helps them navigate youth."
    },
    {
      genreId: "youth",
      titleJa: "思いのほかの恋",
      titleEn: "The Incredibly True Adventure of Two Girls in Love",
      castJa: "ローレル・ホロマン, ニコル・アリ・パーカー",
      castEn: "Laurel Holloman, Nicole Ari Parker",
      dirJa: "マリア・マグエンティ",
      dirEn: "Maria Maggenti",
      infoJa: "1995年 / 94分 / アメリカ",
      infoEn: "1995 / 94 min / USA",
      quoteJa: "「あなたと一緒にいると、世界がまったく違って見える」",
      quoteEn: "“Being with you makes the whole world feel entirely brand new.”",
      descJa: "ボーイッシュでアウトローな白人少女と、裕福でおしゃれなアフリカ系優等生少女。対照的な2人の女子高生が出会い、互いの違いを超えて惹かれ合っていく甘酸っぱく瑞々しい90年代青春映画の名作。",
      descEn: "A tomboyish, working-class high school girl and a popular, wealthy classmate form an unexpected, sweet romantic bond that challenges their different backgrounds."
    },
    {
      genreId: "youth",
      titleJa: "ひらいて",
      titleEn: "Unlock Your Heart",
      castJa: "山田杏奈, 芋生悠, 作間龍斗",
      castEn: "Anna Yamada, Haruka Imou, Ryuto Sakuma",
      dirJa: "首藤凜",
      dirEn: "Rin Shuto",
      infoJa: "2021年 / 121分 / 日本",
      infoEn: "2021 / 121 min / Japan",
      quoteJa: "「あなたの秘密を、私に見せて」",
      quoteEn: "“Open up and show me all of your hidden secrets.”",
      descJa: "校内の人気者である女子高生が、密かに思いを寄せる男子生徒に秘密の恋人がいることを知る。その相手である地味な女子生徒へと屈折した関心を向け急接近していく歪で美しい欲望の物語。",
      descEn: "A popular high school girl becomes dangerously obsessed with an introverted female classmate who is secretly dating the boy she likes, pushing boundaries of intimacy."
    },
    {
      genreId: "youth",
      titleJa: "ファースト・ガールズ",
      titleEn: "First Girl I Loved",
      castJa: "ディラン・ゲルラ, ブリアンヌ・ヒューイ",
      castEn: "Dylan Gelula, Brianna Hildebrand",
      dirJa: "ケラム・サンガ",
      dirEn: "Kerem Sanga",
      infoJa: "2016年 / 91分 / アメリカ",
      infoEn: "2016 / 91 min / USA",
      quoteJa: "「初めて誰かを本気で好きになった。それが彼女だったの」",
      quoteEn: "“For the first time, I fell in love—and it happened to be with her.”",
      descJa: "校内新聞の取材をきっかけに、ソフトボール部のスター選手に恋をした17歳の写真部少女。SNSや周囲の視線、初恋の戸惑いに苛まれながらも自分らしさを模索する等身大の甘酸っぱい青春ドラマ。",
      descEn: "A 17-year-old high school photographer falls in love with the star of the girls' softball team, facing complex social dynamics and self-discovery during her turbulent first romance."
    },
    {
      genreId: "youth",
      titleJa: "少女",
      titleEn: "Night's Tightrope",
      castJa: "本田翼, 山本美月",
      castEn: "Tsubasa Honda, Mizuki Yamamoto",
      dirJa: "三島有紀子",
      dirEn: "Yukiko Mishima",
      infoJa: "2016年 / 119分 / 日本",
      infoEn: "2016 / 119 min / Japan",
      quoteJa: "「人が死ぬ瞬間を見たら、生きている意味がわかるのかな」",
      quoteEn: "“If I see someone die, will I finally understand what living means?”",
      descJa: "「人が死ぬ瞬間を見てみたい」という危険な欲望を密かに心に秘めた2人の女子高生。心に傷を負った親友同士が死生観の深淵に踏み込んでいくミステリアスで美しいダーク青春劇。",
      descEn: "Two traumatized high school best friends spend their summer vacation secretly trying to witness a person's death, exploring dark psychological depths and bound affection."
    },
    {
      genreId: "youth",
      titleJa: "ショー・ミー・ラブ（ガールフレンド）",
      titleEn: "Show Me Love",
      castJa: "レベッカ・リリエベリ, アレクサンドラ・ダールストレム",
      castEn: "Rebecka Liljeberg, Alexandra Dahlström",
      dirJa: "ルーカス・ムーディソン",
      dirEn: "Lukas Moodysson",
      infoJa: "1998年 / 89分 / スウェーデン",
      infoEn: "1998 / 89 min / Sweden",
      quoteJa: "「この退屈な町で、あなただけが私の希望」",
      quoteEn: "“In this dead-end town, you are my only ray of hope.”",
      descJa: "スウェーデンの退屈で閉鎖的な田舎町。地味で浮いていた少女と学校一の人気者の少女。誤解や周囲の好奇の目を乗り越え純粋に惹かれ合う姿を描いた甘酸っぱい青春レズビアン映画の名作。",
      descEn: "In a boring Swedish town, an outcast, lonely girl who harbors a secret crush on the school's most popular girl finds her world transformed when her love is unexpectedly returned."
    },
    {
      genreId: "youth",
      titleJa: "金魚つくし",
      titleEn: "Water Lilies",
      castJa: "アデル・エネル, ポーリーヌ・アキュアール",
      castEn: "Adèle Haenel, Pauline Acquart",
      dirJa: "セリーヌ・シアマ",
      dirEn: "Céline Sciamma",
      infoJa: "2007年 / 85分 / フランス",
      infoEn: "2007 / 85 min / France",
      quoteJa: "「息を止めて、あなただけを見つめていた」",
      quoteEn: "“I held my breath, unable to look away from you.”",
      descJa: "郊外の公営プールを舞台に、シンクロナイズドスイミングの美しい主将に惹かれていく15歳の少女。セリーヌ・シアマ監督が長編デビュー作で描いた、欲望と秘密に満ちた眩しく鋭い思春期の目覚め。",
      descEn: "In a Parisian suburb, a quiet 15-year-old girl becomes captivated by the captain of the synchronized swimming team, navigating the delicate and raw awakenings of teenage obsession."
    },
    {
      genreId: "youth",
      titleJa: "恋のゆくえ",
      titleEn: "All Over Me",
      castJa: "アリソン・フォランド, タラ・サブコフ",
      castEn: "Alison Folland, Tara Subkoff",
      dirJa: "アレックス・シカヘル",
      dirEn: "Alex Sichel",
      infoJa: "1997年 / 90分 / アメリカ",
      infoEn: "1997 / 90 min / USA",
      quoteJa: "「言葉にできない気持ちが、胸の中で叫んでいる」",
      quoteEn: "“Unspoken feelings are screaming deep inside my heart.”",
      descJa: "90年代ニューヨーク・ヘルズキッチン。パンクロックとライオット・ガール運動の熱気の中、親友への言えない恋心と厳しい現実に揺れ動く10代少女のリアルで鋭利な青春エモドラマ。",
      descEn: "Set against the backdrop of 1990s New York riot grrrl punk scene, a teenage girl navigates her unrequited romantic feelings for her troubled best friend."
    },
    {
      genreId: "youth",
      titleJa: "マイ・ベスト・フレンド",
      titleEn: "My Best Friend",
      castJa: "モラ・アレナ・ライセン, モレナ・ゴトラ",
      castEn: "Mora Arenillas, Morena Gotter",
      dirJa: "マルティン・ドゥスパバ",
      dirEn: "Martín Deus",
      infoJa: "2018年 / 90分 / アルゼンチン",
      infoEn: "2018 / 90 min / Argentina",
      quoteJa: "「君の存在が、僕の知っていた世界をひっくり返した」",
      quoteEn: "“Your presence completely rewrote the world I thought I knew.”",
      descJa: "静かな家族のもとに家庭の事情で引き取られてきた問題児の少年。同居生活の中で互いの居場所となり、複雑な感情を深めていく2人の少年の繊細で透明感あふれる青春成長物語。",
      descEn: "When a family takes in a troubled friend's teenage son, two boys form an intense, quiet personal connection that changes their understanding of love and friendship."
    },
  
    // ==========================================
    // 🎬 実話ベース (True Stories)
    // ==========================================
    {
      genreId: "true-story",
      titleJa: "アンモナイトの目覚め",
      titleEn: "Ammonite",
      castJa: "ケイト・ウィンスレット, シアーシャ・ローナン",
      castEn: "Kate Winslet, Saoirse Ronan",
      dirJa: "フランシス・リー",
      dirEn: "Francis Lee",
      infoJa: "2020年 / 120分 / イギリス・オーストラリア",
      infoEn: "2020 / 120 min / UK, Australia",
      quoteJa: "「化石の中に隠されていた、私の本当の情熱」",
      quoteEn: "“You have awakened something deep within me.”",
      descJa: "1840年代イギリス。実在の人間的評価に恵まれなかった天才古生物学者メアリー・アニングと、療養のため彼女のもとに預けられた病弱な人妻の恋。静かな海岸で化石と共に発掘される真実の情愛。",
      descEn: "In 1840s England, acclaimed palaeontologist Mary Anning and a young convalescent married woman form an intense, life-changing romantic relationship along the rugged Dorset coastline."
    },
    {
      genreId: "true-story",
      titleJa: "プライドと偏見とエリートたち",
      titleEn: "Pride",
      castJa: "ビル・ナイ, イメルダ・スタウントン, ジョージ・マッケイ",
      castEn: "Bill Nighy, Imelda Staunton, George MacKay",
      dirJa: "マシュー・ウォーチャス",
      dirEn: "Matthew Warchus",
      infoJa: "2014年 / 120分 / イギリス",
      infoEn: "2014 / 120 min / UK",
      quoteJa: "「誰かが虐げられているなら、私たちは共に立ち上がる」",
      quoteEn: "“When someone is being oppressed, we stand together.”",
      descJa: "1984年サッチャー政権下のイギリス。ストライキを行う炭鉱労働者たちを支援するため立ち上がったLGSM（炭鉱夫を支えるレズビアンとゲイの会）の実在の連帯と友情を描いた胸熱く感動的な実話ストーリー。",
      descEn: "Based on the inspiring true story of London-based gay and lesbian activists who raised funds to support striking Welsh miners in 1984, forging an unlikely alliance."
    },
    {
      genreId: "true-story",
      titleJa: "フリーヘルド 最初の愛の証明",
      titleEn: "Freeheld",
      castJa: "ジュリアン・ムーア, エレン・ペイジ, マイケル・シャノン",
      castEn: "Julianne Moore, Elliot Page, Michael Shannon",
      dirJa: "ピーター・ソレット",
      dirEn: "Peter Sollett",
      infoJa: "2015年 / 103分 / アメリカ",
      infoEn: "2015 / 103 min / USA",
      quoteJa: "「私が求めているのは特別な権利じゃない、平等な権利だ」",
      quoteEn: "“I'm not asking for anything special, just equality.”",
      descJa: "末期ガンを言い渡された実在のベテラン女性警察官ローレル。長年勤め上げた遺族年金を同性パートナーに遺すべく、州の保守的な決定と戦い法的な権利を勝ち取った実話に基づく感動作。",
      descEn: "A decorated terminally ill New Jersey police officer fights a courageous legal battle against county board members to pass her earned pension to her domestic partner."
    },
    {
      genreId: "true-story",
      titleJa: "ワイルド・ナイツ・ウィズ・エミリー",
      titleEn: "Wild Nights with Emily",
      castJa: "モーリー・シャノン, スーザン・ジグラー",
      castEn: "Molly Shannon, Susan Ziegler",
      dirJa: "マドレーヌ・オウネク",
      dirEn: "Madeleine Olnek",
      infoJa: "2018年 / 84分 / アメリカ",
      infoEn: "2018 / 84 min / USA",
      quoteJa: "「世界が私を知らなくても、あなたが私を知っていればいい」",
      quoteEn: "“I care not for the world's approval, as long as I have yours.”",
      descJa: "内向的で孤独な一生を送ったと評されてきた伝説の詩人エミリ・ディキンスン。だが実際の彼女は、兄の妻スーと生涯にわたる熱烈で官能的な恋関係を結んでいたという史実に基づく伝記コメディ。",
      descEn: "This biographical comedy overturns popular history to reveal poet Emily Dickinson's passionate lifelong romantic love affair with her sister-in-law Susan."
    },
    {
      genreId: "true-story",
      titleJa: "ヴィータ＆ヴァージニア",
      titleEn: "Vita & Virginia",
      castJa: "ジェマ・アータートン, エリザベス・デビッキ",
      castEn: "Gemma Arterton, Elizabeth Debicki",
      dirJa: "シャニア・バトゥー",
      dirEn: "Chanya Button",
      infoJa: "2018年 / 110分 / イギリス・アイランド",
      infoEn: "2018 / 110 min / UK, Ireland",
      quoteJa: "「あなたは私の言葉に命を吹き込んでくれる」",
      quoteEn: "“You ignite a fire within my quiet mind.”",
      descJa: "1920年代のロンドン。名作『オーランドー』のインスピレーションの源となった、天才文学者ヴァージニア・ウルフと、社交界の華であった貴族女性詩人ヴィータの美しく激しい実在の愛情劇。",
      descEn: "Chronicles the dynamic and passionate real-life love affair between iconic author Virginia Woolf and aristocratic socialite Vita Sackville-West in 1920s England."
    },
    {
      genreId: "true-story",
      titleJa: "バトル・オブ・ザ・セクセス",
      titleEn: "Battle of the Sexes",
      castJa: "エマ・ストーン, アンドレア・ライズボロー, スティーヴ・カレル",
      castEn: "Emma Stone, Andrea Riseborough, Steve Carell",
      dirJa: "ヴァレリー・ファリス, ジョナサン・デイトン",
      dirEn: "Valerie Faris, Jonathan Dayton",
      infoJa: "2017年 / 121分 / アメリカ",
      infoEn: "2017 / 121 min / USA",
      quoteJa: "「世界を変えるための戦いは、コートの上だけじゃない」",
      quoteEn: "“Change happens on the court, but also deep inside our hearts.”",
      descJa: "1973年、世界中が注目したテニスの「性別適合マッチ」。男女格差と戦う世界女王ビリー・ジーン・キングが、美容師女性との出会いを通じて自らのセクシュアリティを自覚し解放していく実話。",
      descEn: "Tennis legend Billie Jean King fights for gender equity on court while privately embarking on a transformative journey of self-discovery through a romantic relationship with a female hairdresser."
    },
    {
      genreId: "true-story",
      titleJa: "ジェントルマン・ジャック",
      titleEn: "Gentleman Jack",
      castJa: "サランヌ・ジョーンズ, ソフィー・ランドル",
      castEn: "Suranne Jones, Sophie Rundle",
      dirJa: "サリー・ウェインライト",
      dirEn: "Sally Wainwright",
      infoJa: "2019年 / ドラマ全8話 / イギリス・アメリカ",
      infoEn: "2019 / TV Series (8 episodes) / UK, USA",
      quoteJa: "「私は自分らしく生きる。誰の許可も必要ない」",
      quoteEn: "“I will live as myself. I need no one's permission.”",
      descJa: "19世紀イギリス。実在の地主アン・リスター（ジェントルマン・ジャック）が、保守的な社会の偏見を打ち破り、所有地を経営しながら同性との真実の結婚と愛を堂々と追い求めた情熱のドラマシリーズ。",
      descEn: "Based on the real coded diaries of 19th-century landowner Anne Lister, who boldly managed her estate and pursued open romantic relationships with women in Victorian England."
    },
    {
      genreId: "true-story",
      titleJa: "マ・レイニーのブラックボトム",
      titleEn: "Ma Rainey's Black Bottom",
      castJa: "ヴィオラ・デイヴィス, チャドウィック・ボーズマン",
      castEn: "Viola Davis, Chadwick Boseman",
      dirJa: "ジョージ・C・ウルフ",
      dirEn: "George C. Wolfe",
      infoJa: "2020年 / 94分 / アメリカ",
      infoEn: "2020 / 94 min / USA",
      quoteJa: "「この歌は私のソウルだ。誰にも渡さない」",
      quoteEn: "“This music isn't just notes, it's my soul.”",
      descJa: "1920年代シカゴのレコーディングスタジオ。「ブルースの母」と呼ばれた実在の伝説的歌手マ・レイニーが、白人経営者たちの搾取に対抗し、同性愛を含めた自らの信念と誇りを誇示する白熱の音楽実話ドラマ。",
      descEn: "In 1920s Chicago, legendary 'Mother of the Blues' Ma Rainey fights for creative control, autonomy, and identity against white music executives during a fiery recording session."
    },
    {
      genreId: "true-story",
      titleJa: "コレット",
      titleEn: "Colette",
      castJa: "キーラ・ナイトレイ, ドミニク・ウェスト",
      castEn: "Keira Knightley, Dominic West",
      dirJa: "ウォッシュ・ウエストモアランド",
      dirEn: "Wash Westmoreland",
      infoJa: "2018年 / 111分 / イギリス・アメリカ",
      infoEn: "2018 / 111 min / USA, UK",
      quoteJa: "「私のペンは、私だけのもの」",
      quoteEn: "“The hand that holds the pen writes my own story.”",
      descJa: "20世紀初頭のパリ。夫のゴーストライターとして大ヒット作を生み出していた実在の女性作家コレットが、女性たちとの自由な恋愛と舞台活動を通じて自身の権利を取り戻し自立していく感動の伝記ドラマ。",
      descEn: "After writing a bestselling novel published under her husband's name, French author Colette fights for creative ownership, embracing romantic liberation and artistic independence."
    },
    {
      genreId: "true-story",
      titleJa: "ブライアン・ウィルソン ソング・ライター",
      titleEn: "Love & Mercy",
      castJa: "ジョン・キューザック, ポール・ダノ, エリザベス・バンクス",
      castEn: "John Cusack, Paul Dano, Elizabeth Banks",
      dirJa: "ビル・ポーラッド",
      dirEn: "Bill Pohlad",
      infoJa: "2014年 / 121分 / アメリカ",
      infoEn: "2014 / 121 min / USA",
      quoteJa: "「君の存在が、私の壊れた心に光をくれた」",
      quoteEn: "“Your presence brought music back to my broken heart.”",
      descJa: "ザ・ビーチ・ボーイズの天才ミュージシャン、ブライアン・ウィルソンの光と影。精神的苦痛と支配から逃れ、運命の女性メリンダとの出会いによって救われ再起を果たす奇跡の実話伝記映画。",
      descEn: "Unveils the brilliant musical mind and internal struggles of Beach Boys founder Brian Wilson, and how his romantic partner Melinda helped rescue him from a controlling environment."
    }
  ];