const worksData = [
// ==========================================
    // 👑 不朽の名作 (Masterpieces)
    // ==========================================
    {
      genreId: "masterpiece",
      titleJa: "作りたい女と食べたい女",
      titleEn: "She Loves to Cook, and She Loves to Eat",
      titleKo: "만들고 싶은 여자와 먹고 싶은 여자",
      castJa: "比嘉愛未, 西野恵未, 森田望智",
      castEn: "Manami Higa, Emi Nishino, Misato Morita",
      castKo: "히가 마나미, 니시노 에미, 모리타 미사토",
      dirJa: "松嵜由衣, 中田博之",
      dirEn: "Yui Matsuzaki, Hiroyuki Nakata",
      dirKo: "마츠자키 유이, 나카타 히로유키",
      infoJa: "2022年 / ドラマ全29話 / 日本",
      infoEn: "2022 / TV Series (29 episodes) / Japan",
      infoKo: "2022년 / 드라마 총 29화 / 일본",
      quoteJa: "「一緒においしいものを食べる、それだけのことがこんなに嬉しい」",
      quoteEn: "“Sharing a delicious meal with you makes me happier than anything else.”",
      quoteKo: "“함께 맛있는 것을 먹는, 그것만으로도 이렇게 기쁠 줄이야.”",
      descJa: "食を通じて心の距離を縮めていく2人の女性。自らの生き方や性的指向、アイデンティティに向き合う姿を心温まる繊細さで丁寧に描き出し、多くの共感と絶賛を集めたNHKドラマの金字塔。",
      descEn: "Two women form a deep, healing connection through home-cooked meals. This highly acclaimed drama thoughtfully portrays self-discovery, identity, sexual orientation, and quiet emotional intimacy in modern Japan.",
      descKo: "음식을 통해 마음의 거리를 줄여가는 두 여성. 자신의 삶의 방식과 성적 지향, 정체성을 면밀히 마주하는 모습을 따뜻하고 섬세하게 그려내며 수많은 공감과 찬사를 받은 NHK 드라마의 금자탑."
    },
    {
      genreId: "masterpiece",
      titleJa: "キャロル",
      titleEn: "Carol",
      titleKo: "캐롤",
      castJa: "ケイト・ブランシェット, ルーニー・マーラ",
      castEn: "Cate Blanchett, Rooney Mara",
      castKo: "케이트 블란쳇, 루니 마라",
      dirJa: "トッド・ヘインズ",
      dirEn: "Todd Haynes",
      dirKo: "토드 헤인즈",
      infoJa: "2015年 / 118分 / アメリカ・イギリス",
      infoEn: "2015 / 118 min / USA, UK",
      infoKo: "2015년 / 118분 / 미국, 영국",
      quoteJa: "「ただ、あなたに会いたかった」",
      quoteEn: "“I just wanted to see you.”",
      quoteKo: "“그냥, 너를 만나고 싶었어.”",
      descJa: "1950年代のニューヨークを舞台に、気品溢れる裕福な既婚女性と若きカメラマン志望の高級百貨店店員の運命的な恋と葛藤を描いた至高の純愛映画史的名作。",
      descEn: "Set in conservative 1950s New York, this film cinematic masterpiece depicts the transformative and deeply emotional love story between an elegant married socialite and a aspiring young photographer.",
      descKo: "1950년대 뉴욕을 배경으로 품격 있고 부유한 유부녀와 젊은 사진작가 지망생인 백화점 점원의 운명적인 사랑과 갈등을 그린 지고지순한 순애보 영화사의 걸작."
    },
    {
      genreId: "masterpiece",
      titleJa: "燃ゆる女の肖像",
      titleEn: "Portrait of a Lady on Fire",
      titleKo: "타오르는 여인의 초상",
      castJa: "ノエミ・メルラン, アデル・エネル",
      castEn: "Noémie Merlant, Adèle Haenel",
      castKo: "노에미 멜랑, 아델 에넬",
      dirJa: "セリーヌ・シアマ",
      dirEn: "Céline Sciamma",
      dirKo: "셀린 시아마",
      infoJa: "2019年 / 122分 / フランス",
      infoEn: "2019 / 122 min / France",
      infoKo: "2019년 / 122분 / 프랑스",
      quoteJa: "「私を見て。あなたを覚えているから」",
      quoteEn: "“Look at me. Remember.”",
      quoteKo: "“나를 봐요. 당신을 기억할 수 있도록.”",
      descJa: "18世紀末のフランス孤島。見つめ合う女性画家と結婚を目前に控えた令嬢の静謐で激しい愛を描き、カンヌ国際映画祭で脚本賞とクィア・パルム賞を受賞した歴史的傑作。",
      descEn: "On an isolated island in 18th-century Brittany, a female painter and her reluctant subject fall deeply in love, captured through poetic artistic gaze, profound passion, and mutual respect.",
      descKo: "18세기 말 프랑스의 고립된 섬. 서로를 응시하는 여성 화가와 결혼을 앞둔 영애의 정숙하면서도 강렬한 사랑을 그려내며 칸 영화제 각본상과 퀴어 종려상을 수상한 역사적 걸작."
    },
    {
      genreId: "masterpiece",
      titleJa: "オーシャンズ8",
      titleEn: "Ocean's 8",
      titleKo: "오션스 8",
      castJa: "サンドラ・ブロック, ケイト・ブランシェット, アン・ハサウェイ",
      castEn: "Sandra Bullock, Cate Blanchett, Anne Hathaway",
      castKo: "산드라 블록, 케이트 블란쳇, 앤 헤서웨이",
      dirJa: "ゲイリー・ロス",
      dirEn: "Gary Ross",
      dirKo: "게리 로스",
      infoJa: "2018年 / 110分 / アメリカ",
      infoEn: "2018 / 110 min / USA",
      infoKo: "2018년 / 110분 / 미국",
      quoteJa: "「どこかでこれを見ている、犯罪者を目指す8歳の少女のために」",
      quoteEn: "“To some 8-year-old girl lying in bed, dreaming of becoming a criminal.”",
      quoteKo: "“어디선가 이걸 보고 있을, 범죄자를 꿈꾸는 8살 소녀를 위해”",
      descJa: "固い絆と阿吽の呼吸で結ばれた強烈なカリスマ相棒コンビが率いる最強の女性犯罪プロフェッショナル集団。メットガラで極上の宝石奪取に挑む爽快エンタテインメント。",
      descEn: "An all-female crew led by two fiercely loyal, highly synchronized long-time partners plots an audacious high-stakes heist at New York's Met Gala in this stylish crime comedy.",
      descKo: "끈끈한 유대와 완벽한 호흡으로 뭉친 강력한 카리스마의 파트너 콤비가 이끄는 최정예 여성 범죄 전문가 집단. 멧 갈라에서 최고급 보석 탈취에 도전하는 통쾌한 엔터테인먼트 영화."
    },
    {
      genreId: "masterpiece",
      titleJa: "アデル、ブルーは熱い色",
      titleEn: "Blue Is the Warmest Color",
      titleKo: "가장 따뜻한 색, 블루",
      castJa: "レア・セドゥ, アデル・エグザルホプロス",
      castEn: "Léa Seydoux, Adèle Exarchopoulos",
      castKo: "레아 세두, 아델 에그자르코풀로스",
      dirJa: "アブデラティフ・ケシシュ",
      dirEn: "Abdellatif Kechiche",
      dirKo: "압델라티프 케시시",
      infoJa: "2013年 / 179分 / フランス",
      infoEn: "2013 / 179 min / France",
      infoKo: "2013년 / 179분 / 프랑스",
      quoteJa: "「私にはあなたとの無限の温もりが必要なの」",
      quoteEn: "“I have infinite tenderness for you. I always will.”",
      quoteKo: "“내겐 당신을 향한 무한한 다정함이 있어요. 언제까지나요.”",
      descJa: "青い髪をした美大生との出会いによって情熱的な愛を知る少女の成長、すれ違い、そして愛の変遷。カンヌ国際映画祭でパルム・ドールを獲得した圧倒的官能ドラマ。",
      descEn: "A French teenager experiences intense passion, emotional growth, and heartrending artistic and romantic devotion after falling in love with a charismatic, blue-haired art student.",
      descKo: "파란 머리의 미대생과의 만남을 통해 열정적인 사랑을 알게 되는 소녀의 성장, 어긋남, 그리고 사랑의 변천. 칸 영화제에서 황금종려상을 수상한 압도적인 관능의 드라마."
    },
    {
      genreId: "masterpiece",
      titleJa: "彼女が好きなものは、彼女の愛したすべて",
      titleEn: "The World to Come",
      titleKo: "세상을 바꿀 수 있는",
      castJa: "キャサリン・ウォーターストン, ヴァネッサ・カービー",
      castEn: "Katherine Waterston, Vanessa Kirby",
      castKo: "캐서린 워터스턴, 바네사 커비",
      dirJa: "モナ・ファストヴォルド",
      dirEn: "Mona Fastvold",
      dirKo: "모나 패스트볼드",
      infoJa: "2020年 / 100分 / アメリカ",
      infoEn: "2020 / 100 min / USA",
      infoKo: "2020년 / 100분 / 미국",
      quoteJa: "「あなたと過ごす時間が、私に生命を与えてくれる」",
      quoteEn: "“Astonishment and joy are What I feel in your presence.”",
      quoteKo: "“당신과 함께 보내는 시간이 내게 생명을 불어넣어 줘요.”",
      descJa: "19世紀半ばのアメリカ東海岸の開拓地。苛酷な自然環境と孤独な日常の中で、隣同士の農家に暮らす2人の既婚女性が魂を揺さぶる強い精神的・身体的絆で結ばれていく抒情詩。",
      descEn: "In mid-19th century rural America, two neighboring farm wives enduring severe personal loss find solace, emotional liberation, and passionate intimacy in each other's arms.",
      descKo: "19세기 중반 미국 동부 해안의 개척지. 가혹한 자연환경과 고독한 일상 속에서 이웃한 농가에 사는 두 유부녀가 영혼을 뒤흔드는 강한 정신적·육체적 유대로 이어져 가는 서정시 같은 영화."
    },
    {
      genreId: "masterpiece",
      titleJa: "お嬢さん",
      titleEn: "The Handmaiden",
      titleKo: "아가씨",
      castJa: "キム・ミニ, キム・テリ",
      castEn: "Kim Min-hee, Kim Tae-ri",
      castKo: "김민희, 김태리",
      dirJa: "パク・チャヌク",
      dirEn: "Park Chan-wook",
      dirKo: "박찬욱",
      infoJa: "2016年 / 145分 / 韓国",
      infoEn: "2016 / 145 min / South Korea",
      infoKo: "2016년 / 145분 / 대한민국",
      quoteJa: "「私の人生を壊しに来た私の救世主」",
      quoteEn: "“My destroyer, my savior.”",
      quoteKo: "“내 인생을 망치러 나간 나의 구원자”",
      descJa: "1930年代の日本統治下の朝鮮。莫大な遺産を継いだ謎めいた令嬢と、彼女を騙すために潜入したスリの少女。陰謀と愛憎を打ち破り真実の愛で連帯する極上の愛憎サスペンス。",
      descEn: "Set during 1930s Japanese-occupied Korea, a wealthy heiress and her newly hired Korean maid become unexpectedly enraptured in a passionate relationship, subverting a complex swindle plot.",
      descKo: "1930년대 일제강점기 조선. 막대한 재산을 상속받게 된 수줍은 귀족 영애와 그녀의 재산을 노리고 하녀로 잠입한 소매치기 소녀. 음모와 애증을 깨부수고 진정한 사랑으로 연대하는 최고의 서스펜스 걸작."
    },
    {
      genreId: "masterpiece",
      titleJa: "海街diary",
      titleEn: "Our Little Sister",
      titleKo: "바닷마을 다이어리",
      castJa: "綾瀬はるか, 長澤まさみ, 夏帆, 広瀬すず",
      castEn: "Haruka Ayase, Masami Nagasawa, Kaho, Suzu Hirose",
      castKo: "아야세 하루카, 나가사와 마사미, 카호, 히로세 스즈",
      dirJa: "是枝裕和",
      dirEn: "Hirokazu Kore-eda",
      dirKo: "고레에다 히로카즈",
      infoJa: "2015年 / 128分 / 日本",
      infoEn: "2015 / 128 min / Japan",
      infoKo: "2015년 / 128분 / 일본",
      quoteJa: "「美しいものを美しいと思えることが、幸せなんだと思う」",
      quoteEn: "“To find beautiful things beautiful is happiness in itself.”",
      quoteKo: "“아름다운 것을 아름답다고 느낄 수 있다는 게, 그게 행복인 것 같아요.”",
      descJa: "鎌倉の古い一軒家で暮らす三姉妹が、父の死亡をきっかけに異母妹を引き取り、互いを慈しみながら真の家族として絆を深めていく、四姉妹の静けさと温もりに満ちた佳作。",
      descEn: "Three sisters living together in Kamakura invite their young half-sister into their home following their father's death, building an irreplaceable sisterly bond across passing seasons.",
      descKo: "가마쿠라의 오래된 주택에서 함께 사는 세 자매가 아버지의 죽음을 계기로 배다른 여동생을 거두어들이고, 서로를 보듬으며 진정한 가족으로서 유대를 깊이 다져가는 네 자매의 잔잔하고 따뜻한 명작."
    },
    {
      genreId: "masterpiece",
      titleJa: "彼女（映画）",
      titleEn: "Ride or Die",
      titleKo: "그녀",
      castJa: "水原希子, さとうほなみ",
      castEn: "Kiko Mizuhara, Honami Sato",
      castKo: "미즈하라 키코, 사토 호나미",
      dirJa: "廣木隆一",
      dirEn: "Ryuichi Hiroki",
      dirKo: "히로키 류이치",
      infoJa: "2021年 / 142分 / 日本",
      infoEn: "2021 / 142 min / Japan",
      infoKo: "2021년 / 142분 / 일본",
      quoteJa: "「あなたのためなら、なんだってできる」",
      quoteEn: "“I would do absolutely anything for you.”",
      quoteKo: "“너를 위해서라면 뭐든 할 수 있어.”",
      descJa: "夫から凄惨な家庭内暴力を受けていた女性と、彼女の哀しみを見かねて夫を殺害したかつての同級生。逃避行の中で狂おしく交錯する愛執と解放を描いた極限のロードムービー。",
      descEn: "A woman kills her high school crush's abusive husband to protect her. Together, the two women embark on a desperate road trip filled with raw, conflicting, and inescapable desire.",
      descKo: "남편으로부터 참혹한 가정폭력을 당하던 여성과, 그녀의 슬픔을 견디다 못해 남편을 살해한 옛 동창. 도피 행각 속에서 광기 어리게 교차하는 애착과 해방을 그린 극한의 로드무비."
    },
    {
      genreId: "masterpiece",
      titleJa: "あのこは貴族",
      titleEn: "Aristocrats",
      titleKo: "조제, 호랑이 그리고 물고기들...이 아닌 '저 문 앞의 상류층' / 그네들의 연대",
      castJa: "門脇麦, 水原希子",
      castEn: "Mugi Kadowaki, Kiko Mizuhara",
      castKo: "카도와키 무기, 미즈하라 키코",
      dirJa: "岨手由貴子",
      dirEn: "Yukiko Sode",
      dirKo: "소데 유키코",
      infoJa: "2021年 / 124分 / 日本",
      infoEn: "2021 / 124 min / Japan",
      infoKo: "2021년 / 124분 / 일본",
      quoteJa: "「私たちは、別の世界を生きているわけじゃない」",
      quoteEn: "“We are not living in entirely separate worlds after all.”",
      quoteKo: "“우리가 완전히 다른 세계를 살아가고 있는 건 아니야.”",
      descJa: "東京の政財界家系で生まれ育った箱入り娘と、地方から自力で上京し都会の壁に突き当たる女性。男性社会の分断を超えて共鳴し、自立への道を歩み出す美しい連帯の物語。",
      descEn: "Two women from vastly different social strata in contemporary Tokyo cross paths, overcoming invisible societal barriers to form a quiet mutual understanding and claim their independence.",
      descKo: "도쿄의 정재계 가문에서 자란 온실 속 화초 같은 여성과, 지방에서 혈혈단신 상경해 도시의 벽에 부딪히는 여성. 남성 중심 사회의 장벽을 넘어 서로 공감하며 자립의 길로 나아가는 아름다운 연대의 이야기."
    },
    // ==========================================
    // 💖 ときめき (Romance)
    // ==========================================
    {
      genreId: "romance",
      titleJa: "彩香ちゃんは弘子先輩に恋してる",
      titleEn: "Ayaka is in Love with Hiroko-senpai",
      titleKo: "아야카 양은 히로코 선배를 사랑하고 있어",
      castJa: "加藤史帆, 森カンナ",
      castEn: "Shiho Kato, Kanna Mori",
      castKo: "카토 시호, 모리 칸나",
      dirJa: "のむらなお, 枝優花",
      dirEn: "Nao Nomura, Yuka Eda",
      dirKo: "노무라 나오, 에다 유카",
      infoJa: "2024年 / ドラマ全8話 / 日本",
      infoEn: "2024 / TV Series (8 episodes) / Japan",
      infoKo: "2024년 / 드라마 총 8화 / 일본",
      quoteJa: "「先輩の特別になりたいんです！」",
      quoteEn: "“I want to be someone truly special to you, Senpai!”",
      quoteKo: "“선배의 특별한 사람이 되고 싶어요!”",
      descJa: "猛烈アタックを繰り広げる猪突猛進な後輩社員と、過去のトラウマから自身がレズビアンであることを隠すクールな先輩。すれ違いがもどかしくも最高に愛おしいオフィス・オフィスラブコメディ。",
      descEn: "An enthusiastic, headstrong junior office worker openly courts her cool, secretly lesbian senior colleague in this delightfully sweet and hilarious office romance drama.",
      descKo: "맹렬한 어프로치를 펼치는 저돌적인 직진 후배 사원과, 과거의 트라우마 때문에 자신이 레즈비언이라는 사실을 숨기는 쿨한 선배. 엇갈림이 안타까우면서도 최고로 사랑스러운 오피스 러브 코미디."
    },
    {
      genreId: "romance",
      titleJa: "チェイサーゲームW パワハラ上司は私の元カノ",
      titleEn: "Chaser Game W",
      titleKo: "체이서 게임 W 갑질 상사는 나의 옛 여자친구",
      castJa: "菅井友香, 中村ゆりか",
      castEn: "Yuka Sugai, Yurika Nakamura",
      castKo: "스가이 유카, 나카무라 유리카",
      dirJa: "太田勇, 山口将幸",
      dirEn: "Yu Ota, Masayuki Yamaguchi",
      dirKo: "오타 유우, 야마구치 마사유키",
      infoJa: "2024年 / ドラマ全8話 / 日本",
      infoEn: "2024 / TV Series (8 episodes) / Japan",
      infoKo: "2024년 / 드라마 총 8화 / 일본",
      quoteJa: "「忘れたなんて言わせないから」",
      quoteEn: "“Don't you dare pretend you've forgotten about us.”",
      quoteKo: "“잊어버렸단 말은하게 두지 않을 테니까.”",
      descJa: "大手ゲーム開発会社でプロジェクトリーダーを務める主人公の前に、クライアント側の冷徹な上司としてあらわれたのは、かつて姿を消した大学時代の元カノだった。愛憎が交錯する愛憎劇。",
      descEn: "A gaming producer is shocked when her demanding new foreign client boss turns out to be her college ex-girlfriend, leading to a passionate blend of resentment, dynamic tension, and reignited love.",
      descKo: "대형 게임 개발회사에서 프로젝트 리더를 맡고 있는 주인공 앞에 클라이언트 측의 냉철한 상사로 나타난 사람은, 과거에 홀연히 자취를 감췄던 대학 시절의 옛 연인이었다. 애증이 교차하는 로맨스 드라마."
    },
    {
      genreId: "romance",
      titleJa: "チェイサーゲームW2 美しい僕ら",
      titleEn: "Chaser Game W Season 2",
      titleKo: "체이서 게임 W2 아름다운 우리",
      castJa: "菅井友香, 中村ゆりか",
      castEn: "Yuka Sugai, Yurika Nakamura",
      castKo: "스가이 유카, 나카무라 유리카",
      dirJa: "太田勇, 山口将幸",
      dirEn: "Yu Ota, Masayuki Yamaguchi",
      dirKo: "오타 유우, 야마구치 마사유키",
      infoJa: "2024年 / ドラマ全8話 / 日本",
      infoEn: "2024 / TV Series (8 episodes) / Japan",
      infoKo: "2024년 / 드라마 총 8화 / 일본",
      quoteJa: "「今度こそ、もう二度と離さない」",
      quoteEn: "“This time, I will never let you go again.”",
      quoteKo: "“이번만큼은, 두 번 다시 놓치지 않아.”",
      descJa: "数々の試練とすれ違いを乗り越えて再び結ばれた樹と冬雨。揺るぎない絆を深める2人が、互いの将来や社会の現実に立ち向かいながら歩む真実の愛の続編。",
      descEn: "Having reunited after painful misunderstandings, Itsuki and Fuyu navigate the realities of family expectations and career obstacles to protect their unwavering commitment to each other.",
      descKo: "수많은 시련과 엇갈림을 극복하고 다시 결합한 이츠키와 후유우. 흔들림 없는 유대를 다지는 두 사람이 서로의 미래와 사회의 현실에 맞서며 걸어가는 진정한 사랑의 속이야기."
    },
    {
      genreId: "romance",
      titleJa: "ボトムス ～最底辺の私たち～",
      titleEn: "Bottoms",
      titleKo: "바텀스",
      castJa: "レイチェル・セノット, アヨ・エデビリ",
      castEn: "Rachel Sennott, Ayo Edebiri",
      castKo: "레이첼 세노트, 아요 에데비리",
      dirJa: "エマ・セリグマン",
      dirEn: "Emma Seligman",
      dirKo: "엠마 셀리그먼",
      infoJa: "2023年 / 91分 / アメリカ",
      infoEn: "2023 / 91 min / USA",
      infoKo: "2023년 / 91분 / 미국",
      quoteJa: "「チアリーダーと付き合うために護身術クラブを作るの」",
      quoteEn: "“We are starting a self-defense club to get closer to cheerleaders.”",
      quoteKo: "“치어리더들이랑 사귀려고 여자 호신술 동아리를 만드는 거야.”",
      descJa: "スクールカースト最底辺のクィアな女子高生コンビが、憧れのチアリーダーたちと仲良くなるために「女子護身術クラブ」をでっち上げる、破天荒でエネルギッシュな青春ブラックコメディ。",
      descEn: "Two awkward, unpopular queer high school girls found a fight club under the guise of self-defense as a hilarious, chaotic strategy to win over the school's top cheerleaders.",
      descKo: "학교 계급 최하위의 퀴어 여고생 콤비가 동경하던 치어리더들과 친해지기 위해 '여성 호신술 동아리'를 엉터리로 만들어내는, 엉뚱하고 에너지가 넘치는 청춘 블랙 코미디 영화."
    },
    {
      genreId: "romance",
      titleJa: "トランジットガールズ",
      titleEn: "Transit Girls",
      titleKo: "트랜짓 걸즈",
      castJa: "伊藤沙莉, 佐久間由衣",
      castEn: "Sairi Ito, Yui Sakuma",
      castKo: "이토 사이리, 사쿠마 유이",
      dirJa: "前田真人",
      dirEn: "Masato Maeda",
      dirKo: "마에다 마사토",
      infoJa: "2015年 / ドラマ全8話 / 日本",
      infoEn: "2015 / TV Series (8 episodes) / Japan",
      infoKo: "2015년 / 드라마 총 8화 / 일본",
      quoteJa: "「お姉ちゃんのこと、好きになっちゃいけない？」",
      quoteEn: "“Is it wrong for me to fall in love with you, sis?”",
      quoteKo: "“언니를 좋아하면 안 되는 거야?”",
      descJa: "親同士の再婚によって急に義理の姉妹となったスタイリッシュな姉とボーイッシュな妹。ひとつ屋根の下で惹かれ合い、世間の目や複雑な感情に揺れ動く甘酸っぱい初恋ストーリー。",
      descEn: "Two young women suddenly become stepsisters due to their parents' remarriage. Living under one roof, subtle affection turns into a poignant, heart-pounding first love.",
      descKo: "부모님의 재혼으로 갑자기 의붓자매가 된 세련된 언니와 보이시한 여동생. 한집에 살며 서로에게 이끌리고, 세상의 시선과 복잡한 감정 속에서 흔들리는 새콤달콤한 첫사랑 이야기."
    },
    {
      genreId: "romance",
      titleJa: "ハーフ・オブ・イット: はじまりの物語",
      titleEn: "The Half of It",
      titleKo: "반쪽의 이야기",
      castJa: "リア・ルイス, ダニエル・ディマー, アレクシス・レミル",
      castEn: "Leah Lewis, Daniel Diemer, Alexxis Lemire",
      castKo: "리아 루이스, 다니엘 디머, 알렉시스 레밀",
      dirJa: "アリス・ウー",
      dirEn: "Alice Wu",
      dirKo: "앨리스 우",
      infoJa: "2020年 / 104分 / アメリカ",
      infoEn: "2020 / 104 min / USA",
      infoKo: "2020년 / 104분 / 미국",
      quoteJa: "「愛とは完璧なものを見つけることじゃない」",
      quoteEn: "“Love isn't finding your perfect complement.”",
      quoteKo: "“사랑이란 완벽한 짝을 찾는 게 아니야.”",
      descJa: "内気な中国系移民の優等生少女が、不器用なフットボール男子から頼まれてラブレターの代筆を引き受けるが、その手紙の相手は自身もひそかに恋焦がれる学校マドンナだった青春ラブストーリー。",
      descEn: "A quiet Asian-American honors student helps a well-meaning jock write love letters to a beautiful classmate whom she secretly harbors romantic feelings for herself.",
      descKo: "내성적인 중국계 이민자 우등생 소녀가 서툰 미식축구 소년의 부탁으로 러브레터 대필을 맡게 되지만, 그 편지의 상대는 자신도 몰래 연모하던 학교의 퀸카였다는 사실을 알게 되며 벌어지는 청춘 로맨스."
    },
    {
      genreId: "romance",
      titleJa: "百合だのかんだの",
      titleEn: "Yuri or Something",
      titleKo: "백합이니 뭐니",
      castJa: "馬場ふみか, 小島藤子",
      castEn: "Fumika Baba, Fujiko Kojima",
      castKo: "바바 후미카, 코지마 후지코",
      dirJa: "加藤裕将",
      dirEn: "Yusuke Kato",
      dirKo: "카토 히로유키",
      infoJa: "2019年 / ドラマ全8話 / 日本",
      infoEn: "2019 / TV Series (8 episodes) / Japan",
      infoKo: "2019년 / 드라마 총 8화 / 일본",
      quoteJa: "「友情とか恋愛とか、名前なんてどうでもいい」",
      quoteEn: "“Friendship, love... labels don't matter between us.”",
      quoteKo: "“우정이니 연애니, 이름 같은 건 아무래도 상관없어.”",
      descJa: "ストーカー被害に悩む女子大生が、再会した小学生時代の親友と同居を開始。単なる友情や従来の恋愛の範疇に収まらない、現代女性たちの繊細で特別なグラデーションの関係性を描く。",
      descEn: "A college girl experiencing stalking encounters her childhood best female friend and moves in together, developing an indefinable yet deeply vital emotional connection.",
      descKo: "스토커 피해로 고민하는 여대생이 우연히 재회한 초등학교 시절의 절친과 동거를 시작한다. 단순한 우정이나 기존의 연애 범주에 얽매이지 않는, 현대 여성들의 섬세하고 특별한 관계의 스펙트럼을 그린 드라마."
    },
    {
      genreId: "romance",
      titleJa: "ブックスマート 卒業前夜のパーティーデビュー",
      titleEn: "Booksmart",
      titleKo: "북스마트",
      castJa: "ビーニー・フェルドスタイン, ケイトリン・デヴァー",
      castEn: "Beanie Feldstein, Kaitlyn Dever",
      castKo: "비니 펠드스타인, 케이틀린 디버",
      dirJa: "オリヴィア・ワイルド",
      dirEn: "Olivia Wilde",
      dirKo: "올리비아 와일드",
      infoJa: "2019年 / 102分 / アメリカ",
      infoEn: "2019 / 102 min / USA",
      infoKo: "2019년 / 102분 / 미국",
      quoteJa: "「私たちは勉強だけじゃなく、遊びだって全力でやるべきだった」",
      quoteEn: "“We should have worked less and partied way more.”",
      quoteKo: "“우린 공부뿐만 아니라 노는 것도 온 힘을 다해 했어야 했어.”",
      descJa: "高校生活のすべてを勉強に捧げてきた優等生コンビ（うち一人はオープンなレズビアン）。卒業前夜に「遊ぶことも諦めない」と誓い、爆笑の爆走パーティー巡りに繰り出す最高のバディ＆ガールズ映画。",
      descEn: "On the night before high school graduation, two academic overachievers—one of whom is openly gay—realize they missed out on fun and cram four years of partying into one wild night.",
      descKo: "고등학교 생활 전부를 공부에 바친 우등생 콤비(그중 한 명은 커밍아웃한 퀴어). 졸업 전날 밤 '노는 것도 포기하지 않겠다'고 맹세하고 폭소 만발의 파티 순회에 나서는 최고의 버디 & 청춘 코미디 영화."
    },
    {
      genreId: "romance",
      titleJa: "片想いスパイラル",
      titleEn: "Unrequited Love Spiral",
      titleKo: "짝사랑 스파이럴",
      castJa: "知英, 佐津川愛美, TAKUYA",
      castEn: "Ji-young, Aimi Satsukawa, TAKUYA",
      castKo: "강지영, 사츠카와 아이미, 타쿠야",
      dirJa: "原桂之介",
      dirEn: "Keinosuke Hara",
      dirKo: "하라 케이노스케",
      infoJa: "2016年 / 82分 / 日本",
      infoEn: "2016 / 82 min / Japan",
      infoKo: "2016년 / 82분 / 일본",
      quoteJa: "「心は男でも、体は女。そんな僕が君を好きになった」",
      quoteEn: "“Though I have a woman's body, my heart fell deeply in love with you.”",
      quoteKo: "“마음은 남자지만, 몸은 여자. 그런 내가 너를 좋아하게 되었어.”",
      descJa: "体は女性でありながら心は男性である性同一性障害（FTM）を抱える主人公。シェアハウスの同居人である親友女性への報われない秘めた想いと複雑な三角関係を描く純愛ドラマ。",
      descEn: "A transgender man with a female body struggles with his secret, intense romantic feelings for his female roommate, navigating a complex triangular affection.",
      descKo: "몸은 여성이지만 마음은 남자인 트랜스젠더(FTM) 주인공. 셰어하우스 동거인인 절친한 여성에게 품은 이루어질 수 없는 숨겨진 마음과 복잡한 삼각관계를 그린 순애 드라마."
    },
    {
      genreId: "romance",
      titleJa: "イマジナリーライン（パス・イン・ライフ）",
      titleEn: "Saving Face",
      titleKo: "세이빙 페이스",
      castJa: "ミシェル・クルージ, リン・チェン, ジョアン・チェン",
      castEn: "Michelle Krusiec, Lynn Chen, Joan Chen",
      castKo: "미셸 크루식, 린 첸, 조안 첸",
      dirJa: "アリス・ウー",
      dirEn: "Alice Wu",
      dirKo: "앨리스 우",
      infoJa: "2004年 / 91分 / アメリカ",
      infoEn: "2004 / 91 min / USA",
      infoKo: "2004년 / 91분 / 미국",
      quoteJa: "「本当の自分を隠して生きるのに疲れたの」",
      quoteEn: "“I'm tired of hiding who I really am.”",
      quoteKo: "“진짜 나를 숨기고 살아가는 데 이제 지쳤어.”",
      descJa: "ニューヨークに住む中国系アメリカ人の外科医女性が、ダンサーの女性と恋に落ちる。世間体を気にする保守的な親類と未婚で妊娠した実母とのコミカルで情に厚いファミリーロマンス。",
      descEn: "A young Chinese-American surgeon falling for a beautiful dancer must navigate her conservative family's expectations while her unmarried mother suddenly becomes pregnant.",
      descKo: "뉴욕에 사는 중국계 미국인 외과의사 여성이 댄서인 여성과 사랑에 빠진다. 체면을 중요시하는 보수적인 친척들과 미혼으로 임신한 친어머니 사이에서 벌어지는 유쾌하고 정감이 넘치는 가족 로맨스."
    },
    // ==========================================
    // 🍂 大人の葛藤 (Drama & Bitter)
    // ==========================================
    {
      genreId: "bitter",
      titleJa: "TAR/ター",
      titleEn: "TÁR",
      titleKo: "타르",
      castJa: "ケイト・ブランシェット, ニーナ・ホス, ノエミ・メルラン",
      castEn: "Cate Blanchett, Nina Hoss, Noémie Merlant",
      castKo: "케이트 블란쳇, 니나 호스, 노에미 멜랑",
      dirJa: "トッド・フィールド",
      dirEn: "Todd Field",
      dirKo: "토드 필드",
      infoJa: "2022年 / 158分 / アメリカ",
      infoEn: "2022 / 158 min / USA",
      infoKo: "2022년 / 158분 / 미국",
      quoteJa: "「時間は私がコントロールする」",
      quoteEn: "“Time is the essential piece of interpretation.”",
      quoteKo: "“시간은 내가 통제하는 거야.”",
      descJa: "世界最高峰のオーケストラで指揮者を務める天才絶対君主ター。同性のパートナーであるコンサートマスターとの冷え切った関係、権力濫用疑惑から狂気と落日へ向かう圧巻の心理サスペンス。",
      descEn: "A world-renowned lesbian conductor at the peak of her career sees her personal life and artistic empire collapse as secrets and allegations of abuse of power emerge.",
      descKo: "세계 최고 수준의 오케스트라에서 지휘를 맡은 천재 절대군주 타르. 동성 파트너인 악장과의 식어버린 관계, 권력 남용 의혹 속에서 광기와 몰락을 향해 치달아가는 압도적인 심리 서스펜스."
    },
    {
      genreId: "bitter",
      titleJa: "Daughters",
      titleEn: "Daughters",
      titleKo: "도터스",
      castJa: "三吉彩花, 阿部純子",
      castEn: "Ayaka Miyoshi, Junko Abe",
      castKo: "미요시 아야카, 아베 준코",
      dirJa: "津田肇",
      dirEn: "Hajime Tsuda",
      dirKo: "츠다 하지메",
      infoJa: "2020年 / 104分 / 日本",
      infoEn: "2020 / 104 min / Japan",
      infoKo: "2020년 / 104분 / 일본",
      quoteJa: "「友達の妊娠、それは私たちの関係も変えていく」",
      quoteEn: "“Her unexpected pregnancy gradually changes everything between us.”",
      quoteKo: "“친구의 임신, 그것은 우리의 관계까지도 변화시켜.”",
      descJa: "東京・中目黒でルームシェア生活を送る2人の働く女性。一人の予期せぬ妊娠をきっかけに、家族でも恋人でもない二人の絶妙な関係性がグラデーションのように変化していくスタイリッシュなビタードラマ。",
      descEn: "Two female roommates in Tokyo navigate the subtle shift in their deep friendship and personal independence when one discovers she is pregnant and decides to keep the baby.",
      descKo: "도쿄 나카메구로에서 룸메이트로 함께 사는 두 명의 일하는 여성. 한 사람의 예상치 못한 임신을 계기로 가족도 연인도 아닌 두 사람의 미묘한 관계가 그라데이션처럼 변화해 가는 스타일리시한 비터 드라마."
    },
    {
      genreId: "bitter",
      titleJa: "カケラ",
      titleEn: "A Piece of Our Life",
      titleKo: "조각",
      castJa: "満島ひかり, 中村映里子",
      castEn: "Hikari Mitsushima, Eriko Nakamura",
      castKo: "미츠시마 히카리, 나카무라 에리코",
      dirJa: "安藤桃子",
      dirEn: "Momoko Ando",
      dirKo: "안도 모모코",
      infoJa: "2010年 / 107分 / 日本",
      infoEn: "2010 / 107 min / Japan",
      infoKo: "2010년 / 107분 / 일본",
      quoteJa: "「女の子同士の恋愛って、そんなに特別なこと？」",
      quoteEn: "“Is love between two women really something so strange?”",
      quoteKo: "“여자들끼리의 연애라는 게 그렇게 특별한 일이야?”",
      descJa: "自分勝手な彼氏との関係に虚しさを抱く女子大生が、意思の強いメディカル・アーティストの女性と出会い恋に落落つ。歪んだ独占欲や依存心が交錯するリアルで切ない女性同士の愛憎劇。",
      descEn: "Unfulfilled in her relationship with her boyfriend, a college student falls for a confident female prosthetic artist, embarking on a turbulent journey of desire, possessiveness, and passion.",
      descKo: "제멋대로인 남자친구와의 관계에서 허무함을 느끼는 여대생이 주체적인 의지를 가진 메디컬 아티스트 여성을 만나 사랑에 빠진다. 뒤틀린 독점욕과 의존심이 교차하는 리얼하고 애절한 여성 간의 애증극."
    },
    {
      genreId: "bitter",
      titleJa: "パッセージ",
      titleEn: "Passages",
      titleKo: "패시지스",
      castJa: "フランツ・ロゴフスキ, アデル・エグザルホプロス, ベン・ウィショー",
      castEn: "Franz Rogowski, Adèle Exarchopoulos, Ben Whishaw",
      castKo: "프란츠 로고프스키, 아델 에그자르코풀로스, 벤 위쇼",
      dirJa: "アイラ・サックス",
      dirEn: "Ira Sachs",
      dirKo: "아이라 삭스",
      infoJa: "2023年 / 91分 / フランス・ドイツ",
      infoEn: "2023 / 91 min / France, Germany",
      infoKo: "2023년 / 91분 / 프랑스·독일",
      quoteJa: "「誰かを愛することは、こんなにも身勝手で切ない」",
      quoteEn: "“Loving someone can be so destructive and utterly selfish.”",
      quoteKo: "“누군가를 사랑한다는 것은 이토록 이기적이고 애달프다.”",
      descJa: "パリを舞台に、同性婚関係にある映画監督の男が若き女性と一夜を共にしたことで巻き起こる愛憎。男女の境界を超えて人間のエゴと愛の脆さを剥き出しにしたビターな人間ドラマ。",
      descEn: "In Paris, a narcissistic male filmmaker's long-term marriage to his husband unravels after he begins an impulsive affair with a young schoolteacher, exploring painful relationship dynamics.",
      descKo: "파리를 배경으로 동성 결혼 관계에 있는 영화 감독 남성이 젊은 여성과 하룻밤을 보내며 시작되는 애증. 남녀의 경계를 넘어 인간의 이기심과 사랑의 취약함을 적나라하게 드러낸 씁쓸한 인간 드라마."
    },
    {
      genreId: "bitter",
      titleJa: "Blue",
      titleEn: "Blue",
      titleKo: "블루 (Blue)",
      castJa: "市川実日子, 小西真奈美",
      castEn: "Mikako Ichikawa, Manami Konishi",
      castKo: "이치카와 미카코, 코니시 마나미",
      dirJa: "安藤尋",
      dirEn: "Hiroshi Ando",
      dirKo: "안도 히로시",
      infoJa: "2002年 / 116分 / 日本",
      infoEn: "2002 / 116 min / Japan",
      infoKo: "2002년 / 116분 / 일본",
      quoteJa: "「息が苦しくなるほど、あなたに触れていたい」",
      quoteEn: "“I want to feel you close, so deeply that it leaves me breathless.”",
      quoteKo: "“숨이 막힐 정도로 당신에게 닿아 있고 싶어.”",
      descJa: "日本海の海辺の町。どこか孤立した空気を纏う2人の女子高生が密かに惹かれ合い、寄り添うように身体を重ねる。思春期特有の痛切な孤独と静寂を描いた至高の百合作品。",
      descEn: "In a quiet coastal town in Japan, two isolated high school girls forge a secret physical and emotional bond, offering each other escape from unbearable loneliness.",
      descKo: "동해(일본해) 연안의 바닷가 마을. 어딘가 고립된 분위기를 띤 두 여고생이 비밀리에 서로에게 끌리며 가만히 몸을 겹친다. 사춘기 특유의 절절한 고독과 정적을 그린 최고의 백합 작품."
    },
    {
      genreId: "bitter",
      titleJa: "ふたりのマイルーム",
      titleEn: "The Feels",
      titleKo: "더 필스 (The Feels)",
      castJa: "コンスタンス・ウー, アンジェラ・トリンバー",
      castEn: "Constance Wu, Angela Trimbur",
      castKo: "콘스탄스 우, 앤절라 트림버",
      dirJa: "ジェンジ・コーハン",
      dirEn: "Jenée LaMarque",
      dirKo: "제니 라마크",
      infoJa: "2017年 / 88分 / アメリカ",
      infoEn: "2017 / 88 min / USA",
      infoKo: "2017년 / 88분 / 미국",
      quoteJa: "「完璧に見える関係にも、秘密はある」",
      quoteEn: "“Even the most perfect relationship has its hidden truths.”",
      quoteKo: "“완벽해 보이는 관계에도 비밀은 있다.”",
      descJa: "結婚を目前に控えたレズビアンカップルが、友人たちを集めて開催した独身サヨナラパーティー。酒席でのふとした告白から互いの本音と葛藤が浮き彫りになるビターな群像コメディドラマ。",
      descEn: "A group of friends gathers for a bachelorette weekend to celebrate a lesbian couple's upcoming wedding, but an unexpected confession leads to deep emotional friction and self-discovery.",
      descKo: "결혼을 앞둔 레즈비언 커플이 친구들을 모아 개최한 처녀 파티. 술자리에서의 우연한 고백으로 서로의 본심과 갈등이 드러나는 씁쓸한 군상 코미디 드라마."
    },
    {
      genreId: "bitter",
      titleJa: "わたしはロランス",
      titleEn: "Laurence Anyways",
      titleKo: "로렌스 애니웨이",
      castJa: "メルヴィル・プポー, スザンヌ・クレマン",
      castEn: "Melvil Poupaud, Suzanne Clément",
      castKo: "멜빌 푸포, 쉬잔 클레망",
      dirJa: "グザヴィエ・ドラン",
      dirEn: "Xavier Dolan",
      dirKo: "자비에 돌란",
      infoJa: "2012年 / 168分 / カナダ・フランス",
      infoEn: "2012 / 168 min / Canada, France",
      infoKo: "2012년 / 168분 / 캐나다·프랑스",
      quoteJa: "「君を愛している。でも、自分自身を偽ることはできない」",
      quoteEn: "“I love you, but I cannot go on living a lie.”",
      quoteKo: "“너를 사랑해. 하지만 나 자신을 속이며 살 수는 없어.”",
      descJa: "30歳の誕生日に「女性として生きたい」と打ち明けた男性国語教師と、彼を深く愛しながらも激しく葛藤する恋人フレッド。10年間にわたる2人の揺れ動く愛の葛藤と絆を描いた圧倒的色彩の人間ドラマ。",
      descEn: "When a high school teacher reveals his inner truth to live as a woman, he and his passionate girlfriend navigate a complex, decade-long journey of enduring love, identity, and heartbreak.",
      descKo: "30번째 생일에 여성으로 살고 싶다고 고백한 남성 국어 교사와, 그를 깊이 사랑하면서も 격렬하게 갈등하는 연인 프레드. 10년에 걸친 두 사람의 흔들리는 사랑의 갈등과 유대를 그린 압도적 색채의 인간 드라마."
    },
    {
      genreId: "bitter",
      titleJa: "彼女のいない部屋",
      titleEn: "Hold Me Tight",
      titleKo: "홀드 미 타이트",
      castJa: "ヴィッキー・クリープス, マチュー・アマルリック",
      castEn: "Vicky Krieps, Mathieu Amalric",
      castKo: "비키 크리프스, 마티외 아말리크",
      dirJa: "マチュー・アマルリック",
      dirEn: "Mathieu Amalric",
      dirKo: "마티외 아말리크",
      infoJa: "2021年 / 97分 / フランス",
      infoEn: "2021 / 97 min / France",
      infoKo: "2021년 / 97분 / 프랑스",
      quoteJa: "「立ち止まれば、哀しみに押しつぶされてしまうから」",
      quoteEn: "“If I stop moving, the sorrow will overwhelm me completely.”",
      quoteKo: "“멈춰 서면 슬픔에 짓눌려 버릴 테니까.”",
      descJa: "ある朝、夫と子どもたちを残して家を出た一人の女性。彼女のあてのない孤独な旅路と、残された家族の日常が交錯する中で明かされる、抱えきれない喪失感と愛のビターな記憶。",
      descEn: "A woman appears to abandon her family one morning, embarking on a solitary journey. As past memories and current realities merge, a deeply moving story of grief and emotional resilience unfolds.",
      descKo: "어느 날 아침, 남편과 아이들을 남겨두고 집을 떠난 한 여성. 그녀의 목적 없는 고독한 여정과 남겨진 가족의 일상이 교차하는 가운데 밝혀지는, 감당할 수 없는 상실감과 사랑의 씁쓸한 기억."
    },
    {
      genreId: "bitter",
      titleJa: "マイ・ファースト・サマー",
      titleEn: "My First Summer",
      titleKo: "마이 퍼스트 서머",
      castJa: "マークエラ・カヴェナ, メイヴ・ディモディ",
      castEn: "Markella Kavenagh, Maiah Stewardson",
      castKo: "마르켈라 카베나, 마이아 스튜어드슨",
      dirJa: "ケイティ・ファウンド",
      dirEn: "Katie Found",
      dirKo: "케이티 파운드",
      infoJa: "2020年 / 78分 / オーストラリア",
      infoEn: "2020 / 78 min / Australia",
      infoKo: "2020년 / 78분 / 호주",
      quoteJa: "「世界が私達を見つけるまで、ここでふたりだけでいよう」",
      quoteEn: "“Until the world finds us, let's stay right here together.”",
      quoteKo: "“세상이 우리를 찾을 때까지, 여기서 둘이서만 있자.”",
      descJa: "世間から隔離された隠れ家で母を亡くした少女が、町からやってきた天真爛漫な少女と出会う。美しく密やかな湖畔で傷を舐め合い育まれる悲しくも眩しい秘密のロマンス。",
      descEn: "Raised in isolation from the outside world, a grieving 16-year-old girl meets an adventurous teenager, creating a fragile sanctuary of healing love and discovery.",
      descKo: "세상과 격리된 은신처에서 엄마를 잃은 소녀가 마을에서 온 천진난만한 소녀를 만난다. 아름답고 비밀스러운 호숫가에서 서로의 상처를 보듬으며 싹트는 슬프고도 눈부신 비밀 로맨스."
    },
    {
      genreId: "bitter",
      titleJa: "クロゼットの失楽園",
      titleEn: "Lost and Delirious",
      titleKo: "상실의 유혹",
      castJa: "パイパー・ペラーボ, ミーシャ・バートン",
      castEn: "Piper Perabo, Mischa Barton",
      castKo: "파이퍼 페라보, 미샤 바튼",
      dirJa: "レア・プール",
      dirEn: "Léa Pool",
      dirKo: "레아 풀",
      infoJa: "2001年 / 103分 / カナダ",
      infoEn: "2001 / 103 min / Canada",
      infoKo: "2001년 / 103분 / 캐나다",
      quoteJa: "「偽りの自分を演じるくらいなら、狂気に沈む方がマシだ」",
      quoteEn: "“I'd rather be madly in love than pretend to be normal.”",
      quoteKo: "“거짓된 자신을 연기할 바에야, 광기에 빠지는 편이 낫다.”",
      descJa: "全寮制の女子校。ルームメイトとして深く愛し合っていた2人の少女。だが世間の目を恐れた一方が男性との交際を選んだことで、もう一人の情熱は純粋ゆえの狂気へと加速していく悲劇。",
      descEn: "At a prestigious boarding school, two roommates share a passionate secret romance. When fear of social rejection forces one back into conformity, it drives the other to heartbreaking extremes.",
      descKo: "기숙사제 여학교. 룸메이트로서 깊이 사랑하던 두 소녀. 하지만 세상의 시선을 두려워한 한쪽이 남성과의 교제를 선택하면서, 다른 한쪽의 열정은 순수함으로 인한 광기로 가속해 가는 비극."
    },
    // ==========================================
    // 🌱 あの頃の青春 (Youth)
    // ==========================================
    {
      genreId: "youth",
      titleJa: "さよならくちびる",
      titleEn: "Farewell Song",
      titleKo: "굿바이 입술",
      castJa: "小松菜奈, 門脇麦, 成田凌",
      castEn: "Nana Komatsu, Mugi Kadowaki, Ryo Narita",
      castKo: "고마츠 나나, 카도와키 무기, 나리타 료",
      dirJa: "塩田明彦",
      dirEn: "Akihiko Shiota",
      dirKo: "시오타 아키히코",
      infoJa: "2019年 / 116分 / 日本",
      infoEn: "2019 / 116 min / Japan",
      infoKo: "2019년 / 116분 / 일본",
      quoteJa: "「この歌が終わったら、私たちは解散する」",
      quoteEn: "“Once this song is finished, our road together ends.”",
      quoteKo: "“이 노래가 끝나면, 우리는 해산한다.”",
      descJa: "解散を決めた人気女性アコースティックデュオ「ハルレオ」。ローディの男性を交えた解散ツアーの途上、互いへの切ない恋心と言葉にできない執着が音楽に乗せて響き合う感動の音楽青春映画。",
      descEn: "During a farewell concert tour across Japan, two female indie folk duo partners confront their complex, unspoken romantic feelings and emotional dependance through music.",
      descKo: "해산을 결정한 인기 여성 어쿠스틱 듀오 '하루레오'. 로디 남성을 동반한 해산 투어 중에, 서로를 향한 애틋한 연정과 말로 다 할 수 없는 집착이 음악에 실려 울려 퍼지는 감동적인 음악 청춘 영화."
    },
    {
      genreId: "youth",
      titleJa: "志乃ちゃんは自分の名前が言えない",
      titleEn: "Shino Cannot Say Her Own Name",
      titleKo: "시노는 자신의 이름을 말하지 못한다",
      castJa: "南沙良, 蒔田彩珠",
      castEn: "Sara Minami, Aju Makita",
      castKo: "미나미 사라, 마키타 아쥬",
      dirJa: "湯浅弘章",
      dirEn: "Hiroaki Yuasa",
      dirKo: "유아사 히로아키",
      infoJa: "2018年 / 110分 / 日本",
      infoEn: "2018 / 110 min / Japan",
      infoKo: "2018년 / 110분 / 일본",
      quoteJa: "「上手にしゃべれなくても、私の歌は届くのかな」",
      quoteEn: "“Even if I stumble over words, can you still hear my true voice?”",
      quoteKo: "“말을 잘하지 못해도 내 노래는 전해질까.”",
      descJa: "吃音のため上手く話せない少女と、音楽を愛しながら音痴な少女。孤独を抱えた2人が校舎の屋上で音楽を通じて心を通わせ、世界の不器用さと対峙する感動的な青春模様。",
      descEn: "A high school girl who stutters forms a unique musical bond with an outcast guitarist classmate, building a powerful friendship that helps them navigate youth.",
      descKo: "말더듬증 때문에 말을 잘하지 못하는 소녀와 음악을 사랑하지만 음치인 소녀. 고독을 안은 두 사람이 학교 옥상에서 음악을 통해 마음을 나누며 세상의 서투름과 맞서는 감동적인 청춘 드라마."
    },
    {
      genreId: "youth",
      titleJa: "思いのほかの恋",
      titleEn: "The Incredibly True Adventure of Two Girls in Love",
      titleKo: "두 소녀의 놀라운 모험",
      castJa: "ローレル・ホロマン, ニコル・アリ・パーカー",
      castEn: "Laurel Holloman, Nicole Ari Parker",
      castKo: "로렐 홀러먼, 니콜 아리 파커",
      dirJa: "マリア・マグエンティ",
      dirEn: "Maria Maggenti",
      dirKo: "마리아 마젠티",
      infoJa: "1995年 / 94分 / アメリカ",
      infoEn: "1995 / 94 min / USA",
      infoKo: "1995년 / 94분 / 미국",
      quoteJa: "「あなたと一緒にいると、世界がまったく違って見える」",
      quoteEn: "“Being with you makes the whole world feel entirely brand new.”",
      quoteKo: "“너와 함께 있으면 세상이 완전히 달라 보여.”",
      descJa: "ボーイッシュでアウトローな白人少女と、裕福でおしゃれなアフリカ系優等生少女。対照的な2人の女子高生が出会い、互いの違いを超えて惹かれ合っていく甘酸っぱく瑞々しい90年代青春映画の名作。",
      descEn: "A tomboyish, working-class high school girl and a popular, wealthy classmate form an unexpected, sweet romantic bond that challenges their different backgrounds.",
      descKo: "보이시하고 아웃로인 백인 소녀와 풍족하고 세련된 아프리카계 모범생 소녀. 대조적인 두 여고생이 만나 서로의 차이를 넘어 끌려가는 새콤달콤하고 신선한 90년대 청춘 영화의 명작."
    },
    {
      genreId: "youth",
      titleJa: "ひらいて",
      titleEn: "Unlock Your Heart",
      titleKo: "열어봐",
      castJa: "山田杏奈, 芋生悠, 作間龍斗",
      castEn: "Anna Yamada, Haruka Imou, Ryuto Sakuma",
      castKo: "야마다 안나, 이모우 하루카, 사쿠마 류토",
      dirJa: "首藤凜",
      dirEn: "Rin Shuto",
      dirKo: "슈토 린",
      infoJa: "2021年 / 121分 / 日本",
      infoEn: "2021 / 121 min / Japan",
      infoKo: "2021년 / 121분 / 일본",
      quoteJa: "「あなたの秘密を、私に見せて」",
      quoteEn: "“Open up and show me all of your hidden secrets.”",
      quoteKo: "“당신의 비밀을 나에게 보여줘.”",
      descJa: "校内の人気者である女子高生が、密かに思いを寄せる男子生徒に秘密の恋人がいることを知る。その相手である地味な女子生徒へと屈折した関心を向け急接近していく歪で美しい欲望の物語。",
      descEn: "A popular high school girl becomes dangerously obsessed with an introverted female classmate who is secretly dating the boy she likes, pushing boundaries of intimacy.",
      descKo: "교내 인기인인 여고생이 짝사랑하는 남학생에게 비밀 연인이 있다는 사실을 알게 된다. 그 상대인 수수한 여학생에게 굴절된 관심을 쏟으며 급접근해 가는 비틀리고도 아름다운 욕망의 이야기."
    },
    {
      genreId: "youth",
      titleJa: "ファースト・ガールズ",
      titleEn: "First Girl I Loved",
      titleKo: "퍼스트 걸 아이 러브",
      castJa: "ディラン・ゲルラ, ブリアンヌ・ヒューイ",
      castEn: "Dylan Gelula, Brianna Hildebrand",
      castKo: "딜런 겔룰라, 브리아나 힐데브란드",
      dirJa: "ケラム・サンガ",
      dirEn: "Kerem Sanga",
      dirKo: "케렘 산가",
      infoJa: "2016年 / 91分 / アメリカ",
      infoEn: "2016 / 91 min / USA",
      infoKo: "2016년 / 91분 / 미국",
      quoteJa: "「初めて誰かを本気で好きになった。それが彼女だったの」",
      quoteEn: "“For the first time, I fell in love—and it happened to be with her.”",
      quoteKo: "“처음으로 누군가를 진심으로 좋아하게 되었어. 그게 그녀였던 거야.”",
      descJa: "校内新聞の取材をきっかけに、ソフトボール部のスター選手に恋をした17歳の写真部少女。SNSや周囲の視線、初恋の戸惑いに苛まれながらも自分らしさを模索する等身大の甘酸っぱい青春ドラマ。",
      descEn: "A 17-year-old high school photographer falls in love with the star of the girls' softball team, facing complex social dynamics and self-discovery during her turbulent first romance.",
      descKo: "교내 신문 취재를 계기로 소프트볼부 스타 선수에게 반한 17세 사진부 소녀. SNS와 주변의 시선, 첫사랑의 혼란에 시달리면서도 자신다움을 모색하는 등신대의 새콤달콤한 청춘 드라마."
    },
    {
      genreId: "youth",
      titleJa: "少女",
      titleEn: "Night's Tightrope",
      titleKo: "소녀 (Night's Tightrope)",
      castJa: "本田翼, 山本美月",
      castEn: "Tsubasa Honda, Mizuki Yamamoto",
      castKo: "혼다 츠바사, 야마모토 미즈키",
      dirJa: "三島有紀子",
      dirEn: "Yukiko Mishima",
      dirKo: "미시마 유키코",
      infoJa: "2016年 / 119分 / 日本",
      infoEn: "2016 / 119 min / Japan",
      infoKo: "2016년 / 119분 / 일본",
      quoteJa: "「人が死ぬ瞬間を見たら、生きている意味がわかるのかな」",
      quoteEn: "“If I see someone die, will I finally understand what living means?”",
      quoteKo: "“사람이 죽는 순간을 보면 살아있는 의미를 알 수 있을까.”",
      descJa: "「人が死ぬ瞬間を見てみたい」という危険な欲望を密かに心に秘めた2人の女子高生。心に傷を負った親友同士が死生観の深淵に踏み込んでいくミステリアスで美しいダーク青春劇。",
      descEn: "Two traumatized high school best friends spend their summer vacation secretly trying to witness a person's death, exploring dark psychological depths and bound affection.",
      descKo: "'사람이 죽는 순간을 보고 싶다'는 위험한 욕망을 가슴속에 비밀리 품은 두 여고생. 마음의 상처를 안은 절친한 친구끼리 사생관의 심연으로 들어가는 미스터리하고 아름다운 다크 청춘극."
    },
    {
      genreId: "youth",
      titleJa: "ショー・ミー・ラブ（ガールフレンド）",
      titleEn: "Show Me Love",
      titleKo: "쇼 미 러브 (아모르스 아말)",
      castJa: "レベッカ・リリエベリ, アレクサンドラ・ダールストレム",
      castEn: "Rebecka Liljeberg, Alexandra Dahlström",
      castKo: "레베카 리예베리, 알렉산드라 달스트룀",
      dirJa: "ルーカス・ムーディソン",
      dirEn: "Lukas Moodysson",
      dirKo: "루카스 무디손",
      infoJa: "1998年 / 89分 / スウェーデン",
      infoEn: "1998 / 89 min / Sweden",
      infoKo: "1998년 / 89분 / 스웨덴",
      quoteJa: "「この退屈な町で、あなただけが私の希望」",
      quoteEn: "“In this dead-end town, you are my only ray of hope.”",
      quoteKo: "“이 지루한 마을에서 당신만이 나의 희망이야.”",
      descJa: "スウェーデンの退屈で閉鎖的な田舎町。地味で浮いていた少女と学校一の人気者の少女。誤解や周囲の好奇の目を乗り越え純粋に惹かれ合う姿を描いた甘酸っぱい青春レズビアン映画の名作。",
      descEn: "In a boring Swedish town, an outcast, lonely girl who harbors a secret crush on the school's most popular girl finds her world transformed when her love is unexpectedly returned.",
      descKo: "스웨덴의 지루하고 폐쇄적인 시골 마을. 수수하고 겉돌던 소녀와 학교 최고의 인기인 소녀. 오해와 주변의 호기심 어린 시선을 극복하고 순수하게 서로에게 끌리는 모습을 그린 새콤달콤한 청춘 레즈비언 영화의 명작."
    },
    {
      genreId: "youth",
      titleJa: "金魚つくし",
      titleEn: "Water Lilies",
      titleKo: "워터 릴리스",
      castJa: "アデル・エネル, ポーリーヌ・アキュアール",
      castEn: "Adèle Haenel, Pauline Acquart",
      castKo: "아델 에넬, 폴린 아퀴아르",
      dirJa: "セリーヌ・シアマ",
      dirEn: "Céline Sciamma",
      dirKo: "셀린 시아마",
      infoJa: "2007年 / 85分 / フランス",
      infoEn: "2007 / 85 min / France",
      infoKo: "2007년 / 85분 / 프랑스",
      quoteJa: "「息を止めて、あなただけを見つめていた」",
      quoteEn: "“I held my breath, unable to look away from you.”",
      quoteKo: "“숨을 참고, 당신만을 바라보고 있었어.”",
      descJa: "郊外の公営プールを舞台に、シンクロナイズドスイミングの美しい主将に惹かれていく15歳の少女。セリーヌ・シアマ監督が長編デビュー作で描いた、欲望と秘密に満ちた眩しく鋭い思春期の目覚め。",
      descEn: "In a Parisian suburb, a quiet 15-year-old girl becomes captivated by the captain of the synchronized swimming team, navigating the delicate and raw awakenings of teenage obsession.",
      descKo: "교외의 공영 수영장을 배경으로 아티스틱 스위밍의 아름다운 주장에 끌려가는 15세 소녀. 셀린 시아마 감독이 장편 데뷔작에서 그린, 욕망과 비밀로 가득 찬 눈부시고 날카로운 사춘기의 눈뜸."
    },
    {
      genreId: "youth",
      titleJa: "恋のゆくえ",
      titleEn: "All Over Me",
      titleKo: "올 오버 미",
      castJa: "アリソン・フォランド, タラ・サブコフ",
      castEn: "Alison Folland, Tara Subkoff",
      castKo: "앨리슨 폴랜드, 타라 서브코프",
      dirJa: "アレックス・シカヘル",
      dirEn: "Alex Sichel",
      dirKo: "알렉스 시첼",
      infoJa: "1997年 / 90分 / アメリカ",
      infoEn: "1997 / 90 min / USA",
      infoKo: "1997년 / 90분 / 미국",
      quoteJa: "「言葉にできない気持ちが、胸の中で叫んでいる」",
      quoteEn: "“Unspoken feelings are screaming deep inside my heart.”",
      quoteKo: "“말로 표현할 수 없는 마음이 가슴속에서 울부짖고 있다.”",
      descJa: "90年代ニューヨーク・ヘルズキッチン。パンクロックとライオット・ガール運動の熱気の中、親友への言えない恋心と厳しい現実に揺れ動く10代少女のリアルで鋭利な青春エモドラマ。",
      descEn: "Set against the backdrop of 1990s New York riot grrrl punk scene, a teenage girl navigates her unrequited romantic feelings for her troubled best friend.",
      descKo: "90년대 뉴욕 헬스키친. 펑크 록과 라이엇 걸 운동의 열기 속, 절친을 향한 말 못 할 연정과 가혹한 현실 사이에서 흔들리는 10대 소녀의 리얼하고 날카로운 청춘 에모 드라마."
    },
    {
      genreId: "youth",
      titleJa: "マイ・ベスト・フレンド",
      titleEn: "My Best Friend",
      titleKo: "마이 베스트 프렌드 (내 최고의 친구)",
      castJa: "モラ・アレナ・ライセン, モレナ・ゴトラ",
      castEn: "Mora Arenillas, Morena Gotter",
      castKo: "모라 아레니야스, 모레나 고테르",
      dirJa: "マルティン・ドゥスパバ",
      dirEn: "Martín Deus",
      dirKo: "마르틴 데우스",
      infoJa: "2018年 / 90分 / アルゼンチン",
      infoEn: "2018 / 90 min / Argentina",
      infoKo: "2018년 / 90분 / 아르헨티나",
      quoteJa: "「君の存在が、僕の知っていた世界をひっくり返した」",
      quoteEn: "“Your presence completely rewrote the world I thought I knew.”",
      quoteKo: "“너의 존재가 내가 알고 있던 세상을 뒤집어 놓았어.”",
      descJa: "静かな家族のもとに家庭の事情で引き取られてきた問題児の少年。同居生活の中で互いの居場所となり、複雑な感情を深めていく2人の少年の繊細で透明感あふれる青春成長物語。",
      descEn: "When a family takes in a troubled friend's teenage son, two boys form an intense, quiet personal connection that changes their understanding of love and friendship.",
      descKo: "조용한 가족에게 가정 형편상 거둬진 문제아 소년. 동거 생활 속에서 서로의 안식처가 되어주며 복잡한 감정을 깊게 다져가는 두 소년의 섬세하고 투명감 넘치는 청춘 성장 이야기."
    },
  
    // ==========================================
    // 🎬 実話ベース (True Stories)
    // ==========================================
    {
      genreId: "true-story",
      titleJa: "アンモナイトの目覚め",
      titleEn: "Ammonite",
      titleKo: "암모나이트",
      castJa: "ケイト・ウィンスレット, シアーシャ・ローナン",
      castEn: "Kate Winslet, Saoirse Ronan",
      castKo: "케이트 윈슬렛, 시얼샤 로넌",
      dirJa: "フランシス・リー",
      dirEn: "Francis Lee",
      dirKo: "프랜시스 리",
      infoJa: "2020年 / 120分 / イギリス・オーストラリア",
      infoEn: "2020 / 120 min / UK, Australia",
      infoKo: "2020년 / 120분 / 영국·오스트레일리아",
      quoteJa: "「化石の中に隠されていた、私の本当の情熱」",
      quoteEn: "“You have awakened something deep within me.”",
      quoteKo: "“화석 속에 숨겨져 있던 나의 진정한 열정.”",
      descJa: "1840年代イギリス。実在の人間的評価に恵まれなかった天才古生物学者メアリー・アニングと、療養のため彼女のもとに預けられた病弱な人妻の恋。静かな海岸で化石と共に発掘される真実の情愛。",
      descEn: "In 1840s England, acclaimed palaeontologist Mary Anning and a young convalescent married woman form an intense, life-changing romantic relationship along the rugged Dorset coastline.",
      descKo: "1840년대 영국. 실존했던, 합당한 평가를 받지 못한 천재 고생물학자 메리 애닝과 요양을 위해 그녀에게 맡겨진 병약한 유부녀의 사랑. 조용한 해안가에서 화석과 함께 발굴되는 진실한 애정."
    },
    {
      genreId: "true-story",
      titleJa: "プライドと偏見とエリートたち",
      titleEn: "Pride",
      titleKo: "런던 프라이드",
      castJa: "ビル・ナイ, イメルダ・スタウントン, ジョージ・マッケイ",
      castEn: "Bill Nighy, Imelda Staunton, George MacKay",
      castKo: "빌 나이, 이멜다 스턴턴, 조지 맥케이",
      dirJa: "マシュー・ウォーチャス",
      dirEn: "Matthew Warchus",
      dirKo: "매튜 워처스",
      infoJa: "2014年 / 120分 / イギリス",
      infoEn: "2014 / 120 min / UK",
      infoKo: "2014년 / 120분 / 영국",
      quoteJa: "「誰かが虐げられているなら、私たちは共に立ち上がる」",
      quoteEn: "“When someone is being oppressed, we stand together.”",
      quoteKo: "“누군가가 억압받고 있다면, 우리는 함께 일어선다.”",
      descJa: "1984年サッチャー政権下のイギリス。ストライキを行う炭鉱労働者たちを支援するため立ち上がったLGSM（炭鉱夫を支えるレズビアンとゲイの会）の実在の連帯と友情を描いた胸熱く感動的な実話ストーリー。",
      descEn: "Based on the inspiring true story of London-based gay and lesbian activists who raised funds to support striking Welsh miners in 1984, forging an unlikely alliance.",
      descKo: "1984년 대처 정권 하의 영국. 파업을 벌이는 광부들을 지원하기 위해 일어선 LGSM(광부를 지원하는 레즈비언과 게이 모임)의 실존 연대와 우정을 그린 벅찬 감동의 실화 스토리."
    },
    {
      genreId: "true-story",
      titleJa: "フリーヘルド 最初の愛の証明",
      titleEn: "Freeheld",
      titleKo: "프리헬드",
      castJa: "ジュリアン・ムーア, エレン・ペイジ, マイケル・シャノン",
      castEn: "Julianne Moore, Elliot Page, Michael Shannon",
      castKo: "줄리안 무어, 엘리엇 페이지, 마이클 섀넌",
      dirJa: "ピーター・ソレット",
      dirEn: "Peter Sollett",
      dirKo: "피터 솔렛",
      infoJa: "2015年 / 103分 / アメリカ",
      infoEn: "2015 / 103 min / USA",
      infoKo: "2015년 / 103분 / 미국",
      quoteJa: "「私が求めているのは特別な権利じゃない、平等な権利だ」",
      quoteEn: "“I'm not asking for anything special, just equality.”",
      quoteKo: "“내가 요구하는 것은 특별한 권리가 아니라 평등한 권리다.”",
      descJa: "末期ガンを言い渡された実在のベテラン女性警察官ローレル。長年勤め上げた遺族年金を同性パートナーに遺すべく、州の保守的な決定と戦い法的な権利を勝ち取った実話に基づく感動作。",
      descEn: "A decorated terminally ill New Jersey police officer fights a courageous legal battle against county board members to pass her earned pension to her domestic partner.",
      descKo: "말기 암을 선고받은 실존 베테랑 여성 경찰관 로렐. 오랜 기간 근무하며 쌓은 유족 연금을 동성 파트너에게 남기기 위해 주정부의 보수적인 결정과 싸워 법적 권리를 쟁취해 낸 실화 바탕의 감동작."
    },
    {
      genreId: "true-story",
      titleJa: "ワイルド・ナイツ・ウィズ・エミリー",
      titleEn: "Wild Nights with Emily",
      titleKo: "와일드 나이츠 위드 에밀리",
      castJa: "モーリー・シャノン, スーザン・ジグラー",
      castEn: "Molly Shannon, Susan Ziegler",
      castKo: "몰리섀넌, 수잔 지글러",
      dirJa: "マドレーヌ・オウネク",
      dirEn: "Madeleine Olnek",
      dirKo: "매들린 올넥",
      infoJa: "2018年 / 84分 / アメリカ",
      infoEn: "2018 / 84 min / USA",
      infoKo: "2018년 / 84분 / 미국",
      quoteJa: "「世界が私を知らなくても、あなたが私を知っていればいい」",
      quoteEn: "“I care not for the world's approval, as long as I have yours.”",
      quoteKo: "“세상이 나를 몰라도 당신이 나를 안다면 그것으로 족해.”",
      descJa: "内向的で孤独な一生を送ったと評されてきた伝説の詩人エミリ・ディキンスン。だが実際の彼女は、兄の妻スーと生涯にわたる熱烈で官能的な恋関係を結んでいたという史実に基づく伝記コメディ。",
      descEn: "This biographical comedy overturns popular history to reveal poet Emily Dickinson's passionate lifelong romantic love affair with her sister-in-law Susan.",
      descKo: "내향적이고 고독한 일생을 보냈다고 평가받아 온 전설적인 시인 에밀리 디킨슨. 하지만 실제 그녀는 오빠의 아내 수와 평생에 걸쳐 열렬하고 관능적인 연애 관계를 맺고 있었다는 역사적 사실에 기반한 전기 코미디."
    },
    {
      genreId: "true-story",
      titleJa: "ヴィータ＆ヴァージニア",
      titleEn: "Vita & Virginia",
      titleKo: "비타와 버지니아",
      castJa: "ジェマ・アータートン, エリザベス・デビッキ",
      castEn: "Gemma Arterton, Elizabeth Debicki",
      castKo: "젬마 아터튼, 엘리자베스 데비키",
      dirJa: "シャニア・バトゥー",
      dirEn: "Chanya Button",
      dirKo: "샤니아 버튼",
      infoJa: "2018年 / 110分 / イギリス・アイランド",
      infoEn: "2018 / 110 min / UK, Ireland",
      infoKo: "2018년 / 110분 / 영국·아일랜드",
      quoteJa: "「あなたは私の言葉に命を吹き込んでくれる」",
      quoteEn: "“You ignite a fire within my quiet mind.”",
      quoteKo: "“당신은 내 말에 숨결을 불어넣어 준다.”",
      descJa: "1920年代のロンドン。名作『オーランドー』のインスピレーションの源となった、天才文学者ヴァージニア・ウルフと、社交界の華であった貴族女性詩人ヴィータの美しく激しい実在の愛情劇。",
      descEn: "Chronicles the dynamic and passionate real-life love affair between iconic author Virginia Woolf and aristocratic socialite Vita Sackville-West in 1920s England.",
      descKo: "1920년대 로던. 명작 『오를란도』의 영감이 된 천재 문학가 버지니아 울프와 사교계의 꽃이었던 귀족 여성 시인 비타의 아름답고 격렬한 실존 애정극."
    },
    {
      genreId: "true-story",
      titleJa: "バトル・オブ・ザ・セクセス",
      titleEn: "Battle of the Sexes",
      titleKo: "빌리 진 킹: 세기의 대결",
      castJa: "エマ・ストーン, アンドレア・ライズボロー, スティーヴ・カレル",
      castEn: "Emma Stone, Andrea Riseborough, Steve Carell",
      castKo: "엠마 스톤, 앤드리아 라이즈보로, 스티브 카렐",
      dirJa: "ヴァレリー・ファリス, ジョナサン・デイトン",
      dirEn: "Valerie Faris, Jonathan Dayton",
      dirKo: "발레리 파리스, 조나단 데이턴",
      infoJa: "2017年 / 121分 / アメリカ",
      infoEn: "2017 / 121 min / USA",
      infoKo: "2017년 / 121분 / 미국",
      quoteJa: "「世界を変えるための戦いは、コートの上だけじゃない」",
      quoteEn: "“Change happens on the court, but also deep inside our hearts.”",
      quoteKo: "“세상을 바꾸기 위한 싸움은 코트 위뿐만이 아니다.”",
      descJa: "1973年、世界中が注目したテニスの「性別適合マッチ」。男女格差と戦う世界女王ビリー・ジーン・キングが、美容師女性との出会いを通じて自らのセクシュアリティを自覚し解放していく実話。",
      descEn: "Tennis legend Billie Jean King fights for gender equity on court while privately embarking on a transformative journey of self-discovery through a romantic relationship with a female hairdresser.",
      descKo: "1973년 전 세계가 주목한 테니스의 '성별 대결'. 남녀 격차와 싸우는 세계 여왕 빌리 진 킹이 미용사 여성과의 만남을 통해 자신의 정체성을 자각하고 해방시켜 가는 실화."
    },
    {
      genreId: "true-story",
      titleJa: "ジェントルマン・ジャック",
      titleEn: "Gentleman Jack",
      titleKo: "젠틀맨 잭",
      castJa: "サランヌ・ジョーンズ, ソフィー・ランドル",
      castEn: "Suranne Jones, Sophie Rundle",
      castKo: "수랜 존스, 소피 런들",
      dirJa: "サリー・ウェインライト",
      dirEn: "Sally Wainwright",
      dirKo: "샐리 웨인라이트",
      infoJa: "2019年 / ドラマ全8話 / イギリス・アメリカ",
      infoEn: "2019 / TV Series (8 episodes) / UK, USA",
      infoKo: "2019년 / 드라마 전8화 / 영국·미국",
      quoteJa: "「私は自分らしく生きる。誰の許可も必要ない」",
      quoteEn: "“I will live as myself. I need no one's permission.”",
      quoteKo: "“나는 나답게 살 것이다. 누구의 허락도 필요 없다.”",
      descJa: "19世紀イギリス。実在の地主アン・リスター（ジェントルマン・ジャック）が、保守的な社会の偏見を打ち破り、所有地を経営しながら同性との真実の結婚と愛を堂々と追い求めた情熱のドラマシリーズ。",
      descEn: "Based on the real coded diaries of 19th-century landowner Anne Lister, who boldly managed her estate and pursued open romantic relationships with women in Victorian England.",
      descKo: "19세기 영국. 실존 지주 앤 리스터(젠틀맨 잭)가 보수적인 사회의 편견을 깨뜨리고 자신의 영지를 경영하며 동성과의 진정한 결혼과 사랑을 당당히 추구한 열정의 드라마 시리즈."
    },
    {
      genreId: "true-story",
      titleJa: "マ・レイニーのブラックボトム",
      titleEn: "Ma Rainey's Black Bottom",
      titleKo: "마 레이니, 그녀가 블루스",
      castJa: "ヴィオラ・デイヴィス, チャドウィック・ボーズマン",
      castEn: "Viola Davis, Chadwick Boseman",
      castKo: "비올라 데이비스, 채드윅 보스만",
      dirJa: "ジョージ・C・ウルフ",
      dirEn: "George C. Wolfe",
      dirKo: "조지 C. 울프",
      infoJa: "2020年 / 94分 / アメリカ",
      infoEn: "2020 / 94 min / USA",
      infoKo: "2020년 / 94분 / 미국",
      quoteJa: "「この歌は私のソウルだ。誰にも渡さない」",
      quoteEn: "“This music isn't just notes, it's my soul.”",
      quoteKo: "“이 노래는 나의 영혼이다. 누구에게도 넘기지 않는다.”",
      descJa: "1920年代シカゴのレコーディングスタジオ。「ブルースの母」と呼ばれた実在の伝説的歌手マ・レイニーが、白人経営者たちの搾取に対抗し、同性愛を含めた自らの信念と誇りを誇示する白熱の音楽実話ドラマ。",
      descEn: "In 1920s Chicago, legendary 'Mother of the Blues' Ma Rainey fights for creative control, autonomy, and identity against white music executives during a fiery recording session.",
      descKo: "1920년대 시카고의 녹음 스튜디오. '블루스의 어머니'라 불린 실존 전설적 가수 마 레이니가 백인 경영자들의 착취에 맞서 동성애를 포함한 자신의 신념과 자긍심을 과시하는 뜨거운 음악 실화 드라마."
    },
    {
      genreId: "true-story",
      titleJa: "コレット",
      titleEn: "Colette",
      titleKo: "콜렛",
      castJa: "キーラ・ナイトレイ, ドミニク・ウェスト",
      castEn: "Keira Knightley, Dominic West",
      castKo: "키이라 나이트레이, 도미닉 웨스트",
      dirJa: "ウォッシュ・ウエストモアランド",
      dirEn: "Wash Westmoreland",
      dirKo: "워시 웨스트모어랜드",
      infoJa: "2018年 / 111分 / イギリス・アメリカ",
      infoEn: "2018 / 111 min / USA, UK",
      infoKo: "2018년 / 111분 / 영국·미국",
      quoteJa: "「私のペンは、私だけのもの」",
      quoteEn: "“The hand that holds the pen writes my own story.”",
      quoteKo: "“내 펜은 오직 나의 것이다.”",
      descJa: "20世紀初頭のパリ。夫のゴーストライターとして大ヒット作を生み出していた実在の女性作家コレットが、女性たちとの自由な恋愛と舞台活動を通じて自身の権利を取り戻し自立していく感動の伝記ドラマ。",
      descEn: "After writing a bestselling novel published under her husband's name, French author Colette fights for creative ownership, embracing romantic liberation and artistic independence.",
      descKo: "20세기 초 파리. 남편의 유령 작가로서 대히트작을 써내던 실존 여성 작가 콜렛이 여성들과의 자유로운 연애와 무대 활동을 통해 자신의 권리를 되찾고 자립해 나가는 감동적인 전기 드라마."
    },
    {
      genreId: "true-story",
      titleJa: "ブライアン・ウィルソン ソング・ライター",
      titleEn: "Love & Mercy",
      titleKo: "러브 앤 머시",
      castJa: "ジョン・キューザック, ポール・ダノ, エリザベス・バンクス",
      castEn: "John Cusack, Paul Dano, Elizabeth Banks",
      castKo: "존 쿠삭, 폴 다노, 엘리자베스 뱅크스",
      dirJa: "ビル・ポーラッド",
      dirEn: "Bill Pohlad",
      dirKo: "빌 포라드",
      infoJa: "2014年 / 121分 / アメリカ",
      infoEn: "2014 / 121 min / USA",
      infoKo: "2014년 / 121분 / 미국",
      quoteJa: "「君の存在が、私の壊れた心に光をくれた」",
      quoteEn: "“Your presence brought music back to my broken heart.”",
      quoteKo: "“너의 존재가 나의 부서진 마음에 빛을 주었다.”",
      descJa: "ザ・ビーチ・ボーイズの天才ミュージシャン、ブライアン・ウィルソンの光と影。精神的苦痛と支配から逃れ、運命の女性メリンダとの出会いによって救われ再起を果たす奇跡の実話伝記映画。",
      descEn: "Unveils the brilliant musical mind and internal struggles of Beach Boys founder Brian Wilson, and how his romantic partner Melinda helped rescue him from a controlling environment.",
      descKo: "비치 보이스의 천재 뮤지션 브라이언 윌슨의 빛과 그림자. 정신적 고통과 지배에서 벗어나 운명의 여성 멜린다와의 만남을 통해 구원받고 재기하는 기적의 실화 전기 영화."
    },
  ];