const shopDetails = [
    // H系列 (H)
    { name: "一(はじめ)", series: "H系列", seriesMark: "H", type: "MIX", area: "東京", xId: "@barhajime", snsUrl: "https://x.com/barhajime", time: "19:00～26:00,20:00〜4:00", holiday: "日曜,火曜", address: "東京都新宿区新宿2丁目-12-14-1A", tags: ["カラオケ", "喫煙可", "初心者向け", "年齢層高め", "変わったリキュール有", "穏やか", "ボトルキープ有", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/barhajime" },
    { name: "八(はち)", series: "H系列", seriesMark: "H", type: "ビアン", area: "東京", xId: "@hachi_omusubi_8", snsUrl: "https://x.com/hachi_omusubi_8", time: "20:00〜25:00", holiday: "日曜,月曜", address: "東京都新宿区新宿2丁目-15-13第二中江ビルB1", tags: ["喫煙可", "初心者向け", "初心者多め", "変わったリキュール有", "穏やか", "イベント多い", "フード有", "盛り上がる"], icon: "https://unavatar.io/twitter/hachi_omusubi_8" },
    { name: "はっちゃけ", series: "H系列", seriesMark: "H", type: "MIX", area: "東京", xId: "@hacchake_nicho", snsUrl: "https://x.com/hacchake_nicho", time: "18:00〜24:00", holiday: "日曜,月曜,火曜", address: "東京都新宿区新宿2丁目-14-11フタミビル101-A", tags: ["初心者向け", "穏やか", "お通し有", "フード有"], icon: "https://unavatar.io/twitter/hacchake_nicho" },
    { name: "PUZZLE", series: "H系列", seriesMark: "H", type: "ビアン", area: "東京", xId: "@BarPUZZLE1", snsUrl: "https://x.com/BarPUZZLE1", time: "20:00〜26:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-13-14jビルディング1F", tags: ["カラオケ", "喫煙可", "初心者向け", "初心者多め", "穏やか", "変わったリキュール有", "持ち込み食べ物可", "イベント多い"], icon: "https://unavatar.io/twitter/BarPUZZLE1" },
    { name: "パズルアソビ", series: "H系列", seriesMark: "H", type: "ビアン", area: "東京", xId: "@puzzleasobi2", snsUrl: "https://x.com/puzzleasobi2", time: "21:00〜9:00", holiday: "不定休", address: "東京都新宿区新宿1丁目36-3新宿御苑136ビル6F", tags: [], icon: "https://unavatar.io/twitter/puzzleasobi2" },

    // A系列 (A)
    { name: "agit", series: "A系列", seriesMark: "A", type: "ビアン", area: "東京", xId: "@agit_staff", snsUrl: "https://x.com/agit_staff", time: "19:00〜25:00,19:00～27:00", holiday: "月曜,火曜", address: "東京都新宿区新宿2-15-11-1F", tags: [], icon: "https://unavatar.io/twitter/agit_staff" },
    { name: "anchor rainbow port tokyo", series: "A系列", seriesMark: "A", type: "MIX", area: "東京", xId: "@anchor_staff", snsUrl: "https://x.com/anchor_staff", time: "12:00〜25:00,12:00～5:00", holiday: "火曜,水曜", address: "東京都新宿区新宿2丁目-12-15山原ハイツ2F", tags: [], icon: "https://unavatar.io/twitter/anchor_staff" },
    { name: "艶櫻", series: "A系列", seriesMark: "A", type: "MIX", area: "東京", xId: "@adezakura_staff", snsUrl: "https://x.com/adezakura_staff", time: "21:00〜5:00,21:00～6:00", holiday: "月曜,火曜", address: "東京都新宿区新宿2丁目15-11-1F", tags: ["初心者向け", "初心者多め", "イベント多い", "変わったリキュール有"], icon: "https://unavatar.io/twitter/adezakura_staff" },

    // B系列 - Lグループ (B(L))
    { name: "LITTLE MONKEY", series: "B系列", seriesMark: "B(L)", type: "ビアン", area: "東京", xId: "@little_monkey80", snsUrl: "https://x.com/little_monkey80", time: "20:00〜5:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-14-7赤川ビル1階", tags: ["カラオケ", "喫煙可", "初心者向け", "初心者多め", "盛り上がる", "イベント多い", "持ち込み食べ物可", "穏やか"], icon: "https://unavatar.io/twitter/little_monkey80" },
    { name: "LAUGH", series: "B系列", seriesMark: "B(L)", type: "ビアン", area: "東京", xId: "@BARLAUGH07", snsUrl: "https://x.com/BARLAUGH07", time: "20:00〜5:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-18-7ふぁーぶる店舗2F", tags: ["カラオケ", "喫煙可", "初心者多め", "初心者向け", "イベント多い", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/BARLAUGH07" },
    { name: "Lin9", series: "B系列", seriesMark: "B(L)", type: "MIX", area: "東京", xId: "@Lin993960", snsUrl: "https://x.com/Lin993960", time: "20:00〜5:00", holiday: "不定休", address: "東京都新宿区新宿1丁目新宿御苑136ビル9F", tags: ["カラオケ", "喫煙可", "初心者向け", "イベント多い", "持ち込み食べ物可", "盛り上がる", "穏やか"], icon: "https://unavatar.io/twitter/Lin993960" },

    // B系列 - Gグループ (B(G))
    { name: "グルークファースト", series: "B系列", seriesMark: "B(G)", type: "MIX", area: "東京", xId: "@gluck_mixbar", snsUrl: "https://x.com/gluck_mixbar", time: "20:00〜8:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-18-7ふぁーぶる店舗1階", tags: ["カラオケ", "喫煙可", "初心者向け", "初心者多め", "イベント多い", "持ち込み食べ物可", "ボトルキープ有", "盛り上がる", "穏やか"], icon: "https://unavatar.io/twitter/gluck_mixbar" },
    { name: "グルークネクスト", series: "B系列", seriesMark: "B(G)", type: "MIX", area: "東京", xId: "@gluck_mixbar", snsUrl: "https://x.com/gluck_mixbar", time: "20:00〜5:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-12-11林ビル2階", tags: ["カラオケ", "喫煙可", "初心者多め", "初心者向け", "ボトルキープ有", "イベント多い", "盛り上がる", "穏やか"], icon: "https://unavatar.io/twitter/gluck_mixbar" },
    { name: "グルークゼロ", series: "B系列", seriesMark: "B(G)", type: "MIX", area: "東京", xId: "@gluck_mixbar", snsUrl: "https://x.com/gluck_mixbar", time: "20:00〜5:00,19:00~5:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-12-15 山原ハイツB1", tags: ["カラオケ", "喫煙可", "初心者向け", "初心者多め", "ボトルキープ有", "イベント多い", "穏やか", "盛り上がる", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/gluck_mixbar" },
    { name: "GILLTY", series: "B系列", seriesMark: "B(G)", type: "MIX", area: "東京", xId: "Instagramのみ", snsUrl: "https://www.instagram.com/gillty__mixbar", time: "20:00〜27:00", holiday: "不定休", address: "東京都新宿区新宿1丁目-36-3新宿御苑136ビル1階", tags: ["喫煙可", "ボトルキープ有", "穏やか", "持ち込み食べ物可", "イベント多い"], icon: "instagram" },

    // 特別マークグループ
    { name: "GOLD FINGER", series: "GF系", seriesMark: "☝️", type: "MIX", area: "東京", xId: "@GOLDFINGERTOKYO", snsUrl: "https://x.com/GOLDFINGERTOKYO", time: "17:00〜24:00,17:00~28:00", holiday: "不定休", address: "東京都新宿区新宿2丁目 12-11林ビル1階", tags: ["初心者多め", "初心者向け"], icon: "https://unavatar.io/twitter/GOLDFINGERTOKYO" },
    { name: "ラブHOT", series: "GF系", seriesMark: "☝️", type: "ビアン", area: "東京", xId: "@GOLDFINGERTOKYO", snsUrl: "https://x.com/GOLDFINGERTOKYO", time: "19:00~26:00", holiday: "金曜と土曜以外", address: "東京都新宿区新宿2丁目 12-2-3、4、5階", tags: [], icon: "https://unavatar.io/twitter/GOLDFINGERTOKYO" },
    { name: "どん浴", series: "船系", seriesMark: "🚢", type: "MIX", area: "東京", xId: "@donyoku2018", snsUrl: "https://x.com/donyoku2018", time: "14:00〜22:00", holiday: "火曜", address: "東京都新宿区新宿2丁目-7-3ヴェラハイツ新宿御苑203", tags: [], icon: "https://unavatar.io/twitter/donyoku2018" },
    { name: "どろぶね", series: "船系", seriesMark: "🚢", type: "ビアン", area: "東京", xId: "@dorobune1222", snsUrl: "https://x.com/dorobune1222", time: "19:00〜23:00", holiday: "不定休", address: "東京都新宿区新宿2-7-3ヴェラハイツ新宿御苑205", tags: ["初心者多め"], icon: "https://unavatar.io/twitter/dorobune1222" },

    // その他
    { name: "LAGOON", type: "ビアン", area: "東京", xId: "@lagoon0410", snsUrl: "https://x.com/lagoon0410", time: "18:00〜24:00,18:00～25:00", holiday: "日曜,月曜,木曜", address: "東京都新宿区新宿2丁目-18-10新千鳥街の中", tags: ["初心者向け", "初心者多め", "フード有", "お通し有", "変わったリキュール有", "穏やか", "年齢層高め"], icon: "https://unavatar.io/twitter/lagoon0410" },
    { name: "ELLVIE", type: "ビアン", area: "東京", xId: "@Ellevie_", snsUrl: "https://x.com/Ellevie_", time: "18:00〜24:00,18:00～4:00", holiday: "不定休", address: "東京都新宿区新宿2丁目18-10新千鳥街の中", tags: ["初心者多め", "初心者向け", "フード有", "変わったリキュール有", "穏やか", "ボトルキープ有", "年齢層高め"], icon: "https://unavatar.io/twitter/Ellevie_" },
    { name: "YES", type: "ビアン", area: "東京", xId: "@BAR_YES_201", snsUrl: "https://x.com/BAR_YES_201", time: "18:00〜last", holiday: "不定休", address: "東京都新宿区新宿2丁目 18-10-201", tags: ["穏やか", "年齢層高め", "変わったリキュール有", "お通し有", "ボトルキープ有", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/BAR_YES_201" },
    { name: "AVANTY", type: "ビアン", area: "東京", xId: "@yumineesan", snsUrl: "https://x.com/yumineesan", time: "20:00〜last", holiday: "月曜,木曜", address: "東京都新宿区新宿2丁目 18-10-1階", tags: ["穏やか", "お通し有", "フード有", "ボトルキープ有", "年齢層高め", "喫煙可"], icon: "https://unavatar.io/twitter/yumineesan" },
    { name: "バーファイブ5", type: "ビアン", area: "東京", xId: "@BAR_Five5", snsUrl: "https://x.com/BAR_Five5", time: "18:00〜24:00", holiday: "月曜,火曜", address: "東京都新宿区新宿2丁目-15-8-2F", tags: [], icon: "https://unavatar.io/twitter/BAR_Five5" },
    { name: "あじゃら", type: "MIX", area: "東京", xId: "@ajara_chibar", snsUrl: "https://x.com/ajara_chibar", time: "18:00〜25:00", holiday: "日曜", address: "東京都新宿区新宿2丁目 15-8", tags: ["初心者向け", "穏やか", "変わったリキュール有", "フード有", "年齢層高め", "喫煙可"], icon: "https://unavatar.io/twitter/ajara_chibar" },
    { name: "SUPERMODEL", type: "MIX", area: "東京", xId: "@supermodel0412", snsUrl: "https://x.com/supermodel0412", time: "20:00〜27:00,20:00~29:00", holiday: "火曜", address: "東京都新宿区新宿2丁目-15-8中村建物ビル1階", tags: ["カラオケ", "初心者多め", "喫煙可", "変わったリキュール有", "盛り上がる"], icon: "https://unavatar.io/twitter/supermodel0412" },
    { name: "うーたん", type: "ビアン", area: "東京", xId: "@3oKOFLjgPthoJF6", snsUrl: "https://x.com/3oKOFLjgPthoJF6", time: "20:00〜26:00", holiday: "日曜,月曜", address: "東京都新宿区新宿2丁目-16-3第三宏和ビル2階", tags: ["カラオケ", "穏やか", "盛り上がる", "喫煙可", "お通し有"], icon: "https://unavatar.io/twitter/3oKOFLjgPthoJF6" },
    { name: "バー絆", type: "ビアン", area: "東京", xId: "@kizunamio", snsUrl: "https://x.com/kizunamio", time: "19:00〜23:00", holiday: "月曜,火曜,木曜", address: "東京都新宿区新宿2丁目-16-3第三宏和ビル3階", tags: [], icon: "https://unavatar.io/twitter/kizunamio" },
    { name: "バーSTELLA", type: "MIX", area: "東京", xId: "@bar_lunastella", snsUrl: "https://x.com/bar_lunastella", time: "20:00〜5:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-10-3ユニビル3階", tags: [], icon: "https://unavatar.io/twitter/bar_lunastella" },
    { name: "TAMAGO", type: "MIX", area: "東京", xId: "@TAMAGO_BAR", snsUrl: "https://x.com/TAMAGO_BAR", time: "21:00〜26:00", holiday: "月曜", address: "東京都新宿区新宿2丁目", tags: ["カラオケ", "喫煙可", "穏やか", "年齢層高め", "盛り上がる"], icon: "https://unavatar.io/twitter/TAMAGO_BAR" },
    { name: "DIAMOND HOLIC", type: "ビアン", area: "東京", xId: "@DIAMOND_HOLIC", snsUrl: "https://x.com/DIAMOND_HOLIC", time: "19:00〜23:30,19:00~5:00", holiday: "月曜", address: "東京都新宿区新宿2丁目-18-8栗原ビル2階", tags: [], icon: "https://unavatar.io/twitter/DIAMOND_HOLIC" },
    { name: "SUNNY", type: "ビアン", area: "東京", xId: "@natsuyo32", snsUrl: "https://x.com/natsuyo32", time: "21:00〜", holiday: "日曜,月曜", address: "東京都新宿区新宿2丁目-15-8中村建物ビル2階", tags: [], icon: "https://unavatar.io/twitter/natsuyo32" },
    { name: "MIMOSA", type: "ビアン", area: "東京", xId: "@YuikaMimosa", snsUrl: "https://x.com/YuikaMimosa", time: "20:00〜23:00", holiday: "月曜,火曜", address: "東京都新宿区新宿2丁目-18-10 1階", tags: [], icon: "https://unavatar.io/twitter/YuikaMimosa" },
    { name: "HUNEY BUNNY", type: "ビアン", area: "東京", xId: "@HUNEY_BUNNY8282", snsUrl: "https://x.com/HUNEY_BUNNY8282", time: "21:00〜4:00", holiday: "日曜,月曜", address: "東京都新宿区新宿2丁目-12-11林ビルB1", tags: ["カラオケ", "喫煙可", "穏やか", "年齢層高め", "フード有", "お通し有", "盛り上がる"], icon: "https://unavatar.io/twitter/HONEY_BUNNY8282" },
    { name: "villain", type: "MIX", area: "東京", xId: "@bar_villains", snsUrl: "https://x.com/bar_villains", time: "21:00〜9:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-12-16セントフォービル901", tags: ["カラオケ", "喫煙可", "穏やか", "初心者向け", "フード有", "盛り上がる", "持ち込み食べ物可", "イベント多い"], icon: "https://unavatar.io/twitter/bar_villains" },
    { name: "パンドラ", type: "MIX", area: "東京", xId: "@_pandora_2017", snsUrl: "https://x.com/_pandora_2017", time: "22:00〜5:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-12-16セントフォービル201", tags: ["カラオケ", "喫煙可", "穏やか", "盛り上がる", "ボトルキープ有", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/_pandora_2017" },
    { name: "YOTTA", type: "MIX", area: "東京", xId: "@YOTTA0701", snsUrl: "https://x.com/YOTTA0701", time: "20:00〜5:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-11-11近藤ビル201", tags: [], icon: "https://unavatar.io/twitter/YOTTA0701" },
    { name: "BAR Nico", type: "MIX", area: "東京", xId: "@BarNico0627", snsUrl: "https://x.com/BarNico0627", time: "20:00〜5:00,20:00~8:00", holiday: "不定休", address: "東京都新宿区新宿1丁目-36-3新宿御苑136ビル2階", tags: [], icon: "https://unavatar.io/twitter/BarNico0627" },
    { name: "Lily and", type: "ビアン", area: "東京", xId: "@lilyand2mixbar", snsUrl: "https://x.com/lilyand2mixbar", time: "18:00〜23:00,20:00~26:00", holiday: "不定休", address: "東京都新宿区新宿2丁目 12-15山原ハイツ401", tags: [], icon: "https://unavatar.io/twitter/lilyand2mixbar" },
    { name: "bar belle by あじゃり", type: "ビアン", area: "東京", xId: "@barbelless", snsUrl: "https://x.com/barbelless", time: "21:00〜5:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-15-14パンチョスタワー4F", tags: ["カラオケ", "喫煙可", "フード有", "イベント多い", "穏やか"], icon: "https://unavatar.io/twitter/barbelless" },
    { name: "BELLUS", type: "MIX", area: "東京", xId: "@BELLUS2023", snsUrl: "https://x.com/BELLUS2023", time: "21:00〜27:00", holiday: "不定休", address: "東京都新宿区新宿2丁目-18-10", tags: ["カラオケ", "変わったリキュール有", "穏やか", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/BELLUS2023" },
    { name: "香まり", type: "MIX", area: "東京", xId: "@sexual_mix", snsUrl: "https://x.com/sexual_mix", time: "19:30〜", holiday: "不定休", address: "東京都新宿区新宿2丁目-18-10新千鳥街1F", tags: ["喫煙可"], icon: "https://unavatar.io/twitter/sexual_mix" },
    { name: "QUEEN TOKYO", type: "MIX", area: "東京", xId: "Instagramのみ", snsUrl: "https://www.instagram.com/queentokyobar", time: "18:00〜26:30", holiday: "不定休", address: "東京都新宿区新宿2丁目-11-7-108", tags: ["喫煙可", "カラオケ", "盛り上がる", "持ち込み食べ物可", "初心者多い"], icon: "instagram" }
];