const shopDetails = [
    // H系列 (H)
    { name_jp: "一(はじめ)", name_en: "Bar Hajime", series: "H系列", seriesMark: "H", type: "MIX", area: "東京", xId: "@barhajime", snsUrl: "https://x.com/barhajime", time: "19:00～26:00,20:00〜4:00", holiday: "日曜,火曜", address_jp: "東京都新宿区新宿2丁目-12-14-1A", address_en: "1A, 2-12-14 Shinjuku, Shinjuku-ku, Tokyo", tags: ["カラオケ", "喫煙可", "初心者向け", "年齢層高め", "変わったリキュール有", "穏やか", "ボトルキープ有", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/barhajime", note: "https://note.com/412357siki/n/n214e5c8e1d02" },
    { name_jp: "八(はち)", name_en: "Bar Hachi", series: "H系列", seriesMark: "H", type: "ビアン", area: "東京", xId: "@hachi_omusubi_8", snsUrl: "https://x.com/hachi_omusubi_8", time: "20:00〜25:00", holiday: "日曜,月曜", address_jp: "東京都新宿区新宿2丁目-15-13第二中江ビルB1", address_en: "B1, Dai-ni Nakae Bldg, 2-15-13 Shinjuku, Tokyo", tags: ["喫煙可", "初心者向け", "初心者多め", "変わったリキュール有", "穏やか", "イベント多い", "フード有", "盛り上がる"], icon: "https://unavatar.io/twitter/hachi_omusubi_8", note: "#" },
    { name_jp: "はっちゃけ", name_en: "Hacchake", series: "H系列", seriesMark: "H", type: "MIX", area: "東京", xId: "@hacchake_nicho", snsUrl: "https://x.com/hacchake_nicho", time: "18:00〜24:00", holiday: "日曜,月曜,火曜", address_jp: "東京都新宿区新宿2丁目-14-11フタミビル101-A", address_en: "101-A, Futami Bldg, 2-14-11 Shinjuku, Tokyo", tags: ["初心者向け", "穏やか", "お通し有", "フード有"], icon: "https://unavatar.io/twitter/hacchake_nicho", note: "#" },
    { name_jp: "PUZZLE", name_en: "Bar PUZZLE", series: "H系列", seriesMark: "H", type: "ビアン", area: "東京", xId: "@BarPUZZLE1", snsUrl: "https://x.com/BarPUZZLE1", time: "20:00〜26:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-13-14jビルディング1F", address_en: "1F, J-Building, 2-13-14 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "初心者向け", "初心者多め", "穏やか", "変わったリキュール有", "持ち込み食べ物可", "イベント多い"], icon: "https://unavatar.io/twitter/BarPUZZLE1", note: "#" },
    { name_jp: "パズルアソビ", name_en: "PUZZLE ASOBI", series: "H系列", seriesMark: "H", type: "ビアン", area: "東京", xId: "@puzzleasobi2", snsUrl: "https://x.com/puzzleasobi2", time: "21:00〜9:00", holiday: "不定休", address_jp: "東京都新宿区新宿1丁目36-3新宿御苑136ビル6F", address_en: "6F, Shinjuku Gyoen 136 Bldg, 1-36-3 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/puzzleasobi2", note: "#" },

    // A系列 (A)
    { name_jp: "agit", name_en: "agit", series: "A系列", seriesMark: "A", type: "ビアン", area: "東京", xId: "@agit_staff", snsUrl: "https://x.com/agit_staff", time: "19:00〜25:00,19:00～27:00", holiday: "月曜,火曜", address_jp: "東京都新宿区新宿2-15-11-1F", address_en: "1F, 2-15-11 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/agit_staff", note: "#" },
    { name_jp: "anchor rainbow port tokyo", name_en: "anchor", series: "A系列", seriesMark: "A", type: "MIX", area: "東京", xId: "@anchor_staff", snsUrl: "https://x.com/anchor_staff", time: "12:00〜25:00,12:00～5:00", holiday: "火曜,水曜", address_jp: "東京都新宿区新宿2丁目-12-15山原ハイツ2F", address_en: "2F, Yamahara Heights, 2-12-15 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/anchor_staff", note: "#" },
    { name_jp: "艶櫻", name_en: "Adezakura", series: "A系列", seriesMark: "A", type: "MIX", area: "東京", xId: "@adezakura_staff", snsUrl: "https://x.com/adezakura_staff", time: "21:00〜5:00,21:00～6:00", holiday: "月曜,火曜", address_jp: "東京都新宿区新宿2丁目 15-11-1F", address_en: "1F, 2-15-11 Shinjuku, Tokyo", tags: ["初心者向け", "初心者多め", "イベント多い", "外国人多い","ノーチャージ","英語対応","変わったリキュール有"], icon: "https://unavatar.io/twitter/adezakura_staff", note: "#" },

    // B系列 - Lグループ (B(L))
   
    { name_jp: "LITTLE MONKEY", name_en: "LITTLE MONKEY", series: "B系列", seriesMark: "B(L)", type: "ビアン", area: "東京", xId: "@little_monkey80", snsUrl: "https://x.com/little_monkey80", time: "20:00〜5:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-14-7赤川ビル1階", address_en: "1F, Akagawa Bldg, 2-14-7 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "初心者向け", "初心者多め", "盛り上がる", "イベント多い", "持ち込み食べ物可", "穏やか"], icon: "https://unavatar.io/twitter/little_monkey80", note: "#" },
    { name_jp: "LAUGH", name_en: "LAUGH", series: "B系列", seriesMark: "B(L)", type: "ビアン", area: "東京", xId: "@BARLAUGH07", snsUrl: "https://x.com/BARLAUGH07", time: "20:00〜5:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-18-7ふぁーぶる店舗2F", address_en: "2F, 2-18-7 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "初心者多め", "初心者向け", "イベント多い", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/BARLAUGH07", note: "#" },
    { name_jp: "Lin9", name_en: "Lin9", series: "B系列", seriesMark: "B(L)", type: "MIX", area: "東京", xId: "@Lin993960", snsUrl: "https://x.com/Lin993960", time: "20:00〜5:00", holiday: "不定休", address_jp: "東京都新宿区新宿1丁目新宿御苑136ビル9F", address_en: "9F, Shinjuku Gyoen 136 Bldg, 1-36 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可","ボトルキープ有", "初心者向け", "イベント多い", "持ち込み食べ物可", "盛り上がる", "穏やか"], icon: "https://unavatar.io/twitter/Lin993960", note: "#" },

    // B系列 - Gグループ (B(G))
    { name_jp: "グルークファースト", name_en: "Gluck First", series: "B系列", seriesMark: "B(G)", type: "MIX", area: "東京", xId: "@gluck_mixbar", snsUrl: "https://x.com/gluck_mixbar", time: "20:00〜8:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-18-7ふぁーぶる店舗1階", address_en: "1F, 2-18-7 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "初心者向け", "初心者多め", "イベント多い", "持ち込み食べ物可", "ボトルキープ有", "盛り上がる", "穏やか"], icon: "https://unavatar.io/twitter/gluck_mixbar", note: "#" },
    { name_jp: "グルークネクスト", name_en: "Gluck Next", series: "B系列", seriesMark: "B(G)", type: "MIX", area: "東京", xId: "@gluck_mixbar", snsUrl: "https://x.com/gluck_mixbar", time: "20:00〜5:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-12-11林ビル2階", address_en: "2F, Hayashi Bldg, 2-12-11 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "初心者多め", "初心者向け", "ボトルキープ有", "イベント多い", "盛り上がる", "穏やか"], icon: "https://unavatar.io/twitter/gluck_mixbar", note: "#" },
    { name_jp: "グルークゼロ", name_en: "Gluck Zero", series: "B系列", seriesMark: "B(G)", type: "MIX", area: "東京", xId: "@gluck_mixbar", snsUrl: "https://x.com/gluck_mixbar", time: "20:00〜5:00,19:00~5:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-12-15 山原ハイツB1", address_en: "B1, Yamahara Heights, 2-12-15 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "初心者向け", "初心者多め", "ボトルキープ有", "イベント多い", "穏やか", "盛り上がる", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/gluck_mixbar", note: "#" },
    { name_jp: "GILLTY", name_en: "GILLTY", series: "B系列", seriesMark: "B(G)", type: "MIX", area: "東京", xId: "Instagramのみ", snsUrl: "https://www.instagram.com/gillty__mixbar", time: "20:00〜27:00", holiday: "不定休", address_jp: "東京都新宿区新宿1丁目-36-3新宿御苑136ビル1階", address_en: "1F, Shinjuku Gyoen 136 Bldg, 1-36-3 Shinjuku, Tokyo", tags: ["喫煙可", "ボトルキープ有", "穏やか", "持ち込み食べ物可", "イベント多い"], icon: "instagram", note: "#" },

    // 特別マークグループ
    { name_jp: "GOLD FINGER", name_en: "GOLD FINGER", series: "GF系", seriesMark: "☝️", type: "MIX", area: "東京", xId: "@GOLDFINGERTOKYO", snsUrl: "https://x.com/GOLDFINGERTOKYO", time: "17:00〜24:00,17:00~28:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目 12-11林ビル1階", address_en: "1F, Hayashi Bldg, 2-12-11 Shinjuku, Tokyo", tags: ["初心者多め","外国人多い","ノーチャージ","英語対応", "初心者向け"], icon: "https://unavatar.io/twitter/GOLDFINGERTOKYO", note: "#" },
    { name_jp: "ラブHOT", name_en: "LOVE HOT", series: "GF系", seriesMark: "☝️", type: "ビアン", area: "東京", xId: "@GOLDFINGERTOKYO", snsUrl: "https://x.com/GOLDFINGERTOKYO", time: "19:00~26:00", holiday: "金曜と土曜以外", address_jp: "東京都新宿区新宿2丁目 12-2-3、4、5階", address_en: "3-5F, 2-12-2 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/GOLDFINGERTOKYO", note: "#" },
    { name_jp: "どん浴", name_en: "Donyoku", series: "船系", seriesMark: "🚢", type: "MIX", area: "東京", xId: "@donyoku2018", snsUrl: "https://x.com/donyoku2018", time: "14:00〜22:00", holiday: "火曜", address_jp: "東京都新宿区新宿2丁目-7-3ヴェラハイツ新宿御苑203", address_en: "203, Vera Heights, 2-7-3 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/donyoku2018", note: "#" },
    { name_jp: "どろぶね", name_en: "Dorobune", series: "船系", seriesMark: "🚢", type: "ビアン", area: "東京", xId: "@dorobune1222", snsUrl: "https://x.com/dorobune1222", time: "19:00〜23:00", holiday: "不定休", address_jp: "東京都新宿区新宿2-7-3ヴェラハイツ新宿御苑205", address_en: "205, Vera Heights, 2-7-3 Shinjuku, Tokyo", tags: ["初心者多め"], icon: "https://unavatar.io/twitter/dorobune1222", note: "#" },

    // その他
    { name_jp: "LAGOON", name_en: "LAGOON", type: "ビアン", area: "東京", xId: "@lagoon0410", snsUrl: "https://x.com/lagoon0410", time: "18:00〜24:00,18:00～25:00", holiday: "日曜,月曜,木曜", address_jp: "東京都新宿区新宿2丁目-18-10新千鳥街の中", address_en: "Shin-Chidorigai, 2-18-10 Shinjuku, Tokyo", tags: ["初心者向け", "初心者多め", "フード有", "お通し有", "変わったリキュール有", "穏やか", "年齢層高め"], icon: "https://unavatar.io/twitter/lagoon0410", note: "https://note.com/412357siki/n/n44f1fe5eaca6" },
    { name_jp: "ELLVIE", name_en: "ELLVIE", type: "ビアン", area: "東京", xId: "@Ellevie_", snsUrl: "https://x.com/Ellevie_", time: "18:00〜24:00,18:00～4:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目18-10新千鳥街の中", address_en: "Shin-Chidorigai, 2-18-10 Shinjuku, Tokyo", tags: ["初心者多め", "初心者向け", "フード有", "変わったリキュール有", "穏やか", "ボトルキープ有", "年齢層高め"], icon: "https://unavatar.io/twitter/Ellevie_", note: "https://note.com/412357siki/n/n416d22497985?sub_rt=share_pb" },
    { name_jp: "YES", name_en: "YES", type: "ビアン", area: "東京", xId: "@BAR_YES_201", snsUrl: "https://x.com/BAR_YES_201", time: "18:00〜last", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目 18-10-201", address_en: "201, 2-18-10 Shinjuku, Tokyo", tags: ["穏やか", "年齢層高め", "変わったリキュール有", "お通し有", "ボトルキープ有", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/BAR_YES_201", note: "https://note.com/412357siki/n/n9f915b56c341" },
    { name_jp: "AVANTY", name_en: "AVANTY", type: "ビアン", area: "東京", xId: "@yumineesan", snsUrl: "https://x.com/yumineesan", time: "20:00〜last", holiday: "月曜,木曜", address_jp: "東京都新宿区新宿2丁目 18-10-1階", address_en: "1F, 2-18-10 Shinjuku, Tokyo", tags: ["穏やか", "お通し有", "フード有", "ボトルキープ有", "年齢層高め", "喫煙可"], icon: "https://unavatar.io/twitter/yumineesan", note: "https://note.com/412357siki/n/n8f9da14b0fef" },
    { name_jp: "バーファイブ5", name_en: "Bar Five5", type: "ビアン", area: "東京", xId: "@BAR_Five5", snsUrl: "https://x.com/BAR_Five5", time: "18:00〜24:00", holiday: "月曜,火曜", address_jp: "東京都新宿区新宿2丁目-15-8-2F", address_en: "2F, 2-15-8 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/BAR_Five5", note: "#" },
    { name_jp: "あじゃら", name_en: "Ajara", type: "MIX", area: "東京", xId: "@ajara_chibar", snsUrl: "https://x.com/ajara_chibar", time: "18:00〜25:00", holiday: "日曜", address_jp: "東京都新宿区新宿2丁目 15-8", address_en: "2-15-8 Shinjuku, Tokyo", tags: ["初心者向け", "穏やか", "変わったリキュール有", "フード有", "年齢層高め", "喫煙可"], icon: "https://unavatar.io/twitter/ajara_chibar", note: "#" },
    { name_jp: "SUPERMODEL", name_en: "SUPERMODEL", type: "MIX", area: "東京", xId: "@supermodel0412", snsUrl: "https://x.com/supermodel0412", time: "20:00〜27:00,20:00~29:00", holiday: "火曜", address_jp: "東京都新宿区新宿2丁目-15-8中村建物ビル1階", address_en: "1F, Nakamura Bldg, 2-15-8 Shinjuku, Tokyo", tags: ["カラオケ", "初心者多め", "喫煙可", "変わったリキュール有", "盛り上がる"], icon: "https://unavatar.io/twitter/supermodel0412", note: "#" },
    { name_jp: "うーたん", name_en: "U-tan", type: "ビアン", area: "東京", xId: "@3oKOFLjgPthoJF6", snsUrl: "https://x.com/3oKOFLjgPthoJF6", time: "20:00〜26:00", holiday: "日曜,月曜", address_jp: "東京都新宿区新宿2丁目-16-3第三宏和ビル2階", address_en: "2F, Dai-san Kowa Bldg, 2-16-3 Shinjuku, Tokyo", tags: ["カラオケ", "穏やか", "盛り上がる", "喫煙可", "お通し有"], icon: "https://unavatar.io/twitter/3oKOFLjgPthoJF6", note: "#" },
    { name_jp: "バー絆", name_en: "Bar Kizuna", type: "ビアン", area: "東京", xId: "@kizunamio", snsUrl: "https://x.com/kizunamio", time: "19:00〜23:00", holiday: "月曜,火曜,木曜", address_jp: "東京都新宿区新宿2丁目-16-3第三宏和ビル3階", address_en: "3F, Dai-san Kowa Bldg, 2-16-3 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/kizunamio", note: "#" },
    { name_jp: "バーSTELLA", name_en: "Bar STELLA", type: "MIX", area: "東京", xId: "@bar_lunastella", snsUrl: "https://x.com/bar_lunastella", time: "20:00〜5:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-10-3ユニビル3階", address_en: "3F, Uni-Bldg, 2-10-3 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/bar_lunastella", note: "#" },
    { name_jp: "TAMAGO", name_en: "TAMAGO", type: "MIX", area: "東京", xId: "@TAMAGO_BAR", snsUrl: "https://x.com/TAMAGO_BAR", time: "21:00〜26:00", holiday: "月曜", address_jp: "東京都新宿区新宿2丁目", address_en: "2-chome, Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "穏やか", "年齢層高め", "盛り上がる"], icon: "https://unavatar.io/twitter/TAMAGO_BAR", note: "#" },
    { name_jp: "DIAMOND HOLIC", name_en: "DIAMOND HOLIC", type: "ビアン", area: "東京", xId: "@DIAMOND_HOLIC", snsUrl: "https://x.com/DIAMOND_HOLIC", time: "19:00〜23:30,19:00~5:00", holiday: "月曜", address_jp: "東京都新宿区新宿2丁目-18-8栗原ビル2階", address_en: "2F, Kurihara Bldg, 2-18-8 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/DIAMOND_HOLIC", note: "#" },
    { name_jp: "SUNNY", name_en: "SUNNY", type: "ビアン", area: "東京", xId: "@natsuyo32", snsUrl: "https://x.com/natsuyo32", time: "21:00〜", holiday: "日曜,月曜", address_jp: "東京都新宿区新宿2丁目-15-8中村建物ビル2階", address_en: "2F, Nakamura Bldg, 2-15-8 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/natsuyo32", note: "#" },
    { name_jp: "MIMOSA", name_en: "MIMOSA", type: "ビアン", area: "東京", xId: "@YuikaMimosa", snsUrl: "https://x.com/YuikaMimosa", time: "20:00〜23:00", holiday: "月曜,火曜", address_jp: "東京都新宿区新宿2丁目-18-10 1階", address_en: "1F, 2-18-10 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/YuikaMimosa", note: "#" },
    { name_jp: "HUNEY BUNNY", name_en: "HUNEY BUNNY", type: "ビアン", area: "東京", xId: "@HUNEY_BUNNY8282", snsUrl: "https://x.com/HUNEY_BUNNY8282", time: "21:00〜4:00", holiday: "日曜,月曜", address_jp: "東京都新宿区新宿2丁目-12-11林ビルB1", address_en: "B1, Hayashi Bldg, 2-12-11 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "穏やか", "年齢層高め", "フード有", "お通し有", "盛り上がる"], icon: "https://unavatar.io/twitter/HONEY_BUNNY8282", note: "#" },
    { name_jp: "villain", name_en: "villain", type: "MIX", area: "東京", xId: "@bar_villains", snsUrl: "https://x.com/bar_villains", time: "21:00〜9:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-12-16セントフォービル901", address_en: "901, St. Four Bldg, 2-12-16 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "穏やか", "初心者向け", "フード有", "盛り上がる", "持ち込み食べ物可", "イベント多い"], icon: "https://unavatar.io/twitter/bar_villains", note: "#" },
    { name_jp: "パンドラ", name_en: "Pandora", type: "MIX", area: "東京", xId: "@_pandora_2017", snsUrl: "https://x.com/_pandora_2017", time: "22:00〜5:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-12-16セントフォービル201", address_en: "201, St. Four Bldg, 2-12-16 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "穏やか", "盛り上がる", "ボトルキープ有", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/_pandora_2017", note: "#" },
    { name_jp: "YOTTA", name_en: "YOTTA", type: "MIX", area: "東京", xId: "@YOTTA0701", snsUrl: "https://x.com/YOTTA0701", time: "20:00〜5:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-11-11近藤ビル201", address_en: "201, Kondo Bldg, 2-11-11 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/YOTTA0701", note: "#" },
    { name_jp: "BAR Nico", name_en: "BAR Nico", type: "MIX", area: "東京", xId: "@BarNico0627", snsUrl: "https://x.com/BarNico0627", time: "20:00〜5:00,20:00~8:00", holiday: "不定休", address_jp: "東京都新宿区新宿1丁目-36-3新宿御苑136ビル2階", address_en: "2F, Shinjuku Gyoen 136 Bldg, 1-36-3 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/BarNico0627", note: "#" },
    { name_jp: "Lily and", name_en: "Lily and", type: "ビアン", area: "東京", xId: "@lilyand2mixbar", snsUrl: "https://x.com/lilyand2mixbar", time: "18:00〜23:00,20:00~26:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目 12-15山原ハイツ401", address_en: "401, Yamahara Heights, 2-12-15 Shinjuku, Tokyo", tags: [], icon: "https://unavatar.io/twitter/lilyand2mixbar", note: "#" },
    { name_jp: "bar belle by あじゃり", name_en: "Bar Belle", type: "ビアン", area: "東京", xId: "@barbelless", snsUrl: "https://x.com/barbelless", time: "21:00〜5:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-15-14パンチョスタワー4F", address_en: "4F, Panchos Tower, 2-15-14 Shinjuku, Tokyo", tags: ["カラオケ", "喫煙可", "フード有", "イベント多い", "穏やか"], icon: "https://unavatar.io/twitter/barbelless", note: "#" },
    { name_jp: "BELLUS", name_en: "BELLUS", type: "MIX", area: "東京", xId: "@BELLUS2023", snsUrl: "https://x.com/BELLUS2023", time: "21:00〜27:00", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-18-10", address_en: "2-18-10 Shinjuku, Tokyo", tags: ["カラオケ", "変わったリキュール有", "穏やか", "持ち込み食べ物可"], icon: "https://unavatar.io/twitter/BELLUS2023", note: "#" },
    { name_jp: "香まり", name_en: "Kamari", type: "MIX", area: "東京", xId: "@sexual_mix", snsUrl: "https://x.com/sexual_mix", time: "19:30〜", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-18-10新千鳥街1F", address_en: "1F, Shin-Chidorigai, 2-18-10 Shinjuku, Tokyo", tags: ["喫煙可"], icon: "https://unavatar.io/twitter/sexual_mix", note: "#" },
    { name_jp: "QUEEN TOKYO", name_en: "QUEEN TOKYO", type: "MIX", area: "東京", xId: "Instagramのみ", snsUrl: "https://www.instagram.com/queentokyobar", time: "18:00〜26:30", holiday: "不定休", address_jp: "東京都新宿区新宿2丁目-11-7-108", address_en: "108, 2-11-7 Shinjuku, Tokyo", tags: ["喫煙可", "カラオケ", "盛り上がる","外国人多い","ノーチャージ","英語対応", "持ち込み食べ物可", "初心者多い"], icon: "instagram", note: "#" }
];