
  const yuri_data = [
    {
      cat: "🏫 学園・青春の情景", 
      en_cat: "🏫Scenes of School & Youth",
      desc: "多感な時期を過ごす学校という閉鎖的で聖域のような空間。そこで育まれるのは、単なる友情という言葉では片付けられない、切実で時に残酷なほどの純愛です。少女たちが自己を見つめ、誰かを想うことで変化していく繊細な心の機微を、鮮やかな筆致で描いた作品を選出しました。",
      en_desc: "The closed, sanctuary-like space of school during a sensitive period of life. What is nurtured there is a sincere and sometimes cruelly pure love that cannot be dismissed by the simple word 'friendship.' We have selected works that vividly depict the delicate subtleties of the heart as girls look at themselves and change by thinking of someone else.",
      works: [
        { n:1, t:"やがて君になる", en_t:"Bloom Into You", a:"仲谷鳰", en_a:"Nio Nakatani", d:"「人を好きになる」感覚が欠如した少女たちが、本物の愛に手を伸ばす。", en_d:"Girls who lack the feeling of 'falling in love' reach out for real affection.", amz:"https://amzn.to/3RnHDbx" },
        { n:2, t:"気になってる人が男じゃなかった", en_t:"The Guy She Was Interested in Wasn't a Guy", a:"新井すみこ", en_a:"Sumiko Arai", d:"CDショップで出会ったミステリアスな「彼」。音楽が二人の世界を変える。", en_d:"The mysterious 'guy' she met at a CD shop. Music changes their world.", amz:"https://amzn.to/3QQtW4N" },
        { n:3, t:"安達としまむら", en_t:"Adachi and Shimamura", a:"まに（漫画）/ 入間人間", en_a:"Mani / Hitoma Iruma", d:"体育館の二階で出会った二人。巨大な執着と、静かな波紋が広がる日常。", en_d:"Two girls meet in the gym loft. Daily life filled with obsession and quiet ripples.", amz:"https://amzn.to/4f3Vw8G" },
        { n:4, t:"ささやくように恋を唄う", en_t:"Whisper Me a Love Song", a:"竹嶋えく", en_a:"Eku Takeshima", d:"「ひとめぼれ」から始まるバンドと恋。透明感溢れる心理描写。", en_d:"A band and love story starting from 'love at first sight'.", amz:"https://amzn.to/4tnZMn3" },
        { n:5, t:"citrus", en_t:"citrus", a:"サブロウタ", en_a:"Saburouta", d:"派手なJKと厳格な生徒会長の義妹。反発しながら惹かれ合うドラマ。", en_d:"A flashy girl and her strict student council president step-sister.", amz:"https://amzn.to/4wb05nN" },
        { n:6, t:"ゆるゆり", en_t:"YuruYuri", a:"なもり", en_a:"Namori", d:"日常コメディの中にある強固なキャラクター間の情愛。", en_d:"A daily comedy depicting the deep affection between characters.", amz:"https://amzn.to/3Rn6zzT" },
        { n:7, t:"青い花", en_t:"Sweet Blue Flowers", a:"志村貴子", en_a:"Takako Shimura", d:"思春期の揺らぎを文学的に描いた不朽の傑作。", en_d:"A literary masterpiece depicting the tremors of adolescence.", amz:"https://amzn.to/4ts5Bjy" },
        { n:8, t:"はなにあらし", en_t:"Hana ni Arashi", a:"古鉢るか", en_a:"Ruka Kobachi", d:"「付き合っている」秘密を共有する親友。砂糖をまぶしたような甘い日常。", en_d:"Best friends sharing the secret that they are dating.", amz:"https://amzn.to/4cUlKJm" },
        { n:9, t:"熱帯魚は雪に焦がれる", en_t:"Tropical Fish Yearns for Snow", a:"萩原ダイスケ", en_a:"Daisuke Hagiwara", d:"水族館部を舞台に、孤独を埋めようとする少女たち。", en_d:"Girls trying to fill their loneliness at the aquarium club.", amz:"https://amzn.to/4eqNYN7" },
        { n:10, t:"女同士とかありえないでしょと言い張る女の子を、百日間で徹底的に落とす百合のお話", en_t:"Hundred Days Yuri", a:"みかみてれん", en_a:"Teren Mikami", d:"ライトノベルならではの熱量の「落とし」劇。", en_d:"An explosive high-energy light novel romance.", amz:"https://amzn.to/42lNlgt", rkt:"https://a.r10.to/h5r6K9" },
   
      ]
    },
  
    {
      cat: "🏫 学園・青春の情景（つづき）", 
      en_cat: "🏫Scenes of School & Youth (Continued)",
      desc: "まだまだ終わらない名作たちの系譜。さらに深く、色鮮やかな少女たちの物語を揃えました。",
      en_desc: "The lineage of masterpieces that never ends. Here are more deep and colorful stories of girls.",
      works: [
        { n:11, t: "私を喰いたい、ひとでなし",  en_t: "This Monster Wants to Eat Me", a: "苗川 采", en_a: "Sai Naekawa", d: "海辺の街で孤独を抱えて生きる女子高生・比名子と、彼女を「最高に美味しい状態で喰う」ために近づいた人魚の妖怪・汐莉。凄惨な運命の中で、死を望んでいた少女の心が、奇妙な怪異との交流によって生への執着と強い結びつきへ変容していく、どこか物悲しくも美しいダークファンタジー。", en_d: "Hinako, a high school girl living with deep loneliness in a coastal town, meets Shiori, a mermaid folklore monster who approaches her to eventually devour her. Amidst a bizarre fate and a melancholic atmosphere, the girl's desire for death gradually transforms into a powerful bond and an attachment to life.",amz: "https://amzn.to/4p8eSg7" },
        { n:12, t: "どれが恋かがわからない", en_t: "I Don't Know Which One is Love", a: "奥たまむし", en_a: "Tamamushi Oku", d: "主人公・空池（そらいけ）メイは、高校の卒業式に片想いしていた親友への告白に大失敗。「大学では絶対に可愛い彼女を作る！」と意気込んで進学したものの、彼女の前に現れたのは、お色気たっぷりのハイスペックお姉さん、距離感が近すぎるクールなイケメン女子、超肉食系な元同級生のギャルなど、一癖も二癖もある魅力的な女性たちばかり。次々と迫りくる女の子たちに翻弄され、甘い誘惑やエロティックなハプニングにドギマギさせられながらも、本当の『恋』の定義を探し求めて奮闘する、賑やかでちょっぴり過激な多角関係ラブコメディの開幕！", en_d: "On her high school graduation day, the protagonist Mei Soraike completely fumbles her confession to her best friend and crush. Vowing to definitely get a cute girlfriend in college, she enters university with high spirits—only to find herself surrounded by an array of eccentric, highly attractive women. From a voluptuous, high-spec older student and a cool, handsome girl with zero concept of personal space, to a fiercely predatory gyaru who used to be her classmate. Constantly flustered by their bold advances, sweet seductions, and highly erotic accidental run-ins, Mei frantically tries to figure out the true definition of 'love' in this chaotic, slightly spicy, multi-faceted romantic comedy!", amz: "https://amzn.to/4paUZEW" },
        { n:13, t: "猫ノ山寧々子はネコになる", en_t: "Neneko Nekonoyama Turns Into a Cat", a: "ひのはら (著), ミト (イラスト)",  en_a: "Hinohara (Author), Mito (Illustrator)", d: "猫になれる亜人の女子高生・寧々子は、人見知りで臆病な性格。唯一心を許せる姉の友人・ましろに憧れを募らせていたが、ある日彼女が吸血鬼であることを知る。寧々子は彼女の血液提供者（パートナー）として同棲を提案し――。恋に不器用な少女たちのピュアラブストーリー。", en_d: "Neneko, a shy high school girl who can transform into a cat, harbors a deep admiration for Mashiro, her older sister's mysterious friend. Upon discovering that Mashiro is actually a vampire, Neneko proposes moving in together as her blood donor and partner. A pure love story of two girls clumsy in romance.", amz: "https://amzn.to/4bdnuvZ" },
        { n:14, t:"徒然日和", en_t:"Tsurezure Hiyori", a:"浜弓場双", en_a:"Sou Hamayumiba", d:"のどかな田舎の学校を舞台に、少女たちが紡ぐ緩やかで愛おしい青春の1ページ。", en_d:"A slow and lovely piece of youth woven by girls set in a peaceful countryside school.", amz:"https://amzn.to/4eVFcXn" },
        { n:15, t:"ささめきこと", en_t:"Sasameki Koto", a:"いんだまんだ", en_a:"Ikamanda", d:"「可愛い女の子」が好きな少女と、彼女に片想いをするクールな少女のすれ違い学園ラブコメ。", en_d:"A school romantic comedy about a girl who loves cute girls and her cool friend who secretly loves her.", amz:"https://amzn.to/44dS8Se" },
        { n:16, t:"行進子犬に恋文を", en_t:"Love Letter for the Marching Puppy", a:"玉崎たま", en_a:"Tama Tamasaki", d:"陸軍幼年学校を舞台に、規律の中で不器用な少女たちが育む凛々しくも切ない恋心。", en_d:"Set in a military youth academy, a noble and emotional story about clumsy girls navigating strict discipline.", amz:"https://amzn.to/44d89Yw" },
        { n:17, t:"小百合さんの妹は天使", en_t:"Sayuri-san's Sister is an Angel", a:"伊藤ハチ", en_a:"Hachi Ito", d:"血の繋がらない義理の妹との、優しくてちょっぴり切ない学園ホームドラマ。", en_d:"A gentle and slightly bittersweet school home drama with a step-sister who is like an angel.", amz:"https://amzn.to/4vJ4YUx" },
        { n:18, t: "アネモネは熱を帯びる", en_t: "Anemone Is Heat-Grown", a: "桜木蓮", en_a: "Ren Sakuragi", d: "不本意ながら進学した高校で、凪紗（なぎさ）は病弱な少女・茉白（ましろ）と出会う。彼女はなんと、凪紗が受験に失敗した原因となった因縁の少女だった……。自分を変えるため、凪紗は茉白を「好き」になろうと決意する。正反対な二人が紡ぎ出す、濃厚な百合世界。", en_d: "At a high school she never wanted to attend, Nagisa meets a sickly girl named Mashiro—who happens to be the very reason Nagisa failed her entrance exams. In a desperate bid to change herself, Nagisa resolves to make herself 'love' Mashiro. A dense, intense Yuri story woven by two contrasting girls.", amz: "https://amzn.to/4aCPclG" },
        { n:19, t:"きみが死ぬまで恋をしたい", en_t:"I Want to Love You Until You Die", a:"あおのなち", en_a:"Nachi Aono", d:"戦争に身を投じる魔法学校の子供たち。過酷な運命の中で、死が二人を分かつまで愛することを誓う。", en_d:"At a magical military academy where children are trained for war, two girls vow a deep, painful affection amid a dark, cruel fate.", amz:"https://amzn.to/4b5KNb2" },  
        { n:20, t: "踊り場にスカートが鳴る", en_t: "Skirts Sing on the Staircase Landing", a: "うたたね 游", en_a: "Yu Utatane", d: "桜ヶ森高校社交ダンス部2年の春間（はるま）ききは、本当は華麗に舞う「パートナー（女役）」に憧れながらも、高身長ゆえに周囲の期待通り「リーダー（男役）」を続けていた。ある日、幼馴染とのペア解消を機に、放課後の踊り場で人知れず理想のパートナーとしてのステップを踏んでいたところ、その姿を小柄で可憐な新入生・鳥羽見（とばみ）みちるに目撃される。「私のパートナーになってください」――みちるの真っ直ぐな言葉に導かれ、男役を望む後輩と、女役を夢見た先輩の、これまでの常識を覆す美しく熱い競技ダンス百合の幕が上がる。", en_d: "Kiki Haruma, a second-year student in her high school's ballroom dancing club, secretly longs to dance as a 'partner' (the follower), but her tall stature has always forced her into the role of a 'leader' (the leader). After her childhood friend breaks off their duo, Kiki is found dancing alone after school, practicing the fluid follower steps she deeply admires. Her graceful movements catch the eye of Michiru Tobami, a petite and elegant first-year student. Approaching Kiki, Michiru confidently asks, 'Please be my partner.' Entwining their hands, a senior who dreams of being led and a junior who desires to lead begin a stunning, passionate journey to redefine ballroom dancing together.", amz: "https://amzn.to/4vVzP0k" },
        ]
    },
  
    {
      cat: "🏫 学園・青春の情景（つづき）", 
      en_cat: "🏫Scenes of School & Youth (Continued)",
      desc: "青春の光と影、そして言葉にできない特別な関係。少女たちの心を鮮やかに切り取った名作たち。",
      en_desc: "The light and shadows of youth, and special relationships that transcend words. Masterpieces that vividly capture the hearts of girls.",
      works: [
        { n:21, t: "高音さんと嵐ちゃん", en_t: "Takane-san and Arashi-chan", a: "なうち", en_a: "Nauchi", d: "ちょっと強引でついつい攻めすぎてしまうお姉さん気質な高音（たかね）さんと、彼女の甘い誘惑にいつもドギマギしっぱなしで真っ赤になってしまうピュアな嵐（あらし）ちゃん。お互いが大好きでたまらない二人の、甘々で少し刺激的な日常をコミカルかつ愛らしく描く。貴方と過ごす毎日がとびきり愛おしくて幸せに満ちていく、ゼロ距離な溺愛ガールズラブコメディ。", en_d: "The sweet, heart-fluttering daily life of Takane, a slightly aggressive and deeply affectionate girl who loves to tease and pamper, and Arashi, a pure-hearted girl who constantly finds herself flustered and blushing at Takane's sweet advances. A deeply adorable and comforting slice-of-life Yuri comedy that captures the overwhelming happiness and absolute devotion found in their cozy, zero-distance relationship.", amz: "https://amzn.to/4aDBsqP" },
        { n:22, t: "付き合ってあげてもいいかな", en_t: "How Do We Relationship?", a: "たみふる", en_a: "Tamifull", d: "周囲から「超モテるいい女」に見られながらも、実は同性愛者であり、これまでに一度も好きな人と両想いになったことがない大学生のみわ。大学入学を機に入部した軽音サークルで、自分とは正反対の絶対友達にならないタイプだと思っていたお調子者の冴子と出会う。ひょんなことからお互いのセクシュアリティを打ち明け合い、「せっかくだからあたしたち、付き合ってみない？」と始まったリアルな恋。周囲の友人関係、セクシュアリティへの葛藤、綺麗事だけではいかない本音の女子大生ガールズラブ。", en_d: "Miwa is an outwardly popular and attractive university student who harbors a secret: she is a lesbian who has never experienced mutual love with someone she truly liked. After joining a college music club, she grows unexpectedly close to Saeko, an easygoing, outgoing girl she assumed she would never get along with. Upon discovering each other's hidden sexualities, Saeko casually suggests they start dating just to see how it goes. Moving past idealized romance, this poignant and realistic drama masterfully explores the genuine struggles of identity, social circles, and raw human relationships among college-aged women.", amz: "https://amzn.to/4wwMINZ" },    
        { n:23, t: "ロックは淑女の嗜みでして", en_t: "Rock Is a Lady's Modesty", a: "福田宏", en_a: "Hiroshi Fukuda", d: "全国から本物のお嬢様が集う超名門・お茶ノ水ノ女子学園。元庶民であることを隠し、完璧な淑女として息苦しい日々を強いる主人公・鈴ノ宮りりさは、ある日、旧校舎から響く激しいドラムの音に引き寄せられる。そこで目にしたのは、同じく完璧なお嬢様である黒鉄音羽がドラムを激しく叩き鳴らす姿だった。お互いの秘密とロックへの衝動を共有した二人が、気高きお嬢様学校を舞台に、美しく火花を散らしてシャウトする爆音ガールズロック青春劇。", en_d: "At an elite academy for high-class young ladies, Ririsa Suzunomiya constrains herself daily to act like a perfect, elegant lady, hiding her humble working-class roots. One day, she is drawn to the old school building by a thundering drumbeat, only to discover her flawless peer, Otoha Kurogane, furiously beating the drums. Sharing their hidden secrets and a mutual, burning impulse for rock music, the two noble girls begin to clash beautifully and shout out their souls in a high-octane, deafening youth rock drama.", amz: "https://amzn.to/4foK1Zc" },
        { n:24, t: "淡島百景", en_t: "Awajima Hyakkei", a: "志村貴子", en_a: "Takako Shimura", d: "舞台に立つことを夢みる少女たちが全国から集まる、淡島歌劇学校の合宿所（通称・寄宿舎）。ミュージカルスターに憧れて入学した若菜、親友の思いを背負って学び続ける寮長の絹枝、周囲の視線を集める美しき特待生の絵美。恋や友情、憧れ、執着、嫉妬、恐れといった、既存の言葉には当てはまらない瑞々しくも複雑な感情を抱えながら、かけがえのない季節を共に生きる少女たちの揺れる心を鮮やかに切り取ったオムニバス形式の青春群像劇。", en_d: "At the dormitory of the elite Awajima Opera School, girls from all over Japan gather with dreams of standing on stage. Among them are Wakana, who longs to be a musical star; Kinue, the dorm leader carrying her best friend's unfulfilled wishes; and Emi, a breathtakingly beautiful scholarship student. Capturing a kaleidoscope of unnameable emotions—love, friendship, admiration, obsession, and jealousy—this poignant omnibus drama beautifully illustrates the complex inner worlds of young women living through an irreplaceable season of youth.", amz: "https://amzn.to/44mR9z7" },
        { n:25, t: "割り切った関係ですから。", en_t: "It's a Business Relationship.", a: "FLOWERCHILD", en_a: "FLOWERCHILD", d: "スクールカースト低めで冴えない日々を送る女子高生の綾（あや）は、出会いを求めてマッチングアプリを始め、落ち着いた大人の女性「KURO」と繋がる。顔も知らないまま日々の何気ない会話や自撮りの交換を重ねて親密になっていく二人だったが、ある日KUROの異変に気づいた綾は、思い切って彼女のマンションを訪ねる。しかし、そこで扉を開けたのは、学校では完璧で冷徹な憧れの存在である美人教師の黒橋先生だった。アプリから始まる、女子高生と女教師の秘密の割り切った関係。", en_d: "Aya, a high school girl on the lower rungs of the school social hierarchy, uses a matching app out of loneliness and connects with a mature, soothing woman going by 'KURO.' Though they've never met in person, they bond deeply over daily text updates and exchanging selfies. One day, sensing something wrong with KURO, a worried Aya decides to visit her apartment for the first time. Upon knocking on the door, she is shocked to be greeted by Kurohashi-sensei—the flawless, cold, and revered teacher from her school. A secret, complex relationship between a student and her teacher begins.", amz: "https://amzn.to/4y8XX0Z" },
        { n:26, t: "顔だけ良いクラスメイトが、やたらとグイグイ来る百合の話。", en_t: "The Story of a Classmate Who Has Nothing Going for Her but Her Looks, Boldly Making Advances on Me.", a: "はちこ (著), 能代 リョウ (その他)", en_a: "Hachiko (Author), Ryo Noshiro (Other)", d: "スクールカースト最上位のグループに属し、周囲に流されるまま彼氏と付き合って1年になる女子高生・海道律（かいどう りつ）。ある日、彼氏とキスをしようとした瞬間を、クラスメイトの矢来綴（やらい つづり）に目撃されてしまう。どこか抜けているけれど、元気で優しくてとびきり「顔が良い」綴。この最悪な遭遇をきっかけに、なぜか綴からやたらと真っ直ぐにグイグイと距離を縮められるようになり、律の平凡だったはずの日常と恋心が大きく揺れ動き始める青春ガールズラブ。", en_d: "Ritsu Kaido, a high school girl belonging to the top school hierarchy, has been casually dating her boyfriend for almost a year just to blend in. On the day they are about to kiss, the moment is suddenly witnessed by her classmate, Tsuzuri Yarai. Despite being a bit scatterbrained, Tsuzuri is energetic, incredibly kind, and possesses breathtakingly good looks. Following this awkward encounter, Tsuzuri inexplicably begins to aggressively and honestly close the distance between them, sending Ritsu's seemingly ordinary daily life and her heart into a beautifully flustered spin.", amz: "https://amzn.to/4wtnRuA" },
        { n:27, t: "今日はカノジョがいないから", en_t: "Asumi-chan is Interested in Lesbian Brothels!", a: "岩見 樹代子", en_a: "Kiyoko Iwami", d: "周囲に隠れて付き合っている、女子高生の七瀬（ななせ）とゆに。ゆにはバレー部での練習に忙しい七瀬の事情を理解しつつも、寂しさを隠せない放課後を過ごしていた。その持て余した孤独と誰にも言えない秘密の恋の鬱屈を、ゆにはSNSの「裏垢」に自撮りや愚痴として投下し続けてしまう。しかし、そのアカウントが学校のクラスメイトにバレてしまった瞬間から、ゆにの静かだった日常は崩壊し、七瀬だけの従順な彼女ではいられなくなっていく。歪んだ関係と裏切りが交錯する、泥沼の背徳的ガールズラブドラマ。", en_d: "Yuni and Nanase are high school girls who are secretly dating. Although Yuni genuinely understands that Nanase is constantly preoccupied with her volleyball club, she can't help but feel a suffocating loneliness during their empty after-school hours. Seeking an escape, Yuni vents her unexpressed desires, selfies, and relationship frustrations onto a secret social media account. But when a classmate accidentally discovers her hidden profile, Yuni's quiet life shatters, and she finds herself unable to remain solely Nanase's faithful girlfriend. A dark, suspenseful Yuri drama filled with infidelity, secret deals, and emotional turmoil.", amz: "https://amzn.to/4fc32wP" },
        { n:28, t: "わたしが恋人になれるわけないじゃん、ムリムリ! （※ムリじゃなかった!?）", en_t: "There's No Way I Can Have a Lover After All (Or Maybe There Is?!)", a: "むっしゅ (著), 竹嶋 えく (著)", en_a: "Musshu (Author), Eku Takeshima (Character Design)", d: "中学時代のぼっち生活から脱却すべく、猛努力の末に高校デビューを果たした甘織れな子。しかし、根の陰キャ気質ゆえに無理して作った陽キャ生活に限界を迎え、窒息寸前になっていた。そんなある日、学校の誰もが憧れる完璧なスーパースター・王塚真唯とひょんなことから秘密を共有し、無二の親友になる。これで最高の学園生活が始まるかと思った矢先、真唯から「君に恋をしてしまった」とまさかの告白をされ――！？ 親友か恋人か、二人の関係性と最高の高校生活を勝ち取るために奮闘する、全力疾走の青春ガールズラブコメディ。", en_d: "Determined to leave her friendless middle school days behind, Renako Amaori undergoes a total makeover for her high school debut. However, her naturally introverted self quickly suffocates under the strain of pretending to be a popular socialite. In her moments of despair, she crosses paths with Mai Ouka—the school's absolute, flawless superstar. After sharing their hidden burdens, they form an unbreakable bond as best friends, or so Renako thought, until Mai suddenly confesses, 'I've fallen in love with you.' Refusing to give up either a best friend or a potential lover, Renako proposes a competition to see which dynamic fits them best. A high-energy, comedic, and heartwarming school Yuri romance.", amz: "https://amzn.to/4vXFAdQ" },
        { n:29, t: "週に一度クラスメイトを買う話 ～ふたりの時間、言い訳の五千円～", en_t: "Story of Buying a Classmate Once a Week: Our Time, the 5,000 Yen Excuse", a: "羽田 宇佐 (著), U35 (イラスト)", en_a: "Usa Haneda (Author), U35 (Illustrator)", d: "クラスの誰とも馴染もうとしない宮城と、スクールカーストの最上位に位置する仙台さん。交わるはずのなかった二人は、宮城の気まぐれな思いつきから、週に一度「五千円」で仙台さんの時間を買うという奇妙な秘密の契約を結ぶ。部屋で一緒にゲームをしたり、お菓子を食べさせたり、時には少し危険な命令を交わしたり――。「私たちは友達じゃない」と言い訳の五千円で繋がれたまま半年を過ごす中、徐々に歪な主従関係は執着へと変わり、二人の境界線を曖昧に溶かしていく。微熱を孕んだ女子高生二人の、息苦しくも切ないディスタンス百合ストーリー。", en_d: "Miyagi is a solitary high school girl who distances herself from her peers, while Sendai sits at the very top of the school social hierarchy. These two opposites cross paths when Miyagi, on a sudden whim, offers to pay Sendai 5,000 yen once a week in exchange for the right to order her around. For six months, they share a secret room, playing video games, feeding each other snacks, and executing occasionally risky commands. Insisting 'we are not friends,' they use the money as a thin shield to hide their growing emotional dependence. As the seasons change, their twisted master-servant dynamic slowly morphs into an irreplaceable, suffocating obsession. A poignant and lingering high school Yuri drama.", amz: "https://amzn.to/4eRhf3g" },
        { n:30, t: "上伊那ぼたん、酔へる姿は百合の花", en_t: "Kamiina Botan, Her Drunken Face Is a Lily Flower", a: "塀", en_a: "Hei", d: "二十歳になったばかりの女子大学生・上伊那ぼたん。普段は大人しくてちょっぴり人見知りな彼女だが、お酒が入ると一変、とろけるような笑顔を見せたり、思わずドキッとするような大胆な言葉を口にしたり……。同じ大学に通う友人や周囲の女性たちを、その無自覚な「酔い姿」で次々と翻弄し、魅了していく。様々なお酒や美味しいおつまみの描写と共に、お酒の席だからこそ縮まる女の子同士の絶妙な距離感を優しく、そして色っぽく描いた、令和の“読むアルコール”日常百合コメディ。", en_d: "Botan Kamiina is a 20-year-old college student who has just reached the legal drinking age. While she is usually quiet and a bit shy, a single drink transforms her entirely, bringing out a melting smile and surprisingly bold, heart-fluttering remarks. Through her blissfully uninhibited and intoxicating 'drunken state,' she effortlessly charms and flusters the women around her. Packed with delightful depictions of various alcoholic beverages and delicious pairings, this cozy yet deeply alluring modern Yuri comedy beautifully captures the intimate, subtle distances between girls over a drink.", amz: "https://amzn.to/4h3RPAM" },
      ]
    },

    {
      cat: "💼 社会人・生活の連帯", 
      en_cat: "💼Adult Life & Solidarity",
      desc: "自由を手にしたはずの大人の女性たちが直面する、ままならない現実。仕事、結婚、社会的役割の中で、独りでは抱えきれない孤独や不安を、パートナーとの連帯によって乗り越えていく姿を描きます。生活の匂いがするリアリティと、成熟した魂の結びつきを重視したラインナップです。",
      en_desc: "The inconvenient reality faced by adult women who are supposed to have gained freedom. It depicts how they overcome loneliness and anxiety that they cannot handle alone in their work, marriage, and social roles through solidarity with their partners. This lineup emphasizes reality with the scent of daily life and the connection of mature souls.",
      works: [
        { n:31, t:"作りたい女と食べたい女", en_t:"She Loves to Cook and She Loves to Eat", a:"ゆざきさゆ", en_a:"Sakaomi Yuzaki", d:"料理を巡る日常から連帯を深める二人。現代社会の救済を描く。", en_d:"Two women deepening their bond through cooking and eating.", amz:"https://amzn.to/42PwlPT", },
        { n:32, t:"彩香ちゃんは弘子先輩に恋してる", en_t:"Ayaka is in Love with Hiroko", a:"Sal Jiang", en_a:"Sal Jiang", d:"愛が重い後輩と臆病な先輩。オフィス舞台の全力ラブストーリー。", en_d:"An office love story between an intense junior and a shy senior.", amz:"https://amzn.to/4d8QjtR", },
        { n:33, t:"私の百合はお仕事です！", en_t:"Yuri Is My Job!", a:"未幡", en_a:"Miman", d:"コンセプトカフェで演じられる「理想の百合」。本音が交錯する。", en_d:"Idealized 'Yuri' performed at a concept cafe.", amz:"https://amzn.to/4eLFr79", },
        { n:34, t:"おとなになっても", en_t:"Even Though We're Adults", a:"志村貴子", en_a:"Takako Shimura", d:"ままならない大人の愛。実存的な問いかけを放つ。", en_d:"A story about the complex and difficult love of adults.", amz:"https://amzn.to/4eqkEpW", },
        { n:35, t:"明るい記憶喪失", en_t:"Cheerful Amnesia", a:"奥たまむし", en_a:"Oki Tamamushi", d:"記憶を失っても、再び出会えばまた恋に落ちる。", en_d:"Even with memory loss, she falls in love with her partner again.", amz:"https://amzn.to/42ULGi4", },
        { n:36, t:"Still Sick", en_t:"Still Sick", a:"あかしたけまる", en_a:"Akashi Takemaru", d:"職場での有能さと密かな同人活動。自己肯定と絆の物語。", en_d:"A story of self-acceptance and bonds in the workplace.", amz:"https://amzn.to/4cUZ1wP", },
        { n:37, t:"2DK、Gペン、目覚まし時計。", en_t:"2DK, G-pen, Alarm Clock", a:"大沢やよい", en_a:"Yayoi Osawa", d:"漫画家と社畜OL。正反対の価値観が支え合う生活。", en_d:"A manga artist and an office worker living together.", amz:"https://amzn.to/3P5NfGQ", },
        { n:38, t:"メタモルフォーゼの縁側", en_t:"BL Metamorphosis", a:"鶴谷香央理", en_a:"Kaori Tsurutani", d:"BLを通じて心を通わせる75歳と17歳。魂の共鳴。", en_d:"A 75-year-old and a 17-year-old bonding over BL manga.", amz:"https://amzn.to/4tWIs9F", },
        { n:39, t:"ふたりエスケープ", en_t:"Futari Escape", a:"田口囁一", en_a:"Shoichi Taguchi", d:"現実逃避が得意な二人。今を楽しむ空気感の物語。", en_d:"Two women who are experts at escaping reality.", amz:"https://amzn.to/4wbd6xT", },
        { n:40, t:"君と綴るうたかた", en_t:"The Summer You Were There", a:"Yuama", en_a:"Yuama", d:"ひと夏の「偽りの恋」から始まる、切なくも美しい救済。", en_d:"A poignant story of salvation starting from a 'fake' summer romance.", amz:"https://amzn.to/4exfBUP", }
      ]
    },
    {
      cat: "💼 社会人・生活の連帯（つづき）", 
      en_cat: "💼Adult Life & Solidarity (Continued)",
      desc: "成熟した大人の女性たちが紡ぐ、日々の生活の機微と深まる絆。職場の人間関係、キャリアの葛藤、日常のささやかな休息の中で、互いが唯一無二の理解者となっていくプロセスを、多角的な視点から描いた珠玉の作品群です。",
      en_desc: "The subtleties of daily life and deepening bonds woven by mature, adult women. This is a collection of gem-like works depicting the process of becoming each other's one and only understander amid workplace relationships, career struggles, and small daily respites.",
      works: [

        { n:41, t:"海猫荘days", en_t:"Sea Gull Villa Days", a:"コダマナオコ", en_a:"Naoko Kodama", d:"都会から移住してきた教師の少女と、地元の女性たちが織りなす地方学園の人間模様。", en_d:"The human drama of a female teacher who relocated from the city and the local women near a coastal town.", amz:"https://amzn.to/3x8LMNo" },
        { n:42, t: "いばら姫とおやすみ。", en_t: "Sleeping Beauty and Good Night", a: "深水紅茶 (著), 椎名 くろ (イラスト)", en_a: "Kocha Fukami (Author), Kuro Shiina (Illustrator)", d: "社会人3年目のデザイナー・時雨は、通勤電車で重度の不眠症を抱える女子高生・いばらと出会う。時雨の隣なら眠れると確信したいばらは、必死の思いで「お金を払うから一緒に寝てほしい」と懇願。困惑しつつも放っておけない時雨は一晩だけの添い寝を受け入れるが――。孤独な夜に寄り添い合う、救済と秘密のガールミーツガール。", en_d: "Shigure, a third-year office designer, meets Ibarahime, a high school girl suffering from severe insomnia, on a commuter train. Convinced she can only sleep next to Shigure, Ibarahime desperately begs to rent her time for co-sleeping. Unable to turn away someone in deep distress, Shigure agrees to a single night, beginning a gentle girl-meets-girl story of shared solace and hidden secrets.",  amz: "https://amzn.to/4wsDCBZ" },
        { n:43, t: "性別不明な中性僕っ子とお姉さん", en_t: "The Gender-Neutral Short-Haired 'Bokukko' and the Older Sister", a: "つみきつき", en_a: "Tsukitsuki", d: "26歳の会社員・ひなこさんは、ずっと男の子だと思っていた近所の子供・一葵（いつき）ちゃんが女の子かもしれないと知り大混乱。一葵ちゃんの何気ない仕草や格好よさにドキドキさせられる毎日。しかし実は、一葵ちゃんのほうもひなこさんへの片想いを募らせていて……。中性僕っ子に翻弄されるフルカラー・オフィス＆日常ラブコメ。", en_d: "Hinako, a 26-year-old office worker, is thrown into utter confusion upon realizing that Itsuki, the neighboring kid she always thought was a boy, might actually be a girl. While Hinako finds her heart racing over Itsuki's casually cool behavior every day, Itsuki is secretly harboring a massive, heart-pounding crush on her. A full-color romantic comedy about a charmingly ambiguous girl and a flustered older sister.", amz: "https://amzn.to/4vh9gl0" },
        { n:44, t: "アフタヌーンティーはいかがですか？ 私と先輩の、不純で一途なふたり暮らし", en_t: "Would You Care for Afternoon Tea? My Co-living Life of Impure and Earnest Love with Senpai", a: "桃田 ロウ (著), 塩こうじ (イラスト)", en_a: "Rou Momota (Author), Shiokouji (Illustrator)", d: "女たらしと有名な大学の先輩であり、意地悪な同居人でもある一ノ瀬結衣。「恋愛対象外」だと告げられた主人公の結衣（ゆい）は、先輩が誰とどんな夜を過ごそうと関係ないと思い込もうとするが、一つ屋根の下で暮らすうちに執着と嫉妬が狂おしく交錯していく。嘘と本音、ままならない独占欲が渦巻く、不純で一途な女子大生ふたり暮らしストーリー。", en_d: "Ichinose Yui is a notorious female philanderer at university, as well as a teasing, deceptive roommate. Having been explicitly told that she is 'outside the romantic loop,' the protagonist tries to remain indifferent to who Yui spends her nights with. However, living under the same roof causes agonizing attachment and jealousy to intertwine. A bittersweet college-life Yuri story about impure yet earnest devotion.", amz: "https://amzn.to/3R3TSKB" },
        { n:45, t: "どタイプお姉さんの誘惑が止まらないっ！ ちっちゃい頃から私のことがだいすきな年下従妹のお嫁さんになっちゃいました！？", en_t: "My Perfect Type Big Sister's Temptation Won't Stop! I Became the Wife of My Younger Cousin Who Loved Me Since She Was Little?!", a: "御園 海音 (著), けけもつ (イラスト)", en_a: "Amane Misono (Author), Kekemotsu (Illustrator)", d: "幼い従妹を庇った事故で昏睡状態に陥った女子高生・音瀬小絃が目覚めると、そこはなんと10年後の世界。かつてちっちゃかった従妹は、自分好みの大人の女性へと完璧に成長し、目覚めた小絃に「お嫁さん」としてぐいぐい熱烈なアプローチを仕掛けてくる。10年の空白を飛び越えて始まる、刺激的な誘惑に理性が揺さぶられっぱなしの同居ラブコメディ。", en_d: "High school girl Koto Otose falls into a coma after an accident while protecting her young cousin. When she finally wakes up, she finds herself 10 years in the future! Her once-little cousin has grown into a stunning adult woman who happens to be Koto's exact type—and she wastes no time aggressively making Koto her 'wife.' A heart-pounding cohabitation romantic comedy that leaps across a 10-year gap.", amz: "https://amzn.to/3RqG2Ch" },
        { n:46, t: "限界社会人さんを救えるのはクソデカ感情ストーカーちゃんだけでした", en_t: "The Only One Who Could Save a Burned-Out Office Worker Was a Stalker Girl with Giant Emotions", a: "ちさこ", en_a: "Chisako", d: "残業と仕事詰めの地獄のような社会人生活を送り、「無理…限界…死ぬ…」と身も心もすり減らしていた山田花。そんな彼女を突如拉致し、「あなたを監禁します」と告げたのは、凄まじく重い愛（クソデカ感情）を抱えた見知らぬストーカーの美女だった！？ 豪邸、豪華な食事、露天風呂など、至れり尽くせりの環境で、心優しき（？）ストーカーに甘やかされまくる天国のような歪で温かい監禁生活コメディ。", en_d: "Hana Yamada is living a hellish, exhausted life under severe overwork and on the brink of collapse. Her savior arrives in the form of a stunning, mysterious stalker girl driven by massive, overwhelming emotions, who suddenly kidnaps her and declares a 'confinement.' What follows is a paradoxical paradise inside a luxurious mansion with fine dining and open-air baths, where a burned-out adult is thoroughly spoiled in a twisted yet heartwarming domestic comedy.", amz: "https://amzn.to/4pauGPt" },
        { n:47, t: "担当アイドルの熱愛がバレたけど、ノーダメだよね!(※お相手は男装したマネージャーの私だし)", en_t: "My Assigned Idol's Romance Was Leaked, But It's Zero Damage! (Since Her Partner Is Me, the Cross-Dressing Manager)", a: "最宮 みはや (著), 緋月 ひぐれ (イラスト)", en_a: "Mihaya Saimiya (Author), Higure Hizuki (Illustrator)", d: "超人気アイドル・星原奏歌のマネージャーとなった女子大生の早瀬理月。最初は奏歌から舌打ちされるなど最悪の態度をとられていたが、ある日「好みの男性アイドルを紹介しろ」と迫られる。しかし、そのお相手はかつて理月が男装アイドルをしていた頃の『自分自身』だった。男装を隠して上手く懐に入ろうと画策する理月だったが、思惑は外れて速攻で正体がバレてしまい、立場が逆転。「これからは私の言うことに絶対服従」と迫られる、ワガママな最推しアイドルと元男装マネージャーによる、ハラハラドキドキの秘密共有ガールズラブコメディ。", en_d: "Ritsuki Hayase, a university student who becomes the manager of super-popular idol Kanaka Hoshihara, initially faces harsh treatment and tongue-clicking from her client. Things take a bizarre turn when Kanaka demands an introduction to her male idol crush—who is actually Ritsuki herself from her past days as a cross-dressing idol. Hoping to leverage this to control her demanding client, Ritsuki attempts to smooth things over while concealing the truth, only to be immediately exposed. With the tables completely turned and Kanaka declaring absolute obedience from her manager, a high-stakes, thrilling secret-sharing romantic comedy begins.", amz: "https://amzn.to/4f7Y5VN" },
        { n:48, t: "新しくできたお姉さんは、百合というのが好きみたい", en_t: "My New Big Sister Seems to Like Something Called Yuri", a: "アサクラ ネル (著), かがちさく (イラスト)", en_a: "Neru Asakura (Author), Saku Kagachi (Illustrator)", d: "親の再婚により突然義理の姉妹となった、仕事を辞めて実家暮らし中のおっとりした妹・春夏（はるか）と、仕事一筋でクールな姉・沙織（さおり）。沙織からの提案で始まった二人きりの同居生活を通じて次第に距離が縮まっていく二人だったが、実は沙織には「大の百合好き（ガチのレズビアン）」であり、春夏に一目惚れしているという絶対に言えない秘密があった。家族としての絆を失う恐怖と、妹への止められない恋心の狭間で悶える、甘く切ない新婚風（？）姉妹ラブコメディ。", en_d: "Due to their parents' sudden remarriage, Haruka, an easygoing girl who quit her job to live at home, and Saori, a cool, career-driven woman, unexpectedly become stepsisters. Prompted by Saori's invitation, they begin sharing an apartment, slowly narrowing the distance between them through domestic life. However, Saori harbors a massive, unspoken secret: she is a lesbian who fell in love with Haruka at first sight. Torn between her longing for a genuine family bond and her growing romantic desires, a sweet and agonizing stepsister romantic comedy unfolds.", amz: "https://amzn.to/3Tnfm5W" },
        { n:49, t: "姉の親友、私の恋人。", en_t: "My Sister's Best Friend, My Lover.", a: "藤松 盟", en_a: "Mei Fujimatsu", d: "小説家の聖奈（せな）は、実の姉・優奈に歪んだ恋愛感情を抱いていた。姉が離れていった喪失感から執筆も生活も破綻してしまった聖奈のもとに、姉の親友であり「姉の元恋人」でもある成人女性・菊（きく）がしつこく世話を焼きに訪ねてくる。菊を苦手だと思いながらも流されていく聖奈だったが、実は菊もまた聖奈に対して複雑な感情を秘めていた。執着と喪失を抱える成人女性二人の、不器用で重厚な人間ドラマ。", en_d: "Sena, a novelist, harbors a repressed, romantic obsession with her own older sister, Yuna. Left unable to write or maintain her daily life due to a profound sense of loss after her sister moves away, Sena is continuously visited by Kiku—an adult woman who is her sister's best friend and 'ex-lover.' Though Sena finds Kiku overbearing, she gradually lets her guard down, unaware that Kiku is masking a complex, hidden emotional baggage regarding Sena herself. A heavy, intricate Yuri drama about trauma and adult attachment.", amz: "https://amzn.to/4vRYyTf" },
        { n:50, t: "VTuberなんだが配信切り忘れたら伝説になってた", en_t: "VTuber Legend: How I Went Viral After Forgetting to Turn Off My Stream", a: "七斗 七 (著), 塩かずのこ (イラスト)", en_a: "Nana To Nana (Author), Shio Kazunoko (Illustrator)", d: "大手VTuber運営会社「ライブオン」の三期生として、表向きは大人しく可憐な『清楚』系として活動していた心音淡雪。しかし、不注意から配信を切り忘れたことで、ストロング缶の酒を煽り、凄まじい熱量で女の子への限界妄想を爆発させるという「酒カス・女好き」の本性が全世界へ筒抜けになってしまう。大炎上を覚悟した翌日、その破天荒なギャップが奇跡的に大ウケしてトレンド世界1位を獲得。開き直ってガチの素顔を解禁した彼女が、個性派だらけのライバルたちを巻き込みながら界隈の頂点へと駆け上がっていく、圧倒的熱量の新感覚VTuberコメディ。", en_d: "Awayuki Kokorone is a VTuber contracted under Live-On, a major agency filled with glittering stars, where she strictly maintains her public persona as a quiet, refined, and wholesome girl. However, a careless mistake leads her to leave her livestream running after her sign-off, broadcasting her true self to the world: a hard-drinking, girl-crazy chaotic mess who cracks open long-cans of alcohol and screams out raw otaku delusions. Expecting her career to be instantly ruined, Awayuki wakes up to find that her wild, unhinged gap-moe has gone massively viral, capturing the number one global trending spot. Embracing her new reality, she discards her fake modesty and charges headfirst into becoming a top-tier streaming legend.", amz: "https://amzn.to/4wu6RUZ" },
    
      ]
  　　},

  {
    cat: "💼 社会人・生活の連帯（つづき）", 
    en_cat: "💼Adult Life & Solidarity (Continued)",
    desc: "一歩進んで、さらに深く。傷を分かち合い、生活を重ねていく大人の女性たちのリアルな息遣い。甘いだけではない、人生の苦楽を共に歩むパートナーたちの特別な距離感を揃えました。",
    en_desc: "Taking a step further and going even deeper. The realistic breath of adult women sharing their wounds and building their lives together. A selection featuring the unique distance of partners who walk together through life's ups and downs, far beyond mere sweetness.",
    works: [

      { n:51, t: "毎月庭つき大家つき", en_t: "Monthly With a Garden and a Landlord", a: "ヨドカワ", en_a: "Yodokawa", d: "長年付き合ったパートナーとの破局に傷心し、気分を一新するために一戸建てに引っ越してきた社会人の須賀アサコ。心機一転、穏やかな新生活が始まるかと思いきや、なんとその物件の屋根裏部屋には、かつて世間を騒がせた元・国民的アイドルの大家お姉さんが勝手に住み込んでいて……！？ 過去に傷を抱えた不器用な成人女性二人が、ひとつ屋根の下でのんびりとした日々と丁寧な食事を共有しながら、ゆっくりと心を寄せ合っていく大人のリスタート百合コミック。", en_d: "Heartbroken and emotionally drained after breaking up with her long-term partner, office worker Asako Suga moves into a cozy detached house to start fresh. However, her plans for a quiet solo life are instantly upended when she discovers that the property's landlord—a former national idol who mysteriously left the spotlight—is secretly living in the attic! Under one roof, two adult women carrying past scars begin to share slow-paced days and home-cooked meals, gently healing and rewriting their futures in a comforting adult Yuri drama.", amz: "https://amzn.to/4pbWUsN" },
      { n:52, t: "わたしの百合も、営業だと思った？", en_t: "Did You Think My Yuri Was Just Business Too?", a: "アサクラ ネル (著), 千種 みのり (イラスト)", en_a: "Neru Asakura (Author), Minori Chigusa (Illustrator)", d: "最推しアイドル・鐘月かりんの卒業を引きずる若手声優の仙宮すずね。そんな彼女の前に、かりんが新人声優として現れる。突然の推しの再供給に激しく動揺しながらも、先輩として一定の距離を保とうとするすずねだったが、かりんはアイドル時代と変わらぬ完璧なルックスでぐいぐいと距離を縮めてくる。ビジネス（百合営業）なのか本気（ガチ）なのか翻弄されるうちに、すずねは彼女を「ひとりの女性」として意識し始めていく。声優業界を舞台に贈る、先輩×後輩のガールズラブコメディ。", en_d: "Suzune Mamiya, a young voice actress, is still mourning the retirement of her absolute favorite idol, Karin Kanetsuki. Out of nowhere, Karin enters Suzune's agency as a rookie voice actress. While Suzune struggles to maintain a professional distance from her idol, Karin aggressively closes the gap between them. Constantly teased and left wondering if it's all just 'business' or genuine affection, Suzune slowly begins to see Karin as an individual woman. A delightful voice-acting industry Yuri romantic comedy between a senior and her junior.", amz: "https://amzn.to/4ydZX7W" },
      { n:53, t: "好きな子のいもうと", en_t: "My Crush's Little Sister", a: "犬甘 あんず (著), 塩こうじ (イラスト)", en_a: "Anzu Inukai (Author), Shiokouji (Illustrator)", d: "初恋の相手である優等生な先輩・花房渚に告白し、振られてしまった雨宮結叶。未練を断ち切れない結叶を見かねて、渚に瓜二つな不真面目の妹・海望（みひろ）が「お姉ちゃんへの想いを忘れさせてあげる」と、渚の代わりになる歪な関係を提案する。姉の格好をした海望とデートを重ね、渚の影を重ねて欲をぶつけ溺れていく結叶だったが、触れ合いを続けるうちに、身代わりではない海望自身の心と存在に次第に惹かれていく。姉妹の間で複雑にもつれる、切なく狂おしい百合三角関係ストーリー。", en_d: "Yuto Amamiya confesses her feelings to her first love, her elegant senior Nagisa Hanafusa, only to be rejected. Unable to move on, Yuto is approached by Nagisa's rebellious younger sister, Mihiro, who looks exactly like Nagisa. Mihiro offers a twisted compromise: 'I'll make you forget about my sister,' inviting Yuto to project her desires onto her. Yuto falls into a deep, drowning dependency—dating Mihiro while she dresses like Nagisa and crossing lines they shouldn't. However, through this physical and emotional intimacy, Yuto gradually finds herself genuinely falling for Mihiro herself, sparking an agonizing love triangle bound by family ties.", amz: "https://amzn.to/4aF9gE6" },
      { n:54, t: "あなたみたいに【連載版】", en_t: "Just Like You", a: "ユニ", en_a: "Yuni", d: "念願のインテリアデザイナーになったものの、思うような成果を出せず自信を喪失していた柑奈（かんな）。精神的に追い詰められる中で、偶然にも理想を体現したような大人の女性・弥生（やよい）と出会う。優しく寄り添う弥生に悩みを打ち明けるうち、惹かれ合うように衝動的なキスを交わし、戸惑いながらもホテルで初めて女性と身体を重ねてしまう。一夜限りの関係と割り切れず激しく思い悩む柑奈だったが、後日、仕事の現場で衝撃の再会を果たすことに――。初めて女性に恋をした戸惑いと溺愛を描く、大人のオフィス百合ロマンス。", en_d: "Kanna achieved her dream of becoming an interior designer, but failing to deliver results has left her deeply anxious and ready to quit. In the midst of her despair, she crosses paths with Yayoi, a mature woman who embodies everything Kanna aspires to be. Opening up about her insecurities, the two grow closer until they share an impulsive kiss. Though Kanna has never loved a woman before, she cannot resist Yayoi's charm and spends an intimate night with her. Unable to brush it off as a mere one-night stand, Kanna finds her heart in turmoil—only to unexpectedly encounter Yayoi again through her work. A passionate adult workplace Yuri romance about a woman experiencing her first same-sex love.", amz: "https://amzn.to/4guVQyc" },
      { n:55, t: "この恋を星には願わない 1【電子限定特典付き】", en_t: "I Won't Ask the Stars for This Love", a: "紫のあ", en_a: "Noa Murasaki", d: "幼い頃からずっと同じ時間を共有し、固い絆で結ばれてきた幼馴染の三人組、冬葵（ふゆき）、瑛莉（えり）、京（みやこ）。何気ない友達としての関係を穏やかに続けてきた彼らだったが、冬葵は密かに、瑛莉に対して友情以上の切ない恋心を抱き続けていた。そんな中、久しぶりに三人で出かけた遊園地での出来事をきっかけに、冬葵は自分の秘めた恋が決して叶うことのないものであるという残酷な現実を悟ってしまい――。それぞれの「好き」という想いが複雑に交錯する、美しくもどこか淡く切ない、少女たちの青春群像百合ラブストーリー。", en_d: "Fuyuki, Eri, and Miyako are a trio of childhood friends who have spent almost every moment together since they were young, bound by an unbreakable platonic bond. However, underneath their peaceful everyday routine, Fuyuki secretly harbors a deep, aching romantic affection for Eri that goes far beyond mere friendship. One day, during a long-awaited trip to an amusement park, a sudden revelation forces Fuyuki to realize that her hidden love is destined to remain unrequited. Exploring the delicate, complicated tangles of silent longing, this beautifully melancholic school youth Yuri drama follows girls trapped in a web of intersecting feelings.", amz: "https://amzn.to/4fnpLHr" },
    ]
  } ,

    {
      cat: "✨ 異世界・幻想の叙事詩", 
      en_cat: "✨Fantasy & Epic Narratives",
      desc: "魔法、剣、そして過酷な運命が支配する非日常の世界。壮大な設定の中だからこそ、剥き出しになる絆の本質があります。時に命を懸け、時に世界の理を塗り替えながら、最愛の人のために戦う女性たちの高潔な姿を追います。現実を超越した美しさを求める方に。",
      en_desc: "A world of extraordinary circumstances governed by magic, swords, and harsh fates. Because it is within a grand setting, the essence of the bond is exposed. We follow the noble figures of women fighting for their beloved ones, sometimes risking their lives and sometimes rewriting the laws of the world. For those seeking beauty that transcends reality.",
      works: [
        { n:56, t:"転生王女と天才令嬢の魔法革命", en_t:"The Magical Revolution", a:"南高春 / 鴉ぴえろ", en_a:"Haru Minamoto / Piero Karasu", d:"魔学と魔法で世界の理を塗り替えていく革命劇。", en_d:"A revolution rewriting the world's laws with magic.", amz:"https://amzn.to/3QYdhMI", },
        { n:57, t:"私の推しは悪役令嬢。", en_t:"I'm in Love with the Villainess", a:"青乃下 / いのり。", en_a:"Aonoshita / Inori.", d:"推しの「悪役令嬢」に全霊の愛を捧げる転生記。", en_d:"Devoting entire love to her favorite villainess.", amz:"https://amzn.to/4neL0O1",},
        { n:58, t:"裏世界ピクニック", en_t:"Otherside Picnic", a:"水野英多 / 宮澤伊織", en_a:"Eita Mizuno / Iori Miyazawa", d:"怪異が実在する「裏世界」を探索する濃密なバディ。", en_d:"An intense buddy story exploring the dangerous 'Otherside'.", amz:"https://amzn.to/4daZkm3", },
        { n:59, t:"機動戦士ガンダム 水星の魔女", en_t:"The Witch from Mercury", a:"サンライズ", en_a:"Sunrise", d:"「花婿」として「花嫁」を救うために戦う革新的百合。", en_d:"An innovative Yuri story set in the Gundam universe.", amz:"https://amzn.to/42lRl0s",},
        { n:60, t:"少女終末旅行", en_t:"Girls' Last Tour", a:"つくみず", en_a:"Tsukumizu", d:"文明が滅びゆく世界で寄り添い、移動し続ける二人。", en_d:"Two girls traveling through a dying civilization.", amz:"https://amzn.to/3P2dEFx",},
        { n:61, t:"処刑少女の生きる道", en_t:"The Executioner and Her Way of Life", a:"三ツ谷亮 / 佐藤真登", en_a:"Ryo Mitsuya / Mato Sato", d:"殺意から本物の絆へ。過酷な運命を辿る旅。", en_d:"A journey from murderous intent to true bonds.", amz:"https://amzn.to/4neO2BP", },
        { n:62, t:"魔女の旅々", en_t:"Wandering Witch", a:"七緒一綺 / 白石定規", en_a:"Itsuki Nanao / Jougi Shiraishi", d:"魔女イレイナの出会いと別れを綴る幻想オムニバス。", en_d:"The fantastical encounters and partings of Elaina.", amz:"https://amzn.to/3Rptpa6", },
        { n:63, t:"魔法少女まどか☆マギカ", en_t:"Puella Magi Madoka Magica", a:"Magica Quartet", en_a:"Magica Quartet", d:"絶望と奇跡。究極の献身と愛が胸を打つ。", en_d:"Despair and miracles. Ultimate devotion and love.", amz:"https://amzn.to/4ezg3lu",},
        { n:64, t:"ひきこまり吸血姫の悶々", en_t:"The Vexations of a Shut-In Vampire Princess", a:"オリ口 / 小林湖底", en_a:"Origuchi / Kotei Kobayashi", d:"吸血鬼令嬢と部下たちが織りなす熱いドラマ。", en_d:"A hot drama of a vampire princess and her subordinates.", amz:"https://amzn.to/4dsvKK2",},
        { n:65, t: "猫ノ山寧々子はネコになる", en_t: "Neneko Nekonoyama Turns Into a Cat", a: "ひのはら (著), ミト (イラスト)",  en_a: "Hinohara (Author), Mito (Illustrator)", d: "猫になれる亜人の女子高生・寧々子は、人見知りで臆病な性格。唯一心を許せる姉の友人・ましろに憧れを募らせていたが、ある日彼女が吸血鬼であることを知る。寧々子は彼女の血液提供者（パートナー）として同棲を提案し――。恋に不器用な少女たちのピュアラブストーリー。", en_d: "Neneko, a shy high school girl who can transform into a cat, harbors a deep admiration for Mashiro, her older sister's mysterious friend. Upon discovering that Mashiro is actually a vampire, Neneko proposes moving in together as her blood donor and partner. A pure love story of two girls clumsy in romance.", amz: "https://amzn.to/4bdnuvZ" },
    
      ]
    },

    {
      cat: "✨ 異世界・幻想の叙事詩（つづき）", 
      en_cat: "✨Fantasy & Epic Narratives (Continued)",
      desc: "異なる種族、主従の誓い、あるいは悪役令嬢としての逆転劇。過酷で美しい異世界だからこそ、彼女たちの愛と執着はより気高く、深く燃え上がります。運命の鎖を解き放つ、新たな幻想譚の数々。",
      en_desc: "Different races, oaths of master and servant, or dramatic turnarounds as a villainess. Precisely because they are in a harsh and beautiful fantasy world, their love and obsession burn with greater nobility and depth. A new collection of fantasy tales that unshackle the chains of fate.",
      works: [
        { n:66, t:"リコリス・リコイル", en_t:"Lycoris Recoil", a:"A-1 Pictures", en_a:"A-1 Pictures", d:"対照的な二人の少女エージェントが織りなす、過激な日常と強固な絆。【アニメ版】", en_d:"An intense daily life and powerful bond between two contrasting young female secret agents. [Anime]", amz:"https://amzn.to/3T4EZIF" },
        { n:67, t: "狼の皮をかぶった羊姫", en_t: "The Princess Sheep in Wolf's Clothing", a: "ミト", en_a: "Mito", d: "肉食獣の「狼」でありながら、平和な羊の国で物静かな執事として働く六条（ろくじょう）アキ。穏やかな暮らしを気に入っていた彼女だったが、ひょんなことから羊の国の第三王女であるモモ＝シウダーファレスに深く気に入られ、彼女の専属家庭教師に指名されてしまう。純真無垢で天真爛漫、けれど時折大胆な表情を見せるお姫様と、彼女に振り回されつつも惹かれていく狼執事。ケモ耳の少女たちが織りなす、主従関係の甘く愛らしい異世界ガールズラブファンタジー。", en_d: "Aki Rokujo, a wolf who belongs to a predatory race, lives a quiet and peaceful life working as a butler in the Kingdom of Sheep. While she thoroughly enjoys her calm days, she unexpectedly catches the eye of Momo Ciudadjuarez, the third princess of the realm, and finds herself appointed as her personal tutor. Follow the adorable daily life of the innocent yet surprisingly bold sheep princess and her loyal, easily flustered wolf butler. A charming and sweet master-servant beast-ear Yuri fantasy.", amz: "https://amzn.to/4gon5KG" },
        { n:68, t: "竜人ボディガードとお嬢様", en_t: "The Dragonoid Bodyguard and the Young Lady", a: "ふぁゆ瀬", en_a: "Fayuse", d: "密乃宝石商の一人娘・煌（きら）と、彼女を幼い頃から護り続けている竜人族のボディガード・天（てん）。かつては泣き虫だった煌だが、「天ちゃんにふさわしい主人になる」と一念発起し、交渉から採掘、溶接までこなす超アクティブな“パワー系お嬢様”へと大成長を遂げる。長命種ゆえに昔と変わらぬ姿で、時に暴走する煌をクールに見守る天。愛が重すぎるお嬢様と、彼女に過保護な竜人従者。主従でありながら時に護り護られる立場が逆転する、宝石のように強く輝く異種族百合ラブコメディ。", en_d: "Kira, the only daughter of the prominent Mitsuno jewelry merchants, has been protected since childhood by Ten, a cool-headed bodyguard from the dragonoid race. Once a helpless crybaby, Kira determined to become a master worthy of Ten, growing into a hyper-active 'power-type' young lady who can handle everything from business negotiations to mining and welding. As a long-lived species, Ten remains physically unchanged, quietly watching over her beloved mistress's wild antics. With a heavily devoted lady and a fiercely protective dragonoid servant, this sparkling interspecies Yuri comedy beautifully explores a shifting bond where the roles of protector and protected frequently flip.", amz: "https://amzn.to/4aHmgsJ" },
        { n:69, t: "限界OLさんは悪役令嬢さまに仕えたい【電子単行本】", en_t: "The Overworked Office Lady Wants to Serve the Villainess", a: "ネコ太郎", en_a: "Nekotaro", d: "理不尽な派遣切りに遭い、心身ともに疲れ果てていたOLの名鳥翠（なとり みどり）。絶望に暮れる彼女は、プレイ中だったノベルゲームの世界へ突然召喚されてしまう。しかも彼女を呼び出したのは、ゲーム内で数々の悪行を働き、破滅を迎えるはずの残虐非道な悪役令嬢ラピス・テネブラエだった。絶体絶命の状況下、翠はゲームの知識を駆使した「予知能力」でラピスの危機を救う。それを機にラピスに気に入られた翠は、彼女の専属秘書として雇われることになり……。悪役令嬢を幸せにするために全力で仕える、主従異世界百合ファンタジー。", en_d: "Midori Natori, a hard-working temporary office worker, hits rock bottom when she is suddenly and unfairly laid off. In the depths of her despair, she is accidentally summoned into the world of her favorite visual novel game. To her horror, her summoner is none other than Lapis Tenebrae—the notoriously cruel villainess destined for a tragic end. Facing execution, Midori uses her extensive knowledge of the game as 'prophecy' to save Lapis from an impending crisis. Deeply intrigued, Lapis appoints Midori as her personal secretary. Bound to save her beloved villainess from her dark fate, the dedicated ex-OL begins her new life in an enchanting master-servant Yuri fantasy.", amz: "https://amzn.to/4feVjya" },
        { n:70, t: "嫌われ魔女令嬢と男装皇子の婚約", en_t: "The Engagement of the Hated Witch Daughter and the Cross-Dressing Prince", a: "散葉 ちんみ", en_a: "Chinmi Chiriba", d: "闇魔法の才能を持って生まれたがゆえに「魔女」と蔑まれ、家族からも街の人々からも迫害されてきたヴラッドリー家の末娘・イヴリス。挙句の果てに婚約者からも無慈悲に婚約破棄を突きつけられ、絶望のどん底にいた彼女の前に、隣国の麗しき男装皇太子・アルベルトが突如現れて求婚する。貴族の同性婚はあり得ないと激しく戸惑い拒絶しようとするイヴリスだったが、アルベルト（実は女性）からの距離感ゼロの猛烈な溺愛とアプローチに翻弄されていき……！？ 不遇な魔女令嬢とイケメン男装皇太子（♀）が織りなす、王宮主従ドタバタ異世界百合ラブコメディ。", en_d: "Born with a rare talent for dark magic, Yvelise, the youngest daughter of the Vladley family, has been shunned as a 'witch' and persecuted by her family and townsfolk alike. Dropped into the depths of despair after her fiancé callously calls off their engagement, an unexpected savior appears: Albert, the breathtakingly handsome prince from a neighboring empire, who suddenly proposes to her! Although Yvelise deeply opposes same-sex noble marriages and tries to reject the offer, she finds herself completely overwhelmed by the doting, fiercely aggressive affection from the charming, cross-dressing prince (who is secretly a woman). A high-energy, royal fantasy Yuri rom-com.", amz: "https://amzn.to/3QO9fXI" },
      ]
    } ,
    {
      cat: "🏆 定番・美学の原点", 
      en_cat: "🏆The Origin of Classic Aesthetics",
      desc: "「百合」という文化が積み上げてきた歴史の中で、決して外すことのできない金字塔。厳格な寄宿学校の伝統、変革を求める革命、そして様式美。これらの作品は、後世のクリエイターに多大な影響を与え続けています。ジャンルの根幹を知るための、避けては通れない名作群です。",
      en_desc: "A monumental achievement that can never be removed from the history of Yuri culture. Traditions of strict boarding schools, revolutions seeking change, and stylistic beauty. These works continue to exert a tremendous influence on creators of later generations. A group of masterpieces that cannot be avoided in order to know the roots of the genre.",
      works: [
        { n:71, t:"マリア様がみてる", en_t:"Maria Watches Over Us", a:"長沢智 / 今野緒雪", en_a:"Satoru Nagasawa / Oyuki Konno", d:"精神的高潔さ。百合の様式美を完成させた聖典。", en_d:"The scripture that perfected the aesthetic of Yuri.", amz:"https://amzn.to/3OPubwx",  },
        { n:72, t:"少女革命ウテナ", en_t:"Revolutionary Girl Utena", a:"さいとうちほ / 幾原邦彦", en_a:"Chiho Saito / Kunihiko Ikuhara", d:"少女たちの自立と解放を圧倒的ビジュアルで描く。", en_d:"Depicting girls' independence and liberation.", amz:"https://amzn.to/4f7T4Oo", },
        { n:73, t:"ストロベリー・パニック", en_t:"Strawberry Panic", a:"たくみなむち / 公野櫻子", en_a:"Namuchi Takumi / Sakurako Kimino", d:"耽美な愛憎劇。かつてのブームの中核作。", en_d:"An aesthetic drama of love and hatred.", amz:"https://amzn.to/4dvW5H2", },
        { n:74, t:"ささめきこと", en_t:"Sasameki Koto", a:"いけだたかし", en_a:"Takashi Ikeda", d:"自身の指向に悩む「等身大」の葛藤を描いた金字塔。", en_d:"A landmark story about struggling with one's identity.", amz:"https://amzn.to/4tYWhon", },
        { n:75, t:"あの娘にキスと白百合を", en_t:"A Kiss and a White Lily for Her", a:"缶乃", en_a:"Canno", d:"多様な「百合の形」を網羅した入門に最適な一作。", en_d:"A great entry point covering various forms of Yuri.", amz:"https://amzn.to/4nb78Zu",},
        { n:76, t:"神無月の巫女", en_t:"Kannazuki no Miko", a:"介錯", en_a:"Kaishaku", d:"輪廻の運命、激情の結末。多大な影響を与えた名作。", en_d:"A classic that influenced the genre with its tragic end.", amz:"https://amzn.to/4tXlr6v", },
        { n:77, t:"飴色紅茶館歓談", en_t:"Chatting at the Amber Tea House", a:"藤枝雅", en_a:"Miyabi Fujieda", d:"安らぎと癒やしの側面を体現した心地よい物語。", en_d:"A cozy story embodying peace and healing.", amz:"https://amzn.to/4d5NARK",},
        { n:78, t:"フラグタイム", en_t:"Fragtime", a:"さと", en_a:"Sato", d:"3分間だけ時間を止められる少女。不器用な恋。", en_d:"A girl who can stop time for three minutes.", amz:"https://amzn.to/42nBlet", },
        { n:79, t:"ハッピーシュガーライフ", en_t:"Happy Sugar Life", a:"鍵空とみやき", en_a:"Tomiyaki Kagisora", d:"純愛か狂気か。一途すぎる少女の衝撃の愛。", en_d:"Is it pure love or madness? A shocking story of devotion.", amz:"https://amzn.to/4wfqxwH", },
        { n:80, t:"加瀬さん。シリーズ", en_t:"Kase-san Series", a:"高嶋ひろみ", en_a:"Hiromi Takashima", d:"二人の成長と深まる愛を追い続けるファン必読作。", en_d:"A must-read following the growth of two girls' love.", amz:"https://amzn.to/42kzl6Q", }
      ]
    },
    {
      cat: "📖 文芸・小説の深淵", 
      en_cat: "📖The Depths of Literature & Novels",
      desc: "絵のない言葉だけの世界だからこそ、読者の想像力は無限に広がります。著名な文芸作家たちが綴る、心理の細やかな襞、言葉の端々に宿る情念、そして社会的な障壁との葛藤。深い余韻を残す、大人の読書体験にふさわしい、文学的価値の高い作品を揃えました。",
      en_desc: "Because it is a world of words without pictures, the reader's imagination expands infinitely. We have gathered works of high literary value, written by famous literary authors, that depict the fine folds of psychology, the passions dwelling in every word, and the conflict with social barriers. Suitable for an adult reading experience that leaves a deep resonance.",
      works: [
        { n:81, t:"生のみ生のままで", en_t:"Nama no mi, Nama no mama de", a:"綿矢りさ", en_a:"Risa Wataya", d:"圧倒的な筆致で描かれる、抗えない女同士の愛の衝動。", en_d:"An irresistible impulse of love between women.", amz:"https://amzn.to/3PrV89C",  },
        { n:82, t:"花物語", en_t:"Hana-monogatari", a:"吉屋信子", en_a:"Nobuko Yoshiya", d:"大正時代、百合の歴史の「根」となった純粋な情操の美。", en_d:"Pure emotional beauty from the roots of Yuri history.", amz:"https://amzn.to/49B8abE",  },
        { n:83, t:"独り舞", en_t:"Solo Dance", a:"李琴峰", en_a:"Li Kotomi", d:"性的指向に苦悩し、海を越えた女性の魂の到達点。", en_d:"The destination of a soul struggling with orientation.", amz:"https://amzn.to/4nltYxW", },
        { n:84, t:"彼岸花が咲く島", en_t:"The Island Where the Spider Lily Blooms", a:"李琴峰", en_a:"Li Kotomi", d:"幻想的な設定の中に鋭利なメッセージが光る傑作。", en_d:"A masterpiece with a sharp message in a fantasy setting.", amz:"https://amzn.to/4uDgr7e", },
        { n:85, t:"砂糖菓子の弾丸は撃ちぬけない", en_t:"A Lollypop or a Bullet", a:"桜庭一樹", en_a:"Kazuki Sakuraba", d:"絶望と美しさが同居する、短くも鮮烈な夏。", en_d:"A short but vivid summer where despair and beauty coexist.", amz:"https://amzn.to/4tm0CAQ", },
        { n:86, t:"放課後の図書室", en_t:"After School Library", a:"飛鳥井千砂", en_a:"Chisa Asukai", d:"図書室を舞台に交錯する、静かで濃密な感情の交感。", en_d:"A quiet and dense exchange of emotions in a library.", amz:"https://amzn.to/4tXotrp", },
        { n:87, t:"屋上ミサイル", en_t:"Rooftop Missile", a:"山下貴光", en_a:"Takamitsu Yamashita", d:"青春の苛烈さと、寄り添う二人の連帯を描くミステリ。", en_d:"A mystery depicting youth's harshness and solidarity.", amz:"https://amzn.to/3R7bc0X", },
        { n:88, t:"西の魔女が死んだ", en_t:"The Witch of the West is Dead", a:"梨木香歩", en_a:"Kaho Nashiki", d:"血縁を超えた「女性同士の魂の継承」を描く名作。", en_d:"A masterpiece about the spiritual inheritance of women.", amz:"https://amzn.to/4dfXpN3", },
        { n:89, t:"きらきらひかる", en_t:"Twinkle Twinkle", a:"江國香織", en_a:"Kaori Ekuni", d:"歪な関係性の中に宿る、真実の愛と受容の物語。", en_d:"A story of true love and acceptance in a distorted relation.", amz:"https://amzn.to/3QQG8Tf", },
        { n:90, t: "コールミー・バイ・ノーネーム", en_t: "Call Me by No Name", a: "斜線堂有紀 (著), くわばらたもつ (イラスト)", en_a: "Yuki Shasendo (Author), Tamotsu Kuwabara (Illustrator)", d: "深夜のゴミ捨て場で出会った、美しく奔放で掴みどころのない女・古橋琴葉。彼女の魅力に囚われた世次愛は友達になることを拒まれ、代わりに奇妙な賭けを持ちかけられる。それは、仮初めの『恋人』になり、琴葉が改名する前の『本当の名前』を当てられたら友達になる、というもの。名前を当ててしまえば、この歪で幸福な恋人は終わる――。ぎこちなくも濃密に肌と心を重ね、関係を深めていく二人だったが、隠された名前に秘められた凄絶な過去と呪いが、二人の時間を切なく狂わせていく。俊英・斜線堂有紀が圧倒的筆致で放つ、狂おしいほどの執着と痛切なエロティシズムが炸裂する名前当て百合ミステリーの傑作長編。", en_d: "Protagonist Megumi Yotsugi meets Kotoha Furuhashi, a beautiful, ungraspable, and uninhibited woman at a garbage dump late at night. Intoxicated by her charm, Megumi seeks friendship but is flatly rejected. Instead, Kotoha proposes a bizarre wager: become temporary 'lovers,' and if Megumi can guess Kotoha's 'true name' from before her legal name change, she will grant her wish of friendship. However, guessing the name means ending this fragile, blissful romance. As they physically and emotionally entwine, deepening their dense yet awkward relationship, the horrific past and curse hidden behind the secret name refuse to let their happiness last. A masterfully written Yuri mystery novel layered with frantic obsession and poignant, sharp eroticism.", amz: "https://amzn.to/44qazTJ" },
      ]
    },
    {
      cat: "アンソロジー：秘められた背徳と濃密な短編集", 
      en_cat: "Anthology: Secret Improprieties & Dense Short Stories",
      desc: "『アンソロジー』のタイトルを冠した、一冊で多彩なシチュエーションを堪能できる珠玉の短編集。ちょっぴり大人でエロティックな背徳感、息が詰まるほど濃密な距離感、そして感情の揺らぎを凝縮した、甘く官能的な百合の世界へ誘います。",
      en_desc: "A collection of gems bearing the title 'Anthology,' allowing you to enjoy a variety of situations in a single volume. This category invites you into a sweet, sensual world of Yuri, condensed with slightly mature, erotic immorality, breathtakingly dense physical proximity, and fluctuating emotions.",
      works: [
        { n:91, t: "隣の席が好きな人だった 学生百合アンソロジー", en_t: "The Person Sitting Next to Me Was My Crush: School Yuri Anthology", a: "ネコ太郎 (著), 樫風 (著), 深海 紺 (著), 他", en_a: "Nekotaro, Kashikaze, Kon Fukami, et al.", d: "新学期のクラス替えや席替え。もしも「好きな人と隣の席になれたら――」という、誰もが一度は夢見る青春の甘酸っぱいドキドキと憧れを凝縮した、全編描き下ろしの学生百合アンソロジー。教科書の貸し借り、ふとした瞬間に触れ合う肩、授業中の内緒の視線。期待と不安に胸を膨らませる少女たちの、瑞々しくもちょっぴり甘やかでピュアな恋の情景を、豪華作家陣が多彩なシチュエーションで紡ぐ珠玉の全8編。", en_d: "A brand-new school Yuri anthology centered around a dream everyone has had at least once during a classroom seat change: 'What if the person sitting next to me was my crush?' This collection perfectly captures the bittersweet flustered feelings and nervous excitement of youth through eight specially drawn stories. From sharing textbooks and accidental shoulder brushes to stealing secret glances during class, it explores the fresh, sweet, and pure romantic landscapes of high school girls. Beautifully woven by a luxury lineup of artists.", amz: "https://amzn.to/4vsZtZb" },
        { n:92, t: "泣き顔百合アンソロジー", en_t: "Crying Face Yuri Anthology", a: "緜 (著), 春花 あや (著), ゆでぱん (著), 他", en_a: "Wata (Author), Aya Haruka (Author), Yudepan (Author), et al.", d: "「女の子の泣き顔」という、フェティッシュでちょっぴり歪んだ愛好をテーマに掲げた、全7作完全描き下ろしのコンセプト百合アンソロジー。嬉し涙、悔し涙、あるいは胸が締め付けられるような切ない恋の涙から、情熱のあまり溢れ出る濃密な涙まで。様々なシチュエーションで感情を昂ぶらせ、美しい涙を流す少女たちの姿を気鋭の作家陣がフェティシズムたっぷりに描き出す、背徳的で愛おしい短編集。", en_d: "A conceptual, specially drawn Yuri anthology featuring seven short stories dedicated entirely to the fetishistic and slightly twisted theme of 'girls' crying faces.' From tears of joy and frustration to heart-wrenching tears of unrequited love, and even intense, emotional tears overflowed in moments of passion. This bittersweet and compelling collection captures girls letting their emotions run wild and shedding beautiful tears in a variety of situations, beautifully illustrated with deep fetishism by a talented lineup of artists.", amz: "https://amzn.to/4h3zuDY" },
        { n:93, t: "ワンナイトラブ百合アンソロジー", en_t: "One-Night Stand Yuri Anthology", a: "つづら涼 (著), 川上しをん (著), ヨドカワ (著), 他", en_a: "Ryo Tsuzura, Shion Kawakami, Yodokawa, et al.", d: "女性同士の一夜限りの過ちや情事をテーマに、実力派の豪華作家陣がビターでエロティックな関係性を描き出す、ちょっぴり大人向けのコンセプト百合アンソロジー。お酒の勢い、孤独の穴埋め、あるいはバーや小料理屋での偶然の出会い――。朝が来れば他人へと戻る、あるいは戻るはずだった二人の、火照る肌の温もりと、言葉にならない背徳的な衝動、そして夜の闇に溶けていく濃密な吐息を、様々な人間模様と共に生々しく官能的に切り取った珠玉の全7編。", en_d: "A conceptual, mature Yuri anthology dedicated to the bittersweet, erotic themes of one-night stands and fleeting love affairs between adult women. From coping with loneliness to chance encounters in cozy bars and restaurants, these seven stories explore the intense heat and wordless, heavy impulses of women crossing the line for just one night. Filled with flushed skin, raw sensuality, and the heavy atmosphere of relationships destined to dissolve when morning comes, this luxury lineup of artists masterfully captures the intimate, fleeting geometry of late-night desires.", amz: "https://amzn.to/4vrPSlt" },
        { n:94, t: "お酒のせいにはしませんから 百合×飲酒アンソロジー", en_t: "I Won't Blame It on the Alcohol: Yuri x Drinking Anthology", a: "コミックニュータイプ (編集)", en_a: "Comic Newtype (Editor)", d: "「お酒×百合」をテーマに、お酒の力を借りて縮まる大人の女性たちの距離感を艶やかに描き出す、完全描き下ろしのコンセプト百合アンソロジー。ほんのり色づくほろ酔いの頬、深酒の夜に見せるいつもと違う大胆な一面、そしてアルコールに背中を押されて零れ落ちる秘めていた本音。お酒のせいという言い訳の裏で、大人だからこそ踏み出せなかった一線を越えていく、エロティックでちょっぴりエモい濃密なエピソードを多数収録。豪華執筆陣が紡ぐ、読むほどに身も心もとろけるように酔いしれる珠玉の短編集。", en_d: "A specially drawn, themed Yuri anthology dedicated entirely to the alluring chemistry of 'drinking and adult women.' From the soft flush of being tipsy to the uninhibited, bold behavior brought out by late-night deep drinking, this collection captures the moments when hidden desires slip past a woman's lips under the influence. Shielded by the convenient excuse of alcohol, mature women finally step over the lines they never dared to cross before. Filled with an erotic, deeply emotional, and intoxicating atmosphere, this luxury lineup of artists presents a blissful volume that will leave you completely drunk on love.", amz: "https://amzn.to/44WrmxQ" },
        { n:95, t: "私たちの恋が花開くとき 異世界恋愛百合アンソロジーコミック", en_t: "When Our Love Blooms: Another World Romance Yuri Anthology Comic", a: "鴉ぴえろ (著), ミズユ (著), 池中織奈 (著), 他", en_a: "Piero Karasu, Mizuyu, Orina Ikenaka, et al.", d: "大人気の異世界ライトノベル作家陣の原作を実力派コミカライズ作家たちが美しく描き出す、異世界ファンタジーに特化した恋愛百合アンソロジー。追加課金制の契約彼女、無条件に愛される精霊の愛し子、メイドを困らせる破天荒な聖女、お嬢様と従者の絆、そして結婚という現実の壁に隔てられた愛の結末まで――。魔法や主従関係、貴族社会といった過酷で華やかな非日常の世界だからこそ、より一層瑞々しく、時に濃密に燃え上がる少女たちの気高い純愛と執着を詰め込んだ、読み応え抜群の珠玉の全5編を収録。", en_d: "A specialized fantasy romance Yuri anthology where popular isekai light novel authors and talented manga artists team up to bring mesmerizing tales to life. This volume features five rich stories set in extraordinary worlds: a temporary girlfriend under an add-on payment system, a beloved child of spirits receiving unconditional affection, an eccentric saint flustering her personal maid, a deep bond between a noble lady and her retainer, and the heavy fate of a love separated by political marriage. Within these harsh yet gorgeous settings of magic and strict social hierarchies, the pure love and suffocating obsessions of these noble girls bloom with dazzling brilliance.", amz: "https://amzn.to/3RsHsfy" },
        { n:96, t: "マッチングアプリ百合アンソロジー", en_t: "Matching App Yuri Anthology", a: "吉田 ばな (著), ヨドカワ (著), 秋月 かづ (著), 他", en_a: "Bana Yoshida, Yodokawa, Kazu Akizuki, et al.", d: "「マッチングアプリでの出会い」をテーマに、画面越しの『いいね』から始まる様々な女性同士の恋模様を切り取った、完全描き下ろしのコンセプト百合アンソロジー。偶然アプリで繋がってしまった親友や、普段交わるはずのないギャル、密かに憧れるアイドル、果てはまさかの魔法少女まで――。多種多様なシチュエーションのなか、画面上のプロフィールから現実の対面へと進むステップでのドキドキ感、相手の素顔を知る瞬間の甘酸っぱい高揚感を、総勢7名の豪華作家陣が現代的かつピュアに描き出す、今最もリアルでエモい運命の出会い系短編集。", en_d: "A specially drawn, modern-themed Yuri anthology centered around 'meetings on matching apps,' capturing various romance stories that ignite from a single digital 'Like.' This collection follows girls connecting through a screen: a close friend accidentally matched, a gyaru who would normally live in a different social circle, a secretly admired idol, and even a magical girl! Across seven stories illustrated by a talented lineup of artists, it beautifully captures the heart-fluttering tension of moving from online profiles to face-to-face encounters, and the sweet excitement of discovering each other's true selves in this contemporary, fate-driven short story volume.", amz: "https://amzn.to/4y8UjnD" },
        { n:97, t: "レズ風俗アンソロジー", en_t: "Lesbian Brothel Yuri Anthology", a: "焔 すばる (著), 岩見 樹代子 (著), 他", en_a: "Subaru Homura, Kiyoko Iwami, et al.", d: "「女性専用の風俗店」という究極の癒やしと肉体的快楽の空間を舞台に、欲望と感情が濃密に交錯する瞬間を切り取ったコンセプト百合アンソロジー。日常に疲れ果てて扉を叩いた客と、すべてを優しく包み込むプロのキャスト。あるいは、指名というビジネスの関係の裏側で密かに育まれていく、本気の執着や秘められた独占欲――。お互いの肌の温もりに溺れ、甘く熟した吐息を重ね合わせるエロティックな情事から、傷ついた心が身体の交わりによって解きほぐされていく切なくもエモい救済の物語まで、実力派の豪華作家陣8名がそれぞれの視点で艶やかに描き出す、淫らでどこか愛おしい至高の大人向け短編集。", en_d: "Set in the ultimate space of physical pleasure and emotional healing—a women-only adult service parlor—this themed Yuri anthology captures the deeply intense moments where raw desire and genuine affection intersect. It features exhausted everyday women seeking comfort and the professional escorts who gently embrace them, alongside stories of burning obsessions and hidden possessiveness that quietly develop behind a commercial transaction. From erotic affairs where women drown in the warmth of each other's skin and heavy, passionate sighs, to moving tales of emotional salvation where wounded hearts are unraveled through intimate physical contact, this high-end volume for adult audiences features eight talented artists masterfully delivering an enticing, beautifully decadent experience.", amz: "https://amzn.to/4pcHHb3" },
        { n:98, t: "異世界転生百合アンソロジー", en_t: "Isekai Reincarnation Yuri Anthology", a: "南方 純 (著), 井原 リオ (著), きぃやん (著), 他", en_a: "Jun Minakata, Rio Ihara, Kiyanyan, et al.", d: "「異世界転生・転移」というファンタジーの王道シチュエーションを舞台に、未知の世界へと放り出された少女たちが紡ぐ新たな愛と絆の形を集めた完全描き下ろしのコンセプト百合アンソロジー。目が覚めるとゲームの悪役令嬢になっていた、あるいは魔法が満ちる異世界で特別な聖女として召喚された――。現代の常識が通用しない過酷で華やかな非日常の世界だからこそ、出会った二人の女性の距離感は急速に縮まり、時に運命に抗うための強い執着へと変わっていく。甘く情熱的な主従関係から、ちょっぴりエロティックで官能的な異世界での情事まで、気鋭の豪華作家陣7名がそれぞれの色彩で描き出す、ドラマチックでエモいガールズニューワールドの珠玉の全8編。", en_d: "Set against the classic fantasy backdrop of 'Isekai reincarnation and teleportation,' this specially drawn, themed Yuri anthology captures the fresh forms of love and romance woven by girls thrust into unknown realms. Whether waking up as a notorious video game villainess or being summoned as a revered saint into a world overflowing with magic—these extraordinary, gorgeous settings strip away modern common sense, causing the physical and emotional distance between two women to rapidly close, turning their initial confusion into a fierce obsession to defy fate together. From sweet, passionate master-servant bonds to slightly erotic and sensual late-night encounters in a fantasy land, seven talented artists masterfully present eight dramatic, deeply emotional tales of a dazzling girls' new world.", amz: "https://amzn.to/3SIPMZ7" },
        { n:99, t: "浮気・NTR百合アンソロジー", en_t: "Infidelity & NTR Yuri Anthology", a: "しのぎあさ (著), 森 (著), 遮二無二 (著), 他", en_a: "Asa Shinogi, Mori, Shanimuni, et al.", d: "「浮気」「寝取られ（NTR）」という、背徳感と罪悪感の極致に焦点を当てた、ちょっぴり大人向けのビターで官能的なコンセプト百合アンソロジー。彼氏や夫がいるはずの身でありながら、あるいは大切な親友という一線がありながら、別の女性の甘い誘惑と愛撫に抗えず、泥沼の快楽へと堕ちていく少女たちの焦燥と歪んだ愛情。秘密の共有、罪の意識でさらに火照る肌、そしてお互いを激しく求め合う濃厚なベッドシーンまで――。タブーに踏み込んだからこそ剥き出しになる、生々しくエロティックな独占欲と執着を、実力派の豪華作家陣がエモく艶やかに描き出す珠玉の全6編。", en_d: "A bitter, sensual, and highly mature Yuri anthology pushing the boundaries of taboo by focusing on the raw guilt and thrilling immorality of 'infidelity' and 'Netorare (NTR).' Despite having boyfriends, husbands, or long-time best friends, these women find themselves completely powerless against the sweet seductions and intimate caresses of another woman, gradually drowning in a quagmire of forbidden physical pleasure. Shielded by shared secrets and fueled by a burning consciousness of sin, they clash in intensely dense, erotic bedroom encounters. This provocative collection features six dark, deeply emotional stories illustrated by talented artists who masterfully capture the raw, obsessive possessiveness exposed only when crossing the ultimate line.", amz: "https://amzn.to/3TrVgYd" },
        { n:100, t: "ボーイッシュな彼女に沼ってく！？ 百合アンソロジー", en_t: "Falling Deeply for a Boyish Girl?! Yuri Anthology", a: "あいそえる (著), 石ト悠良 (著), おぎしろ (著), 他", en_a: "Aisoeru, Yura Ishito, Ogishiro, et al.", d: "「ボーイッシュ・ガールクラッシュ」をテーマに、中性的でかっこいい女性に心奪われ、狂おしいほど溺れていく少女たちの恋模様を描いた、完全描き下ろしのコンセプト百合アンソロジー。学校や職場で憧れの的である中性的なあの娘、普段は男前なのにふとした瞬間に女の子らしい顔を見せるギャップ、そして強引にリードされているはずが、いつの間にか熱い吐息を重ねてベッドの中に囲い込まれていく濃密な主導権の逆転劇まで。ドキドキするようなかっこよさと、隠されたお色気、そして狂おしいほどの執着を豪華作家陣が瑞々しくもエロティックに描き出す、身も心も魅了される珠玉の短編集。", en_d: "A specially drawn themed Yuri anthology dedicated to 'boyish and girl-crush' characters, exploring the intoxicating romances of girls who fall hopelessly and deeply in love with cool, androgynous women. Whether it is the handsome, school-wide idol who drops her guard to reveal a surprisingly cute, feminine side, or the thrill of being confidently led only for the dynamic to shift behind closed doors amid heavy, shared breaths—this volume is packed with heart-racing tension. A talented lineup of artists masterfully delivers a rich blend of cool charm, hidden sensuality, and frantic obsession that will leave you completely captivated.", amz: "https://amzn.to/4eSSKTk" },
      ]
    },
  ];
      
