
  const yuri_data = [
    {
      cat: "🏫 学園・青春の情景", en_cat: "🏫Scenes of School & Youth", ko_cat: "🏫 학원·청춘의 풍경",
      desc: "多感な時期を過ごす学校という閉鎖的で聖域のような空間。そこで育まれるのは、単なる友情という言葉では片付けられない、切実で時に残酷なほどの純愛です。少女たちが自己を見つめ、誰かを想うことで変化していく繊細な心の機微を、鮮やかな筆致で描いた作品を選出しました。",
      en_desc: "The closed, sanctuary-like space of school during a sensitive period of life. What is nurtured there is a sincere and sometimes cruelly pure love that cannot be dismissed by the simple word 'friendship.' We have selected works that vividly depict the delicate subtleties of the heart as girls look at themselves and change by thinking of someone else.",
      ko_desc: "다감한 시기를 보내는 학교라는 폐쇄적이고 성역 같은 공간. 그곳에서 싹트는 것은 단순한 우정이라는 단어로 치부할 수 없는, 간절하고 때로는 잔혹할 정도의 순애입니다. 소녀들이 자신을 돌아보고 누군가를 생각하며 변화해 가는 섬세한 감정의 기복을 생생한 필치로 그린 작품들을 엄선했습니다.",
      works: [
        { n: 1, t: "やがて君になる", en_t: "Bloom Into You", ko_t: "이윽고 네가 된다", a: "仲谷鳰", en_a: "Nio Nakatani", ko_a: "나카타니 니오", d: "「人を好きになる」感覚が欠如した少女たちが、本物の愛に手を伸ばす。", en_d: "Girls who lack the feeling of 'falling in love' reach out for real affection.", ko_d: "'누군가를 좋아하는' 감정이 결여된 소녀들이 진정한 사랑에 손을 뻗는다.", amz: "https://amzn.to/471glfF" },
        { n: 2, t: "気になってる人が男じゃなかった", en_t: "The Guy She Was Interested in Wasn't a Guy", ko_t: "관심 있는 애가 남자가 아니었다", a: "新井すみこ", en_a: "Sumiko Arai", ko_a: "아라이 스미코", d: "CDショップで出会ったミステリアスな「彼」。音楽が二人の世界を変える。", en_d: "The mysterious 'guy' she met at a CD shop. Music changes their world.", ko_d: "CD 숍에서 만난 미스터리한 '그녀'. 음악이 두 사람의 세계를 바꾼다.", amz: "https://amzn.to/4cMLcAb" },
        { n: 3, t: "安達としまむら", en_t: "Adachi and Shimamura", ko_t: "아다치와 시마무라", a: "まに（漫画）/ 入間人間", en_a: "Mani / Hitoma Iruma", ko_a: "마니 (만화) / 이루마 히토마", d: "体育館の二階で出会った二人。巨大な執着と、静かな波紋が広がる日常。", en_d: "Two girls meet in the gym loft. Daily life filled with obsession and quiet ripples.", ko_d: "체육관 2층에서 만난 두 사람. 거대한 집착과 조용한 파문이 퍼져나가는 일상.", amz: "https://amzn.to/4isWxsL" },
        { n: 4, t: "ささやくように恋を唄う", en_t: "Whisper Me a Love Song", ko_t: "속삭이듯 사랑을 노래하다", a: "竹嶋えく", en_a: "Eku Takeshima", ko_a: "타케시마 에쿠", d: "「ひとめぼれ」から始まるバンドと恋。透明感溢れる心理描写。", en_d: "A band and love story starting from 'love at first sight'.", ko_d: "'첫눈에 반함'으로 시작되는 밴드와 사랑. 투명감 넘치는 심리 묘사.", amz: "https://amzn.to/4yJKmg4" },
        { n: 5, t: "citrus", en_t: "citrus", ko_t: "시트러스 (citrus)", a: "サブロウタ", en_a: "Saburouta", ko_a: "사부로우타", d: "派手なJKと厳格な生徒会長の義妹。反発しながら惹かれ合うドラマ。", en_d: "A flashy girl and her strict student council president step-sister.", ko_d: "화려한 여고생과 엄격한 학생회장 의자매. 반발하면서도 서로에게 이끌리는 드라마.", amz: "https://amzn.to/4xsXt48" },
        { n: 6, t: "ゆるゆり", en_t: "YuruYuri", ko_t: "유루유리", a: "なもり", en_a: "Namori", ko_a: "나모리", d: "日常コメディの中にある強固なキャラクター間の情愛。", en_d: "A daily comedy depicting the deep affection between characters.", ko_d: "일상 코미디 속에 녹아있는 캐릭터 간의 견고한 애정.", amz: "https://amzn.to/4gVDAOf" },
        { n: 7, t: "青い花", en_t: "Sweet Blue Flowers", ko_t: "푸른 꽃", a: "志村貴子", en_a: "Takako Shimura", ko_a: "시무라 타카코", d: "思春期の揺らぎを文学的に描いた不朽の傑作。", en_d: "A literary masterpiece depicting the tremors of adolescence.", ko_d: "사춘기의 흔들림을 문학적으로 그려낸 불후의 명작.", amz: "https://amzn.to/4yajaXG" },
        { n: 8, t: "はなにあらし", en_t: "Hana ni Arashi", ko_t: "꽃에 바람 (하나에 아라시)", a: "古鉢るか", en_a: "Ruka Kobachi", ko_a: "코바치 루카", d: "「付き合っている」秘密を共有する親友。砂糖をまぶしたような甘い日常。", en_d: "Best friends sharing the secret that they are dating.", ko_d: "'사귀고 있다'는 비밀을 공유하는 절친. 설탕을 뿌린 듯 달콤한 일상.", amz: "https://amzn.to/4gXIbiZ" },
        { n: 9, t: "熱帯魚は雪に焦がれる", en_t: "Tropical Fish Yearns for Snow", ko_t: "열대어는 눈을 동경한다", a: "萩原ダイスケ", en_a: "Daisuke Hagiwara", ko_a: "하기와라 다이스케", d: "水族館部を舞台に、孤独を埋めようとする少女たち。", en_d: "Girls trying to fill their loneliness at the aquarium club.", ko_d: "수족관부를 무대로 고독을 채워가려는 소녀들.", amz: "https://amzn.to/4yajZ2I" },
        { n: 10, t: "女同士とかありえないでしょと言い張る女の子を、百日間で徹底的に落とす百合のお話", en_t: "Hundred Days Yuri", ko_t: "여자끼리는 절대 무리라는 여고생을 100일 동안 철저하게 공략하는 백합 이야기", a: "みかみてれん", en_a: "Teren Mikami", ko_a: "미카미 테렌", d: "ライトノベルならではの熱量の「落とし」劇。", en_d: "An explosive high-energy light novel romance.", ko_d: "라이트 노벨 특유의 열량이 느껴지는 '공략'극.", amz: "https://amzn.to/42lNlgt", rkt: "https://amzn.to/4xUBwvN" }
      ]
    },
    {
      cat: "🏫 学園・青春の情景（つづき）", en_cat: "🏫Scenes of School & Youth (Continued)", ko_cat: "🏫 학원·청춘의 풍경 (계속)",
      desc: "まだまだ終わらない名作たちの系譜。さらに深く、色鮮やかな少女たちの物語を揃えました。",
      en_desc: "The lineage of masterpieces that never ends. Here are more deep and colorful stories of girls.",
      ko_desc: "아직 끝나지 않은 명작들의 계보. 더욱 깊고 다채로운 소녀들의 이야기를 모았습니다.",
      works: [
        { n: 11, t: "私を喰べたい、ひとでなし", en_t: "This Monster Wants to Eat Me", ko_t: "나를 잡아먹고 싶어, 괴물", a: "苗川 采", en_a: "Sai Naekawa", ko_a: "나에카와 사이", d: "海辺の街で孤独を抱えて生きる女子高生・比名子と、彼女を「最高に美味しい状態で喰う」ために近づいた人魚の妖怪・汐莉。凄惨な運命の中で、死を望んでいた少女の心が、奇妙な怪異との交流によって生への執着と強い結びつきへ変容していく、どこか物悲しくも美しいダークファンタジー。", en_d: "Hinako, a high school girl living with deep loneliness in a coastal town, meets Shiori, a mermaid folklore monster who approaches her to eventually devour her. Amidst a bizarre fate and a melancholic atmosphere, the girl's desire for death gradually transforms into a powerful bond and an attachment to life.", ko_d: "바닷가 마을에서 고독을 안고 살아가는 여고생 히나코와, 그녀를 '가장 맛있는 상태로 잡아먹기' 위해 접근한 인어 요괴 시오리. 참혹한 운명 속에서 죽음을 바라던 소녀의 마음이 기묘한 괴이와의 교류를 통해 삶에 대한 집착과 강한 유대로 변해가는, 어딘가 쓸쓸하면서도 아름다운 다크 판타지.", amz: "https://amzn.to/3UQhZ17" },
        { n: 12, t: "どれが恋かがわからない", en_t: "I Don't Know Which One is Love", ko_t: "어느 것이 사랑인지 모르겠어", a: "奥たまむし", en_a: "Tamamushi Oku", ko_a: "오쿠 타마무시", d: "主人公・空池（そらいけ）メイは、高校の卒業式に片想いしていた親友への告白に大失敗。「大学では絶対に可愛い彼女を作る！」と意気込んで進学したものの、彼女の前に現れたのは、お色気たっぷりのハイスペックお姉さん、距離感が近すぎるクールなイケメン女子、超肉食系な元同級生のギャルなど、一癖も二癖もある魅力的な女性たちばかり。次々と迫りくる女の子たちに翻弄され、甘い誘惑やエロティックなハプニングにドギマギさせられながらも、本当の『恋』の定義を探し求めて奮闘する、賑やかでちょっぴり過激な多角関係ラブコメディの開幕！", en_d: "On her high school graduation day, the protagonist Mei Soraike completely fumbles her confession to her best friend and crush. Vowing to definitely get a cute girlfriend in college, she enters university with high spirits—only to find herself surrounded by an array of eccentric, highly attractive women. From a voluptuous, high-spec older student and a cool, handsome girl with zero concept of personal space, to a fiercely predatory gyaru who used to be her classmate. Constantly flustered by their bold advances, sweet seductions, and highly erotic accidental run-ins, Mei frantically tries to figure out the true definition of 'love' in this chaotic, slightly spicy, multi-faceted romantic comedy!", ko_d: "주인공 소라이케 메이는 고등학교 졸업식 날 짝사랑하던 절친에게 고백했다가 대실패하고 만다. '대학에서는 반드시 귀여운 여자친구를 만들겠어!'라며 의기투합해 진학했지만, 그녀의 앞에 나타난 것은 글래머러스한 고스펙 언니, 거리감이 너무 가까운 쿨한 멋쟁이 여자, 초육식계인 옛 동급생 갤 등 하나같이 개성 넘치는 매력적인 여성들뿐. 쉴 새 없이 다가오는 여자들에게 휘둘리며 달콤한 유혹과 아슬아슬한 해프닝에 두근거리면서도 진정한 '사랑'의 정의를 찾아내기 위해 분투하는, 떠들썩하고 조금은 발칙한 다각관계 러브 코미디의 개막!", amz: "https://amzn.to/4AiC3cB" },
        { n: 13, t: "猫ノ山寧々子はネコになる", en_t: "Neneko Nekonoyama Turns Into a Cat", ko_t: "네코노야마 네네코는 고양이가 된다", a: "ひのはら (著), ミト (イラスト)", en_a: "Hinohara (Author), Mito (Illustrator)", ko_a: "히노하라 (저), 미토 (일러스트)", d: "猫になれる亜人の女子高生・寧々子は、人見知りで臆病な性格。唯一心を許せる姉の友人・ましろに憧れを募らせていたが、ある日彼女が吸血鬼であることを知る。寧々子は彼女の血液提供者（パートナー）として同棲を提案し――。恋に不器用な少女たちのピュアラブストーリー。", en_d: "Neneko, a shy high school girl who can transform into a cat, harbors a deep admiration for Mashiro, her older sister's mysterious friend. Upon discovering that Mashiro is actually a vampire, Neneko proposes moving in together as her blood donor and partner. A pure love story of two girls clumsy in romance.", ko_d: "고양이가 될 수 있는 아인 여고생 네네코는 낯을 가리고 소심한 성격이다. 유일하게 마음을 터놓을 수 있는 언니의 친구 마시로를 동경하던 중, 어느 날 그녀가 흡혈귀라는 사실을 알게 된다. 네네코는 그녀의 혈액 제공자(파트너)로서 동거를 제안하는데──. 사랑에 서툰 소녀들의 퓨어 러브 스토리.", amz: "https://amzn.to/4h0Xxli" },
        { n: 14, t: "徒然日和", en_t: "Tsurezure Hiyori", ko_t: "한적한 나날", a: "浜弓場双", en_a: "Sou Hamayumiba", ko_a: "하마유바 소우", d: "のどかな田舎の学校を舞台に、少女たちが紡ぐ緩やかで愛おしい青春の1ページ。", en_d: "A slow and lovely piece of youth woven by girls set in a peaceful countryside school.", ko_d: "한적한 시골 학교를 무대로 소녀들이 자아내는 여유롭고 사랑스러운 청춘의 한 페이지.", amz: "https://amzn.to/4xxQS8p" },
        { n: 15, t: "ささめきこと", en_t: "Sasameki Koto", ko_t: "속삭임", a: "いんだまんだ", en_a: "Ikamanda", ko_a: "이카만다", d: "「可愛い女の子」が好きな少女と、彼女に片想いをするクールな少女のすれ違い学園ラブコメ。", en_d: "A school romantic comedy about a girl who loves cute girls and her cool friend who secretly loves her.", ko_d: "'귀여운 여자아이'를 좋아하는 소녀와 그녀를 짝사랑하는 쿨한 소녀의 엇갈리는 학원 러브 코미디.", amz: "https://amzn.to/4h8p8kz" },
        { n: 16, t: "行進子犬に恋文を", en_t: "Love Letter for the Marching Puppy", ko_t: "행진하는 강아지에게 연보를", a: "玉崎たま", en_a: "Tama Tamasaki", ko_a: "타마사키 타마", d: "陸軍幼年学校を舞台に、規律の中で不器用な少女たちが育む凛々しくも切ない恋心。", en_d: "Set in a military youth academy, a noble and emotional story about clumsy girls navigating strict discipline.", ko_d: "육군유년학교를 무대로 규율 속에서 서툰 소녀들이 싹 피우는 의젓하면서도 애절한 연심.", amz: "https://amzn.to/3TuuqPI" },
        { n: 17, t: "小百合さんの妹は天使", en_t: "Sayuri-san's Sister is an Angel", ko_t: "사유리 씨의 여동생은 천사", a: "伊藤ハチ", en_a: "Hachi Ito", ko_a: "이토 하치", d: "血の繋がらない義理の妹との、優しくてちょっぴり切ない学園ホームドラマ。", en_d: "A gentle and slightly bittersweet school home drama with a step-sister who is like an angel.", ko_d: "피가 섞이지 않은 의붓여동생과의 다정하고 조금은 애절한 학원 홈 드라마.", amz: "https://amzn.to/4hc8eSr" },
        { n: 18, t: "アネモネは熱を帯びる", en_t: "Anemone Is Heat-Grown", ko_t: "아네모네는 열을 띤다", a: "桜木蓮", en_a: "Ren Sakuragi", ko_a: "사쿠라기 렌", d: "不本意ながら進学した高校で、凪紗（なぎさ）は病弱な少女・茉白（ましろ）と出会う。彼女はなんと、凪紗が受験に失敗した原因となった因縁の少女だった……。自分を変えるため、凪紗は茉白を「好き」になろうと決意する。正反対な二人が紡ぎ出す、濃厚な百合世界。", en_d: "At a high school she never wanted to attend, Nagisa meets a sickly girl named Mashiro—who happens to be the very reason Nagisa failed her entrance exams. In a desperate bid to change herself, Nagisa resolves to make herself 'love' Mashiro. A dense, intense Yuri story woven by two contrasting girls.", ko_d: "마지못해 진학하게 된 고등학교에서 나기사는 병약한 소녀 마시로와 만난다. 그녀는 다름 아닌 나기사가 입시에 실패하게 된 원인을 제공한 악연의 소녀였다……. 자신을 바꾸기 위해 나기사는 마시로를 '좋아하게' 되기로 결심한다. 정반대인 두 사람이 자아내는 진한 백합 세계.", amz: "https://amzn.to/4hvwz6T" },
        { n: 19, t: "きみが死ぬまで恋をしたい", en_t: "I Want to Love You Until You Die", ko_t: "네가 죽을 때까지 사랑을 하고 싶어", a: "あおのなち", en_a: "Nachi Aono", ko_a: "아오노 나치", d: "戦争に身を投じる魔法学校の子供たち。過酷な運命の中で、死が二人を分かつまで愛することを誓う。", en_d: "At a magical military academy where children are trained for war, two girls vow a deep, painful affection amid a dark, cruel fate.", ko_d: "전쟁에 몸을 던지는 마법학교의 아이들. 가혹한 운명 속에서 죽음이 두 사람을 갈라놓을 때까지 사랑할 것을 맹세한다.", amz: "https://amzn.to/4xYJfce" }, 
        { n: 20, t: "踊り場にスカートが鳴る", en_t: "Skirts Sing on the Staircase Landing", ko_t: "계단참에 스커트가 울린다", a: "うたたね 游", en_a: "Yu Utatane", ko_a: "우타타네 유우", d: "桜ヶ森高校社交ダンス部2年の春間（はるま）ききは、本当は華麗に舞う「パートナー（女役）」に憧れながらも、高身長ゆえに周囲の期待通り「リーダー（男役）」を続けていた。ある日、幼馴染とのペア解消を機に、放課後の踊り場で人知れず理想のパートナーとしてのステップを踏んでいたところ、その姿を小柄で可憐な新入生・鳥羽見（とばみ）みちるに目撃される。「私のパートナーになってください」――みちるの真っ直ぐな言葉に導かれ、男役を望む後輩と、女役を夢見た先輩の、これまでの常識を覆す美しく熱い競技ダンス百合の幕が上がる。", en_d: "Kiki Haruma, a second-year student in her high school's ballroom dancing club, secretly longs to dance as a 'partner' (the follower), but her tall stature has always forced her into the role of a 'leader' (the leader). After her childhood friend breaks off their duo, Kiki is found dancing alone after school, practicing the fluid follower steps she deeply admires. Her graceful movements catch the eye of Michiru Tobami, a petite and elegant first-year student. Approaching Kiki, Michiru confidently asks, 'Please be my partner.' Entwining their hands, a senior who dreams of being led and a junior who desires to lead begin a stunning, passionate journey to redefine ballroom dancing together.", ko_d: "사쿠라가모리 고등학교 사교댄스부 2학년 하루마 키키는 사실 화려하게 춤추는 '파트너(여역)'를 동경하면서도 큰 키 때문에 주변의 기대에 맞춰 '리더(남역)'를 계속 맡고 있었다. 어느 날 소꿉친구와의 페어 해산을 계기로 방과 후 계단참에서 남몰래 이상적인 파트너로서의 스텝을 밟고 있던 중, 그 모습을 아담하고 가련한 신입생 토바미 미치루에게 들키고 만다. \"저의 파트너가 되어주세요\"── 미치루의 곧곧한 말에 이끌려, 남역을 바라는 후배와 여역을 꿈꾸던 선배의, 기존의 상상을 뒤엎는 아름답고 뜨거운 경기 댄스 백합의 막이 오른다.", amz: "https://amzn.to/3Vyksxi" }
      ]
    },
 
    {
      cat: "🏫 学園・青春の情景（つづき）", 
      en_cat: "🏫Scenes of School & Youth (Continued)",
      ko_cat: "🏫 학원·청춘의 풍경 (계속)",
      desc: "青春の光と影、そして言葉にできない特別な関係。少女たちの心を鮮やかに切り取った名作たち。",
      en_desc: "The light and shadows of youth, and special relationships that transcend words. Masterpieces that vividly capture the hearts of girls.",
      ko_desc: "청춘의 빛과 그림자, 그리고 말로 다할 수 없는 특별한 관계. 소녀들의 마음을 생생하게 포착한 명작들.",
      works: [
        { n: 21, t: "高音さんと嵐ちゃん", en_t: "Takane-san and Arashi-chan", ko_t: "타카네 씨와 아라시 쨩", a: "なうち", en_a: "Nauchi", ko_a: "나우치", d: "ちょっと強引でついつい攻めすぎてしまうお姉さん気質な高音（たかね）さんと、彼女の甘い誘惑にいつもドギマギしっぱなしで真っ赤になってしまうピュアな嵐（あらし）ちゃん。お互いが大好きでたまらない二人の、甘々で少し刺激的な日常をコミカルかつ愛らしく描く。貴方と過ごす毎日がとびきり愛おしくて幸せに満ちていく、ゼロ距離な溺愛ガールズラブコメディ。", en_d: "The sweet, heart-fluttering daily life of Takane, a slightly aggressive and deeply affectionate girl who loves to tease and pamper, and Arashi, a pure-hearted girl who constantly finds herself flustered and blushing at Takane's sweet advances. A deeply adorable and comforting slice-of-life Yuri comedy that captures the overwhelming happiness and absolute devotion found in their cozy, zero-distance relationship.", ko_d: "조금 억지스러울 정도로 적극적으로 다가오는 어언니 기질의 타카네 씨와, 그녀의 달콤한 유혹에 매번 두근거리며 얼굴을 붉히는 순수한 아라시 쨩. 서로를 너무나 좋아하는 두 사람의 달콤하고도 조금은 자극적인 일상을 코믹하고 사랑스럽게 그린 작품. 당신과 함께 보내는 매일이 각별하고 행복으로 가득 차오르는, 제로 거리의 딥러브 걸즈 러브 코미디.", amz: "https://amzn.to/4rfk6HL" },
        { n: 22, t: "付き合ってあげてもいいかな", en_t: "How Do We Relationship?", ko_t: "사귀어줘도 상관없잖아", a: "たみふる", en_a: "Tamifull", ko_a: "타미후루", d: "周囲から「超モテるいい女」に見られながらも、実は同性愛者であり、これまでに一度も好きな人と両想いになったことがない大学生のみわ。大学入学を機に入部した軽音サークルで、自分とは正反対の絶対友達にならないタイプだと思っていたお調子者の冴子と出会う。ひょんなことからお互いのセクシュアリティを打ち明け合い、「せっかくだからあたしたち、付き合ってみない？」と始まったリアルな恋。周囲の友人関係、セクシュアリティへの葛藤、綺麗事だけではいかない本音の女子大生ガールズラブ。", en_d: "Miwa is an outwardly popular and attractive university student who harbors a secret: she is a lesbian who has never experienced mutual love with someone she truly liked. After joining a college music club, she grows unexpectedly close to Saeko, an easygoing, outgoing girl she assumed she would never get along with. Upon discovering each other's hidden sexualities, Saeko casually suggests they start dating just to see how it goes. Moving past idealized romance, this poignant and realistic drama masterfully explores the genuine struggles of identity, social circles, and raw human relationships among college-aged women.", ko_d: "주변에서는 '인기 많은 매력적인 여성'으로 보이지만, 사실은 동성애자이며 지금까지 단 한 번도 좋아하는 사람과 마음이 통해본 적 없는 대학생 미와. 대학 입학을 계기로 가입한 경음악 동아리에서, 자신과는 정반대로 절대 친구가 될 리 없는 타입이라고 생각했던  쾌활한 사에코와 만난다. 우연한 계기로 서로의 성적 지향을 털어놓게 되고, \"기왕 이렇게 된 거 우리 한번 사귀어 볼래?\"라며 시작된 현실적인 사랑. 주변 친구 관계, 성적 지향에 대한 갈등, 미사여구로 포장되지 않는 여대생들의 리얼한 속마음을 그린 걸즈 러브.", amz: "https://amzn.to/4j7whnZ" },    
        { n: 23, t: "ロックは淑女の嗜みでして", en_t: "Rock Is a Lady's Modesty", ko_t: "록은 숙녀의 소양", a: "福田宏", en_a: "Hiroshi Fukuda", ko_a: "후쿠다 히로시", d: "全国から本物のお嬢様が集う超名門・お茶ノ水ノ女子学園。元庶民であることを隠し、完璧な淑女として息苦しい日々を強いる主人公・鈴ノ宮りりさは、ある日、旧校舎から響く激しいドラムの音に引き寄せられる。そこで目にしたのは、同じく完璧なお嬢様である黒鉄音羽がドラムを激しく叩き鳴らす姿だった。お互いの秘密とロックへの衝動を共有した二人が、気高きお嬢様学校を舞台に、美しく火花を散らしてシャウトする爆音ガールズロック青春劇。", en_d: "At an elite academy for high-class young ladies, Ririsa Suzunomiya constrains herself daily to act like a perfect, elegant lady, hiding her humble working-class roots. One day, she is drawn to the old school building by a thundering drumbeat, only to discover her flawless peer, Otoha Kurogane, furiously beating the drums. Sharing their hidden secrets and a mutual, burning impulse for rock music, the two noble girls begin to clash beautifully and shout out their souls in a high-octane, deafening youth rock drama.", ko_d: "전국에서 진짜 아가씨들이 모이는 초명문 오차노미즈 여자학원. 평민 출신이라는 사실을 숨긴 채 완벽한 숙녀로서 숨 막히는 나날을 보내는 주인공 스즈노미야 리리사는 어느 날, 구교사에서 울려 퍼지는 격렬한 드럼 소리에 이끌린다. 그곳에서 목격한 것은 역시나 완벽한 아가씨인 쿠로가네 오토하가 드럼을 격렬하게 연주하는 모습이었다. 서로의 비밀과 록을 향한 충동을 공유한 두 사람이 고결한 아가씨 학교를 무대로 아름답게 불꽃을 튀기며 샤우팅하는 폭음 걸즈 록 청춘극.", amz: "https://amzn.to/4h95jtI" },
        { n: 24, t: "淡島百景", en_t: "Awajima Hyakkei", ko_t: "아와지마 백경", a: "志村貴子", en_a: "Takako Shimura", ko_a: "시무라 타카코", d: "舞台に立つことを夢みる少女たちが全国から集まる、淡島歌劇学校の合宿所（通称・寄宿舎）。ミュージカルスターに憧れて入学した若菜、親友の思いを背負って学び続ける寮長の絹枝、周囲の視線を集める美しき特待生の絵美。恋や友情、憧れ、執着、嫉妬、恐れといった、既存の言葉には当てはまらない瑞々しくも複雑な感情を抱えながら、かけがえのない季節を共に生きる少女たちの揺れる心を鮮やかに切り取ったオムニバス形式の青春群像劇。", en_d: "At the dormitory of the elite Awajima Opera School, girls from all over Japan gather with dreams of standing on stage. Among them are Wakana, who longs to be a musical star; Kinue, the dorm leader carrying her best friend's unfulfilled wishes; and Emi, a breathtakingly beautiful scholarship student. Capturing a kaleidoscope of unnameable emotions—love, friendship, admiration, obsession, and jealousy—this poignant omnibus drama beautifully illustrates the complex inner worlds of young women living through an irreplaceable season of youth.", ko_d: "무대에 서는 것을 꿈꾸는 소녀들이 전국에서 모이는 아와지마 가극학교의 기숙사. 뮤지컬 스타를 동경하며 입학한 와카나, 절친한 친구의 뜻을 이어받아 학업에 매진하는 기숙사장 키누에, 주변의 시선을 한 몸에 받는 아름다운 특待생 에미. 사랑, 우정, 동경, 집착, 질투, 두려움 등 기존의 단어로는 정의할 수 없는 풋풋하면서도 복잡한 감정을 품은 채, 대체 불가능한 계절을 함께 살아가는 소녀들의 흔들리는 마음을 생생하게 포착한 옴니버스 형식의 청춘 군상극.", amz: "https://amzn.to/4AiEGuZ" },
        { n: 25, t: "割り切った関係ですから。", en_t: "It's a Business Relationship.", ko_t: "어차피割り切った 관계니까요.", a: "FLOWERCHILD", en_a: "FLOWERCHILD", ko_a: "FLOWERCHILD", d: "スクールカースト低めで冴えない日々を送る女子高生の綾（あや）は、出会いを求めてマッチングアプリを始め、落ち着いた大人の女性「KURO」と繋がる。顔も知らないまま日々の何気ない会話や自撮りの交換を重ねて親密になっていく二人だったが、ある日KUROの異変に気づいた綾は、思い切って彼女のマンションを訪ねる。しかし、そこで扉を開けたのは、学校では完璧で冷徹な憧れの存在である美人教師の黒橋先生だった。アプリから始まる、女子高生と女教師の秘密の割り切った関係。", en_d: "Aya, a high school girl on the lower rungs of the school social hierarchy, uses a matching app out of loneliness and connects with a mature, soothing woman going by 'KURO.' Though they've never met in person, they bond deeply over daily text updates and exchanging selfies. One day, sensing something wrong with KURO, a worried Aya decides to visit her apartment for the first time. Upon knocking on the door, she is shocked to be greeted by Kurohashi-sensei—the flawless, cold, and revered teacher from her school. A secret, complex relationship between a student and her teacher begins.", ko_d: "학교 서열이 낮고 우울한 나날을 보내는 여고생 아야는 인연을 찾기 위해 매칭 앱을 시작하고, 차분한 성인의 여성 'KURO'와 이어진다. 얼굴도 모른 채 일상의 사소한 대화와 셀카를 주고받으며 친밀해져 가던 두 사람이었지만, 어느 날 KURO의 이상을 감지한 아야는 큰맘 먹고 그녀의 맨션을 찾아간다. 하지만 문을 연 사람은 학교에서 완벽하고 냉철한 동경의 대상인 미인 교사 쿠로하시 선생이었다. 앱에서 시작되는 여고생과 여교사의 비밀스럽고도 드라이한 관계.", amz: "https://amzn.to/46XYxCe" },
        { n: 26, t: "顔だけ良いクラスメイトが、やたらとグイグイ来る百合の話。", en_t: "The Story of a Classmate Who Has Nothing Going for Her but Her Looks, Boldly Making Advances on Me.", ko_t: "얼굴만 잘난 반 친구가 끈질기게 대시해 오는 백합 이야기", a: "はちこ (著), 能代 リョウ (その他)", en_a: "Hachiko (Author), Ryo Noshiro (Other)", ko_a: "하치코 (저), 노시로 료 (기타)", d: "スクールカースト最上位のグループに属し、周囲に流されるまま彼氏と付き合って1年になる女子高生・海道律（かいどう りつ）。ある日、彼氏とキスをしようとした瞬間を、クラスメイトの矢来綴（やらい つづり）に目撃されてしまう。どこか抜けているけれど、元気で優しくてとびきり「顔が良い」綴。この最悪な遭遇をきっかけに、なぜか綴からやたらと真っ直ぐにグイグイと距離を縮められるようになり、律の平凡だったはずの日常と恋心が大きく揺れ動き始める青春ガールズラブ。", en_d: "Ritsu Kaido, a high school girl belonging to the top school hierarchy, has been casually dating her boyfriend for almost a year just to blend in. On the day they are about to kiss, the moment is suddenly witnessed by her classmate, Tsuzuri Yarai. Despite being a bit scatterbrained, Tsuzuri is energetic, incredibly kind, and possesses breathtakingly good looks. Following this awkward encounter, Tsuzuri inexplicably begins to aggressively and honestly close the distance between them, sending Ritsu's seemingly ordinary daily life and her heart into a beautifully flustered spin.", ko_d: "스쿨 카스트 최상위 그룹에 속해 주변에 휩쓸려 남친과 사귄 지 1년이 된 여고생 카이도 리츠. 어느 날, 남친과 키스하려던 순간을 반 친구 야라이 츠즈리에게 들키고 만다. 어딘가 허술하지만 밝고 다정하며 무엇보다 '얼굴이 너무나 잘난' 츠즈리. 이 최악의 조우를 계기로 웬일인지 츠즈리가 맹렬하고 솔직하게 다가오기 시작하고, 리츠의 평범했던 일상과 연심이 크게 흔들리기 시작하는 청춘 걸즈 러브.", amz: "https://amzn.to/4cRD9Ca" },
        { n: 27, t: "今日はカノジョがいないから", en_t: "Asumi-chan is Interested in Lesbian Brothels!", ko_t: "오늘은 여자친구가 없으니까", a: "岩見 樹代子", en_a: "Kiyoko Iwami", ko_a: "이와미 키요코", d: "周囲に隠れて付き合っている、女子高生の七瀬（ななせ）とゆに。ゆにはバレー部での練習に忙しい七瀬の事情を理解しつつも、寂しさを隠せない放課後を過ごしていた。その持て余した孤独と誰にも言えない秘密の恋の鬱屈を、ゆにはSNSの「裏垢」に自撮りや愚痴として投下し続けてしまう。しかし、そのアカウントが学校のクラスメイトにバレてしまった瞬間から、ゆにの静かだった日常は崩壊し、七瀬だけの従順な彼女ではいられなくなっていく。歪んだ関係と裏切りが交錯する、泥沼の背徳的ガールズラブドラマ。", en_d: "Yuni and Nanase are high school girls who are secretly dating. Although Yuni genuinely understands that Nanase is constantly preoccupied with her volleyball club, she can't help but feel a suffocating loneliness during their empty after-school hours. Seeking an escape, Yuni vents her unexpressed desires, selfies, and relationship frustrations onto a secret social media account. But when a classmate accidentally discovers her hidden profile, Yuni's quiet life shatters, and she finds herself unable to remain solely Nanase's faithful girlfriend. A dark, suspenseful Yuri drama filled with infidelity, secret deals, and emotional turmoil.", ko_d: "주변에 숨긴 채 교제 중인 여고생 나나세와 유니. 유니는 배구부 연습으로 바쁜 나나세의 사정을 이해하면서도 참을 수 없는 외로움을 삼키며 방과 후를 보낸다. 주체할 수 없는 고독과 아무에게도 말할 수 없는 비밀스러운 사랑의 답답함을 유니는 SNS '부계정'에 셀카와 불만으로 털어놓게 된다. 하지만 그 계정이 학교 반 친구에게 들켜버린 순간부터 유니의 조용했던 일상은 무너지고, 나나세만의 순종적인 여자친구로 남을 수 없게 되는데……. 뒤틀린 관계와 배신이 교차하는 진흙탕 속 배덕의 걸즈 러브 드라마.", amz: "https://amzn.to/4fc32wP" },
        { n: 28, t: "わたしが恋人になれるわけないじゃん、ムリムリ! （※ムリじゃなかった!?）", en_t: "There's No Way I Can Have a Lover After All (Or Maybe There Is?!)", ko_t: "내가 연인이 될 수 있을 리 없잖아, 무리 무리! (※무리(가 아닐지도!?)", a: "むっしゅ (著), 竹嶋 えく (著)", en_a: "Musshu (Author), Eku Takeshima (Character Design)", ko_a: "무슈 (저), 타케시마 에쿠 (캐릭터 디자인)", d: "中学時代のぼっち生活から脱却すべく、猛努力の末に高校デビューを果たした甘織れな子。しかし、根の陰キャ気質ゆえに無理して作った陽キャ生活に限界を迎え、窒息寸前になっていた。そんなある日、学校の誰もが憧れる完璧なスーパースター・王塚真唯とひょんなことから秘密を共有し、無二の親友になる。これで最高の学園生活が始まるかと思った矢先、真唯から「君に恋をしてしまった」とまさかの告白をされ――！？ 親友か恋人か、二人の関係性と最高の高校生活を勝ち取るために奮闘する、全力疾走の青春ガールズラブコメディ。", en_d: "Determined to leave her friendless middle school days behind, Renako Amaori undergoes a total makeover for her high school debut. However, her naturally introverted self quickly suffocates under the strain of pretending to be a popular socialite. In her moments of despair, she crosses paths with Mai Ouka—the school's absolute, flawless superstar. After sharing their hidden burdens, they form an unbreakable bond as best friends, or so Renako thought, until Mai suddenly confesses, 'I've fallen in love with you.' Refusing to give up either a best friend or a potential lover, Renako proposes a competition to see which dynamic fits them best. A high-energy, comedic, and heartwarming school Yuri romance.", ko_d: "중학교 시절의 '아싸' 생활에서 벗어나고자 피나는 노력 끝에 고등학교 데뷔에 성공한 아마오리 레나코. 하지만 본질이 음침한 성격인 탓에 억지로 만든 인싸 생활의 한계에 부딪혀 질식할 지경에 이른다. 그러던 어느 날, 학교의 모든 이들이 동경하는 완벽한 슈퍼스타 오즈카 마유와 우연한 계기로 비밀을 공유하며 둘도 없는 친구가 된다. 이것으로 최고의 학원 생활이 시작될 줄 알았던 순간, 마유로부터 \"너를 사랑하게 되었어\"라는 뜻밖의 고백을 받게 되는데──!? 절친이냐 연인이냐, 두 사람의 관계와 최고의 학교생활을 사수하기 위해 분투하는 전력 질주 청춘 걸즈 러브 코미디.", amz: "https://amzn.to/4cPiSgr" },
        { n: 29, t: "週に一度クラスメイトを買う話 ～ふたりの時間、言い訳の五千円～", en_t: "Story of Buying a Classmate Once a Week: Our Time, the 5,000 Yen Excuse", ko_t: "일주일에 한 번 반 친구를 사는 이야기 ~두 사람의 시간, 핑계의 5천 엔~", a: "羽田 宇佐 (著), U35 (イラスト)", en_a: "Usa Haneda (Author), U35 (Illustrator)", ko_a: "하다 우사 (저), U35 (일러스트)", d: "クラスの誰とも馴染もうとしない宮城と、スクールカーストの最上位に位置する仙台さん。交わるはずのなかった二人は、宮城の気まぐれな思いつきから、週に一度「五千円」で仙台さんの時間を買うという奇妙な秘密の契約を結ぶ。部屋で一緒にゲームをしたり、お菓子を食べさせたり、時には少し危険な命令を交わしたり――。「私たちは友達じゃない」と言い訳の五千円で繋がれたまま半年を過ごす中、徐々に歪な主従関係は執着へと変わり、二人の境界線を曖昧に溶かしていく。微熱を孕んだ女子高生二人の、息苦しくも切ないディスタンス百合ストーリー。", en_d: "Miyagi is a solitary high school girl who distances herself from her peers, while Sendai sits at the very top of the school social hierarchy. These two opposites cross paths when Miyagi, on a sudden whim, offers to pay Sendai 5,000 yen once a week in exchange for the right to order her around. For six months, they share a secret room, playing video games, feeding each other snacks, and executing occasionally risky commands. Insisting 'we are not friends,' they use the money as a thin shield to hide their growing emotional dependence. As the seasons change, their twisted master-servant dynamic slowly morphs into an irreplaceable, suffocating obsession. A poignant and lingering high school Yuri drama.", ko_d: "반 누구와도 어울리지 않으려는 미야기와 스쿨 카스트 최상위에 위치한 센다이 씨. 접점이 없을 두 사람은 미야기의 변덕스러운 발상으로 일주일에 한 번 '5천 엔'에 센다이 씨의 시간을 산다는 기묘한 비밀 계약을 맺는다. 방에서 함께 게임을 하거나 과자를 먹여주거나 때로는 조금 위험한 명령을 주고받으며──. \"우린 친구가 아니야\"라며 핑계 5천 엔으로 연결된 채 반년을 보내는 동안, 서서히 뒤틀린 주종 관계는 집착으로 변해 두 사람의 경계선을 모호하게 녹여낸다. 미열을 품은 여고생 두 사람의 숨 막히고 애절한 디스턴스 백합 이야기.", amz: "https://amzn.to/3UX4Bbs" },
        { n: 30, t: "上伊那ぼたん、酔へる姿は百合の花", en_t: "Kamiina Botan, Her Drunken Face Is a Lily Flower", ko_t: "카미이나 보탄, 취한 모습은 백합꽃", a: "塀", en_a: "Hei", ko_a: "헤이", d: "二十歳になったばかりの女子大学生・上伊那ぼたん。普段は大人しくてちょっぴり人見知りな彼女だが、お酒が入ると一変、とろけるような笑顔を見せたり、思わずドキッとするような大胆な言葉を口にしたり……。同じ大学に通う友人や周囲の女性たちを、その無自覚な「酔い姿」で次々と翻弄し、魅了していく。様々なお酒や美味しいおつまみの描写と共に、お酒の席だからこそ縮まる女の子同士の絶妙な距離感を優しく、そして色っぽく描いた、令和の“読むアルコール”日常百合コメディ。", en_d: "Botan Kamiina is a 20-year-old college student who has just reached the legal drinking age. While she is usually quiet and a bit shrink, a single drink transforms her entirely, bringing out a melting smile and surprisingly bold, heart-fluttering remarks. Through her blissfully uninhibited and intoxicating 'drunken state,' she effortlessly charms and flusters the women around her. Packed with delightful depictions of various alcoholic beverages and delicious pairings, this cozy yet deeply alluring modern Yuri comedy beautifully captures the intimate, subtle distances between girls over a drink.", ko_d: "이제 막 스무 살이 된 여대생 카미이나 보탄. 평소에는 차분하고 조금 낯을 가리는 그녀지만, 술이 들어가면 180도 돌변해 녹아내릴 듯한 미소를 짓거나 깜짝 놀랄 만한 대담한 말을 내뱉곤 한다…. 같은 대학 친구들과 주변 여인들을 그 무자각한 '취중 모습'으로 차례차례 흔들어 놓으며 매료시키는 보탄. 다양한 술과 맛있는 안주 묘사와 함께, 술자리기 때문에 오히려 좁혀지는 여자들 사이의 미묘한 거리를 다정하면서도 매혹적으로 그린 레이와 시대의 '읽는 알코올' 일상 백합 코미디.", amz: "https://amzn.to/3UX76um" }
      ]
    },

  {
    cat: "💼 社会人・生活の連帯", 
    en_cat: "💼Adult Life & Solidarity",
    ko_cat: "💼 사회인·생활의 연대",
    desc: "自由を手にしたはずの大人の女性たちが直面する、ままならない現実。仕事、結婚、社会的役割の中で、独りでは抱えきれない孤独や不安を、パートナーとの連帯によって乗り越えていく姿を描きます。生活の匂いがするリアリティと、成熟した魂の結びつきを重視したラインナップです。",
    en_desc: "The inconvenient reality faced by adult women who are supposed to have gained freedom. It depicts how they overcome loneliness and anxiety that they cannot handle alone in their work, marriage, and social roles through solidarity with their partners. This lineup emphasizes reality with the scent of daily life and the connection of mature souls.",
    ko_desc: "자유를 손에 넣었을 어른 여성들이 직면하는 뜻대로 되지 않는 현실. 일, 결혼, 사회적 역할 속에서 혼자서는 감당할 수 없는 고독과 불안을 파트너와의 연대로 극복해 나가는 모습을 그립니다. 생활의 냄새가 나는 리얼리티와 성숙한 영혼의 결합을 중시한 라인업입니다.",
    works: [
      { n: 31, t: "作りたい女と食べたい女", en_t: "She Loves to Cook and She Loves to Eat", ko_t: "만들고 싶은 여자와 먹고 싶은 여자", a: "ゆざきさゆ", en_a: "Sakaomi Yuzaki", ko_a: "유자키 사유", d: "料理を巡る日常から連帯を深める二人。現代社会の救済を描く。", en_d: "Two women deepening their bond through cooking and eating.", ko_d: "요리를 매개로 일상에서 연대를 깊게 해 가는 두 사람. 현대 사회의 구원을 그린다.", amz: "https://amzn.to/4hckIJI" },
      { n: 32, t: "彩香ちゃんは弘子先輩に恋してる", en_t: "Ayaka is in Love with Hiroko", ko_t: "아야카 쨩은 히로코 선배를 사랑하고 있어", a: "Sal Jiang", en_a: "Sal Jiang", ko_a: "Sal Jiang", d: "愛が重い後輩と臆病な先輩。オフィス舞台の全力ラブストーリー。", en_d: "An office love story between an intense junior and a shy senior.", ko_d: "사랑이 무거운 후배와 겁쟁이 선배. 오피스를 무대로 한 전력 러브 스토리.", amz: "https://amzn.to/3TxoOEo" },
      { n: 33, t: "私の百合はお仕事です！", en_t: "Yuri Is My Job!", ko_t: "나의 백합은 일입니다!", a: "未幡", en_a: "Miman", ko_a: "미만", d: "コンセプトカフェで演じられる「理想の百合」。本音が交錯する。", en_d: "Idealized 'Yuri' performed at a concept cafe.", ko_d: "컨셉 카페에서 연출되는 '이상적인 백합'. 진심이 교차한다.", amz: "https://amzn.to/4yLS9dn" },
      { n: 34, t: "おとなになっても", en_t: "Even Though We're Adults", ko_t: "어른이 되어도", a: "志村貴子", en_a: "Takako Shimura", ko_a: "시무라 타카코", d: "ままならない大人の愛。実存的な問いかけを放する。", en_d: "A story about the complex and difficult love of adults", ko_d: "뜻대로 되지 않는 어른의 사랑. 실존적인 질문을 던진다.", amz: "https://amzn.to/4is2dTQ" },
      { n: 35, t: "明るい記憶喪失", en_t: "Cheerful Amnesia", ko_t: "밝은 기억상실", a: "奥たまむし", en_a: "Oki Tamamushi", ko_a: "오쿠 타마무시", d: "記憶を失っても、再び出会えばまた恋に落ちる。", en_d: "Even with memory loss, she falls in love with her partner again.", ko_d: "기억을 잃어도, 다시 만나면 또 사랑에 빠진다.", amz: "https://amzn.to/4y06d2E" },
      { n: 36, t: "Still Sick", en_t: "Still Sick", ko_t: "Still Sick", a: "あかしたけまる", en_a: "Akashi Takemaru", ko_a: "아카시 타케마루", d: "職場での有能さと密かな同人活動。自己肯定と絆の物語。", en_d: "A story of self-acceptance and bonds in the workplace.", ko_d: "직장에서의 유능함과 남몰래 하는 동인 활동. 자기 긍정과 유대의 이야기.", amz: "https://amzn.to/46MtKIJ" },
      { n: 37, t: "2DK、Gペン、目覚まし時計。", en_t: "2DK, G-pen, Alarm Clock", ko_t: "2DK, G펜, 자명종 시계.", a: "大沢やよい", en_a: "Yayoi Osawa", ko_a: "오오사와 야요이", d: "漫画家と社畜OL。正反対の価値観が支え合う生活。", en_d: "A manga artist and an office worker living together.", ko_d: "만화가와 회사원 OL. 정반대의 가치관이 서로를 지탱해 주는 생활.", amz: "https://amzn.to/4yauFyk" },
      { n: 38, t: "メタモルフォーゼの縁側", en_t: "BL Metamorphosis", ko_t: "메타모르포제의 툇마루", a: "鶴谷香央理", en_a: "Kaori Tsurutani", ko_a: "츠루타니 카오리", d: "BLを通じて心を通わせる75歳と17歳。魂の共鳴。", en_d: "A 75-year-old and a 17-year-old bonding over BL manga.", ko_d: "BL을 통해 마음을 나누는 75세와 17세. 영혼의 공명.", amz: "https://amzn.to/4hvDehp" },
      { n: 39, t: "ふたりエスケープ", en_t: "Futari Escape", ko_t: "둘이서 탈출", a: "田口囁一", en_a: "Shoichi Taguchi", ko_a: "타구치 쇼이치", d: "現実逃避が得意な二人。今を楽しむ空気感の物語。", en_d: "Two women who are experts at escaping reality.", ko_d: "현실 도피가 특기인 두 사람. 현재를 즐기는 공기감의 이야기.", amz: "https://amzn.to/4xxYrMl" },
      { n: 40, t: "君と綴るうたかた", en_t: "The Summer You Were There", ko_t: "너와 자아내는 물거품", a: "Yuama", en_a: "Yuama", ko_a: "유아마", d: "ひと夏の「偽りの恋」から始まる、切なくも美しい救済。", en_d: "A poignant story of salvation starting from a 'fake' summer romance.", ko_d: "어느 여름날의 '거짓 사랑'에서 시작되는, 애절하면서도 아름다운 구원.", amz: "https://amzn.to/4hyMi4b" }
    ]
  },
  {
    cat: "💼 社会人・生活の連帯（つづき）", 
    en_cat: "💼Adult Life & Solidarity (Continued)",
    ko_cat: "💼 사회인·생활의 연대 (계속)",
    desc: "成熟した大人の女性たちが紡ぐ、日々の生活の機微と深まる絆。職場の人間関係、キャリアの葛藤、日常のささやかな休息の中で、互いが唯一無二の理解者となっていくプロセスを、多角的な視点から描いた珠玉の作品群です。",
    en_desc: "The subtleties of daily life and deepening bonds woven by mature, adult women. This is a collection of gem-like works depicting the process of becoming each other's one and only understander amid workplace relationships, career struggles, and small daily respites.",
    ko_desc: "성숙한 어른 여성들이 자아내는 일상생활의 미세한 기와 깊어지는 유대. 직장 인간관계, 커리어의 갈등, 일상의 소소한 휴식 속에서 서로가 유일무이한 이해자가 되어가는 과정을 다각적인 시점에서 그린 주옥같은 작품군입니다.",
    works: [
      { n: 41, t: "海猫荘days", en_t: "Sea Gull Villa Days", ko_t: "해묘장 days", a: "コダマナオコ", en_a: "Naoko Kodama", ko_a: "코다마 나오코", d: "都会から移住してきた教師の少女と、地元の女性たちが織りなす地方学園の人間模様。", en_d: "The human drama of a female teacher who relocated from the city and the local women near a coastal town.", ko_d: "도시에서 이주해 온 교사 소녀와 지역 여성들이 엮어내는 지방 학원의 인간 군상.", amz: "https://amzn.to/4j8fX6p" },
      { n: 42, t: "いばら姫とおやすみ。", en_t: "Sleeping Beauty and Good Night", ko_t: "가시나무 공주와 굿나잇.", a: "深水紅茶 (著), 椎名 くろ (イラスト)", en_a: "Kocha Fukami (Author), Kuro Shiina (Illustrator)", ko_a: "후카미 코차 (저), 시이나 쿠로 (일러스트)", d: "社会人3年目のデザイナー・時雨は、通勤電車で重度の不眠症を抱える女子高生・いばらと出会う。時雨の隣なら眠れると確信したいばらは、必死の思いで「お金を払うから一緒に寝てほしい」と懇願。困惑しつつも放っておけない時雨は一晩だけの添い寝を受け入れるが――。孤独な夜に寄り添い合う、救済と秘密のガールミーツガール。", en_d: "Shigure, a third-year office designer, meets Ibarahime, a high school girl suffering from severe insomnia, on a commuter train. Convinced she can only sleep next to Shigure, Ibarahime desperately begs to rent her time for co-sleeping. Unable to turn away someone in deep distress, Shigure agrees to a single night, beginning a gentle girl-meets-girl story of shared solace and hidden secrets.", ko_d: "사회인 3년 차 디자이너 시구레는 통근 전철에서 중증 불면증을 앓는 여고생 이바라와 만난다. 시구레의 곁이라면 잠들 수 있다고 확신한 이바라는 필사적으로 \"돈을 줄 테니 같이 자달라\"고 애원한다. 당황스러우면서도 내버려 둘 수 없는 시구레는 하룻밤뿐인 동침을 받아들이는데──. 고독한 밤에 서로에게 기대는, 구원과 비밀의 걸 미츠 걸.", amz: "https://amzn.to/3V09gt8" },
      { n: 43, t: "性別不明な中性僕っ子とお姉さん", en_t: "The Gender-Neutral Short-Haired 'Bokukko' and the Older Sister", ko_t: "성별 불명의 중성적인 '보쿠코'와 누나", a: "つみきつき", en_a: "Tsukitsuki", ko_a: "츠미키 츠키", d: "26歳の会社員・ひなこさんは、ずっと男の子だと思っていた近所の子供・一葵（いつき）ちゃんが女の子かもしれないと知り大混乱。一葵ちゃんの何気ない仕草や格好よさにドキドキさせられる毎日。しかし実は、一葵ちゃんのほうもひなこさんへの片想いを募らせていて……。中性僕っ子に翻弄されるフルカラー・オフィス＆日常ラブコメ。", en_d: "Hinako, a 26-year-old office worker, is thrown into utter confusion upon realizing that Itsuki, the neighboring kid she always thought was a boy, might actually be a girl. While Hinako finds her heart racing over Itsuki's casually cool behavior every day, Itsuki is secretly harboring a massive, heart-pounding crush on her. A full-color romantic comedy about a charmingly ambiguous girl and a flustered older sister.", ko_d: "26세 회사원 히나코 씨는 쭉 남자아이인 줄 알았던 이웃집 아이 이츠키가 사실은 여자아이일지도 모른다는 사실을 알고 대혼란에 빠진다. 이츠키의 사소한 행동이나 멋진 모습에 두근거리는 나날. 하지만 사실 이츠키 쪽도 히나코를 향한 짝사랑을 키워가고 있었는데……. 중성적인 보쿠코에게 휘둘리는 풀컬러 오피스 & 일상 러브 코미디.", amz: "https://amzn.to/4rfqEWR" },
      { n: 44, t: "アフタヌーンティーはいかがですか？ 私と先輩の、不純で一途なふたり暮らし", en_t: "Would You Care for Afternoon Tea? My Co-living Life of Impure and Earnest Love with Senpai", ko_t: "애프터눈 티는 어떠신가요? 나와 선배의 불순하고 일편단심인 둘만의 동거", a: "桃田 ロウ (著), 塩こうじ (イラスト)", en_a: "Rou Momota (Author), Shiokouji (Illustrator)", ko_a: "모모타 로우 (저), 시오코우지 (일러스트)", d: "女たらしと有名な大学の先輩であり、意地悪な同居人でもある一ノ瀬結衣。「恋愛対象外」だと告げられた主人公の結衣（ゆい）は、先輩が誰とどんな夜を過ごそうと関係ないと思い込もうとするが、一つ屋根の下で暮らすうちに執着と嫉妬が狂おしく交錯していく。嘘と本音、ままならない独占欲が渦巻く、不純で一途な女子大生ふたり暮らしストーリー。", en_d: "Ichinose Yui is a notorious female philanderer at university, as well as a teasing, deceptive roommate. Having been explicitly told that she is 'outside the romantic loop,' the protagonist tries to remain indifferent to who Yui spends her nights with. However, living under the same roof causes agonizing attachment and jealousy to intertwine. A bittersweet college-life Yuri story about impure yet earnest devotion.", ko_d: "바람둥이로 유명한 대학 선배이자 심술궂은 동거인이기도 한 이치노세 유이. '연애 대상 외'라는 통보를 받은 주인공 유이는 선배가 누구와 어떤 밤을 보내든 상관없다고 되뇌려 하지만, 한 지붕 아래에서 살아가는 동안 집착과 질투가 미치도록 교차해 간다. 거짓과 본심, 뜻대로 되지 않는 독점욕이 소용돌이치는, 불순하고 일편단심인 여대생 둘만의 동거 스토리.", amz: "https://amzn.to/4dEa79e" },
      { n: 45, t: "どタイプお姉さんの誘惑が止まらないっ！ ちっちゃい頃から私のことがだいすきな年下従妹のお嫁さんになっちゃいました！？", en_t: "My Perfect Type Big Sister's Temptation Won't Stop! I Became the Wife of My Younger Cousin Who Loved Me Since She Was Little?!", ko_t: "내 취향 직격인 언니의 유혹이 멈추지 않아! 어릴 때부터 나를 아주 좋아하던 연하 사촌의 아내가 되어버렸습니다!?", a: "御園 海音 (著), けけもつ (イラスト)", en_a: "Amane Misono (Author), Kekemotsu (Illustrator)", ko_a: "미소노 아마네 (저), 케케모츠 (일러스트)", d: "幼い従妹を庇った事故で昏睡状態に陥った女子高生・音瀬小絃が目覚めると、そこはなんと10年後の世界。かつてちっちゃかった従妹は、自分好みの大人の女性へと完璧に成長し、目覚めた小絃に「お嫁さん」としてぐいぐい熱烈なアプローチを仕掛けてくる。10年の空白を飛び越えて始まる、刺激的な誘惑に理性が揺さぶられっぱなしの同居ラブコメディ。", en_d: "High school girl Koto Otose falls into a coma after an accident while protecting her young cousin. When she finally wakes up, she finds herself 10 years in the future! Her once-little cousin has grown into a stunning adult woman who happens to be Koto's exact type—and she wastes no time aggressively making Koto her 'wife.' A heart-pounding cohabitation romantic comedy that leaps across a 10-year gap.", ko_d: "어린 사촌동생을 감싸려다 사고로 혼수상태에 빠진 여고생 오토세 코토가 눈을 뜬 곳은 무려 10년 뒤의 세계. 한때 꼬마였던 사촌은 자신의 취향인 어른 여성으로 완벽하게 성장해 있었고, 깨어난 코토에게 '아내'로서 맹렬하고 열렬한 어프로치를 해온다. 10년의 공백을 뛰어넘어 시작되는, 자극적인 유혹에 이성이 흔들릴 새 없는 동거 러브 코미디.", amz: "https://amzn.to/4djGcTI" },
      { n: 46, t: "限界社会人さんを救えるのはクソデカ感情ストーカーちゃんだけでした", en_t: "The Only One Who Could Save a Burned-Out Office Worker Was a Stalker Girl with Giant Emotions", ko_t: "용한계 사회인을 구할 수 있는 건 엄청난 감정의 스토커 쨩뿐이었습니다", a: "ちさこ", en_a: "Chisako", ko_a: "치사코", d: "残業と仕事詰めの地獄のような社会人生活を送り、「無理…限界…死ぬ…」と身も心もすり減らしていた山田花。そんな彼女を突如拉致し、「あなたを監禁します」と告げられたのは、凄まじく重い愛（クソデカ感情）を抱えた見知らぬストーカーの美女だった！？ 豪邸、豪華な食事、露天風呂など、至れり尽くせりの環境で、心優しき（？）ストーカーに甘やかされまくる天国のような歪で温かい監禁生活コメディ。", en_d: "Hana Yamada is living a hellish, exhausted life under severe overwork and on the brink of collapse. Her savior arrives in the form of a stunning, mysterious stalker girl driven by massive, overwhelming emotions, who suddenly kidnaps her and declares a 'confinement.' What follows is a paradoxical paradise inside a luxurious mansion with fine dining and open-air baths, where a burned-out adult is thoroughly spoiled in a twisted yet heartwarming domestic comedy.", ko_d: "야근과 일에 찌든 지옥 같은 사회인 생활을 보내며 \"무리야… 한계야… 죽겠어…\"라며 몸과 마음이 닳아 있던 야마다 하나. 그런 그녀를 느닷없이 납치해 \"당신을 감금하겠습니다\"라고 선언한 것은, 어마어마하게 무거운 사랑(엄청난 감정)을 품은 낯선 스토커 미녀였다!? 대저택, 호화로운 식사, 노천탕 등 온갖 정성이 가득한 환경에서, 마음 착한(?) 스토커에게 한껏 어리광을 부리게 되는 천국 같은 뒤틀린 온화한 감금 생활 코미디.", amz: "https://amzn.to/4yDGb5f" },
      { n: 47, t: "担当アイドルの熱愛がバレたけど、ノーダメだよね!(※お相手は男装したマネージャーの私だし)", en_t: "My Assigned Idol's Romance Was Leaked, But It's Zero Damage! (Since Her Partner Is Me, the Cross-Dressing Manager)", ko_t: "담당 아이돌의 열애가 들켰지만, 노데미지 맞지?(※상대는 남장한 매니저인 나니까)", a: "最宮 みはや (著), 緋月 ひぐれ (イラスト)", en_a: "Mihaya Saimiya (Author), Higure Hizuki (Illustrator)", ko_a: "사이미야 미하야 (저), 히구레 히구레 (일러스트)", d: "超人気アイドル・星原奏歌のマネージャーとなった女子大生の早瀬理月。最初は奏歌から舌打ちされるなど最悪の態度をとられていたが、ある日「好みの男性アイドルを紹介しろ」と迫られる。しかし、そのお相手はかつて理月が男装アイドルをしていた頃の『自分自身』だった。男装を隠して上手く懐に入ろうと画策する理月だったが、思惑は外れて速攻で正体がバレてしまい、立場が逆転。「これからは私の言うことに絶対服従」と迫られる、ワガママな最推しアイドルと元男装マネージャーによる、ハラハラドキドキの秘密共有ガールズラブコメディ。", en_d: "Ritsuki Hayase, a university student who becomes the manager of super-popular idol Kanaka Hoshihara, initially faces harsh treatment and tongue-clicking from her client. Things take a bizarre turn when Kanaka demands an introduction to her male idol crush—who is actually Ritsuki herself from her past days as a cross-dressing idol. Hoping to leverage this to control her demanding client, Ritsuki attempts to smooth things over while concealing the truth, only to be immediately exposed. With the tables completely turned and Kanaka declaring absolute obedience from her manager, a high-stakes, thrilling secret-sharing romantic comedy begins.", ko_d: "초인기 아이돌 호시하라 카나카의 매니저가 된 여대생 하야세 리츠키. 처음에는 카나카에게 혀를 차는 등 최악의 태도를 당했지만, 어느 날 \"취향의 남자 아이돌을 소개해달라\"며 닦달당한다. 하지만 그 상대는 과거 리츠키가 남장 아이돌을 하던 시절의 '자기 자신'이었다. 남장을 숨기고 요령껏 품에 파고들려던 리츠키였지만, 셈이 어긋나 금방 정체가 들통나고 입장이 역전된다. \"앞으로 내 말에 절대 복종\"이라며 다가오는, 제멋대로인 최애 아이돌과 전 남장 매니저에 의한 조마조마 두근두근 비밀 공유 걸즈 러브 코미디.", amz: "https://amzn.to/4h8UPdz" },
      { n: 48, t: "新しくできたお姉さんは、百合というのが好きみたい", en_t: "My New Big Sister Seems to Like Something Called Yuri", ko_t: "새로 생긴 언니는 백합이라는 걸 좋아하는 것 같아", a: "アサクラ ネル (著), かがちさく (イラスト)", en_a: "Neru Asakura (Author), Saku Kagachi (Illustrator)", ko_a: "아사쿠라 넬 (저), 카가치 사쿠 (일러스트)", d: "親の再婚により突然義理の姉妹となった、仕事を辞めて実家暮らし中のおっとりした妹・春夏（はるか）と、仕事一筋でクールな姉・沙織（さおり）。沙織からの提案で始まった二人きりの同居生活を通じて次第に距離が縮まっていく二人だったが、実は沙織には「大の百合好き（ガチのレズビアン）」であり、春夏に一目惚れしているという絶対に言えない秘密があった。家族としての絆を失う恐怖と、妹への止められない恋心の狭間で悶える、甘く切ない新婚風（？）姉妹ラブコメディ。", en_d: "Due to their parents' sudden remarriage, Haruka, an easygoing girl who quit her job to live at home, and Saori, a cool, career-driven woman, unexpectedly become stepsisters. Prompted by Saori's invitation, they begin sharing an apartment, slowly narrowing the distance between them through domestic life. However, Saori harbors a massive, unspoken secret: she is a lesbian who fell in love with Haruka at first sight. Torn between her longing for a genuine family bond and her growing romantic desires, a sweet and agonizing stepsister romantic comedy unfolds.", ko_d: "부모님의 재혼으로 갑자기 의붓자매가 된, 일을 그만두고 본가에서 지내는 덜렁이 동생 하루카와 일직선인 쿨한 언니 사오리. 사오리의 제안으로 시작된 둘만의 동거 생활을 통해 점차 거리가 좁혀지는 두 사람이었지만, 사실 사오리에게는 '엄청난 백합 덕후(진짜 레즈비언)'이며 하루카에게 첫눈에 반했다는 절대 말할 수 없는 비밀이 있었다. 가족으로서의 유대를 잃을 공포와 동생을 향한 멈출 수 없는 연심 사이에서 번민하는, 달콤하고 애절한 신혼풍(?) 자매 러브 코미디.", amz: "https://amzn.to/4yMy8Dr" },
      { n: 49, t: "姉の親友、私の恋人。", en_t: "My Sister's Best Friend, My Lover.", ko_t: "언니의 절친, 나의 연인.", a: "藤松 盟", en_a: "Mei Fujimatsu", ko_a: "후지마츠 메이", d: "小説家の聖奈（せな）は、実の姉・優奈に歪んだ恋愛感情を抱いていた。姉が離れていった喪失感から執筆も生活も破綻してしまった聖奈のもとに、姉の親友であり「姉の元恋人」でもある成人女性・菊（きく）がしつこく世話を焼きに訪ねてくる。菊を苦手だと思いながらも流されていく聖奈だったが、実は菊もまた聖奈に対して複雑な感情を秘めていた。執着と喪失を抱える成人女性二人の、不器用で重厚な人間ドラマ。", en_d: "Sena, a novelist, harbors a repressed, romantic obsession with her own older sister, Yuna. Left unable to write or maintain her daily life due to a profound sense of loss after her sister moves away, Sena is continuously visited by Kiku—an adult woman who is her sister's best friend and 'ex-lover.' Though Sena finds Kiku overbearing, she gradually lets her guard down, unaware that Kiku is masking a complex, hidden emotional baggage regarding Sena herself. A heavy, intricate Yuri drama about trauma and adult attachment.", ko_d: "소설가 세나는 친언니 유나에게 뒤틀린 연애 감정을 품고 있었다. 언니가 떠나간 상실감으로 집필도 생활도 파탄 나 버린 세나 앞에, 언니의 절친이자 '언니의 전 연인'이기도 한 성인 여성 키쿠가 끈질기게 돌봐주겠다며 찾아온다. 키쿠를 달가워하지 않으면서도 분위기에 휩쓸려 가는 세나였지만, 사실 키쿠 역시 세나를 향해 복잡한 감정을 품고 있었다. 집착과 상실을 품은 성인 여성 두 사람의, 서툴고도 묵직한 인간 드라마.", amz: "https://amzn.to/4AbIApn" },
      { n: 50, t: "VTuberなんだが配信切り忘れたら伝説になってた", en_t: "VTuber Legend: How I Went Viral After Forgetting to Turn Off My Stream", ko_t: "VTuber인데 방송 끄는 걸 깜빡했더니 전설이 되어 있었다", a: "七斗 七 (著), 塩かずのこ (イラスト)", en_a: "Nana To Nana (Author), Shio Kazunoko (Illustrator)", ko_a: "나나토 나나 (저), 시오 카즈노코 (일러스트)", d: "大手VTuber運営会社「ライブオン」の三期生として、表向きは大人しく可憐な『清楚』系として活動していた心音淡雪。しかし、不注意から配信を切り忘れたことで、ストロング缶の酒を煽り、凄まじい熱量で女の子への限界妄想を爆発させるという「酒カス・女好き」の本性が全世界へ筒抜けになってしまう。大炎上を覚悟した翌日、その破天荒なギャップが奇跡的に大ウケしてトレンド世界1位を獲得。開き直ってガチの素顔を解禁した彼女が、個性派だらけのライバルたちを巻き込みながら界隈の頂点へと駆け上がっていく、圧倒的熱量の新感覚VTuberコメディ。", en_d: "Awayuki Kokorone is a VTuber contracted under Live-On, a major agency filled with glittering stars, where she strictly maintains her public persona as a quiet, refined, and wholesome girl. However, a careless mistake leads her to leave her livestream running after her sign-off, broadcasting her true self to the world: a hard-drinking, girl-crazy chaotic mess who cracks open long-cans of alcohol and screams out raw otaku delusions. Expecting her career to be instantly ruined, Awayuki wakes up to find that her wild, unhinged gap-moe has gone massively viral, capturing the number one global trending spot. Embracing her new reality, she discards her fake modesty and charges headfirst into becoming a top-tier streaming legend.", ko_d: "대형 VTuber 운영 회사 '라이브 온'의 3기생으로서 겉으로는 조용하고 가련한 '청순'계로 활동하던 코코로네 아와유키. 하지만 부주의로 방송을 끄는 것을 깜빡하는 바람에, 스트롱 캔 맥주를 들이키며 어마어마한 열량으로 여자아이를 향한 한계 망상을 폭발시키는 '술고래·여색가'의 본성이 전 세계에 생중계되어 버린다. 대형 폭망을 각오한 다음 날, 그 엉뚱한 갭이 기적적으로 대히트를 치며 트렌드 세계 1위를 획득. 적반하장으로 진짜 민낯을 해금한 그녀가 개성 넘치는 라이벌들을 끌어들이며 업계 정점으로 치달아 올라가는, 압도적 열량의 신개념 VTuber 코미디.", amz: "https://amzn.to/4hftGWD" }
    ]
  },

  {
    cat: "💼 社会人・生活の連帯（つづき）", 
    en_cat: "💼Adult Life & Solidarity (Continued)",
    ko_cat: "💼 사회인·생활의 연대 (계속)",
    desc: "一歩進んで、さらに深く。傷を分かち合い、生活を重ねていく大人の女性たちのリアルな息遣い。甘いだけではない、人生の苦楽を共に歩むパートナーたちの特別な距離感を揃えました。",
    en_desc: "Taking a step further and going even deeper. The realistic breath of adult women sharing their wounds and building their lives together. A selection featuring the unique distance of partners who walk together through life's ups and downs, far beyond mere sweetness.",
    ko_desc: "한 걸음 더 나아가 깊숙이. 상처를 나누고 생활을 겹쳐가는 어른 여성들의 리얼한 숨결. 달콤하기만 한 것이 아닌, 인생의 고락을 함께 걷는 파트너들의 특별한 거리감을 모았습니다.",
    works: [
      { n: 51, t: "毎月庭つき大家つき", en_t: "Monthly With a Garden and a Landlord", ko_t: "매달 정원 딸린 집, 집주인 포함", a: "ヨドカワ", en_a: "Yodokawa", ko_a: "요도카와", d: "長年付き合ったパートナーとの破局に傷心し、気分を一新するために一戸建てに引っ越してきた社会人の須賀アサコ。心機一転、穏やかな新生活が始まるかと思いきや、なんとその物件の屋根裏部屋には、かつて世間を騒がせた元・国民的アイドルの大家お姉さんが勝手に住み込んでいて……！？ 過去に傷を抱えた不器用な成人女性二人が、ひとつ屋根の下でのんびりとした日々と丁寧な食事を共有しながら、ゆっくりと心を寄せ合っていく大人のリスタート百合コミック。", en_d: "Heartbroken and emotionally drained after breaking up with her long-term partner, office worker Asako Suga moves into a cozy detached house to start fresh. However, her plans for a quiet solo life are instantly upended when she discovers that the property's landlord—a former national idol who mysteriously left the spotlight—is secretly living in the attic! Under one roof, two adult women carrying past scars begin to share slow-paced days and home-cooked meals, gently healing and rewriting their futures in a comforting adult Yuri drama.", ko_d: "오랫동안 사귀던 파트너와의 파국으로 상심하여 기분 전환을 위해 주택으로 이사 온 사회인 스가 아사코. 심기일전하여 평온한 새 생활이 시작되나 싶었더니, 어째서인지 그 건물의 다락방에는 한때 세상을 떠들썩하게 했던 전 국민적 아이돌 집주인 언니가 제멋대로 눌러앉아 살고 있었는데……!? 과거에 상처를 안은 서툰 성인 여성 두 사람이 한 지붕 아래에서 여유로운 나날과 정성스러운 식사를 공유하며 서서히 마음을 열어가는 어른의 리스타트 백합 코믹.", amz: "https://amzn.to/3SLnFc8" },
      { n: 52, t: "わたしの百合も、営業だと思った？", en_t: "Did You Think My Yuri Was Just Business Too?", ko_t: "내 백합도 영업이라고 생각했어?", a: "アサクラ ネル (著), 千種 みのり (イラスト)", en_a: "Neru Asakura (Author), Minori Chigusa (Illustrator)", ko_a: "아사쿠라 넬 (저), 치구사 미노리 (일러스트)", d: "最推しアイドル・鐘月かりんの卒業を引きずる若手声優の仙宮すずね。そんな彼女の前に、かりんが新人声優として現れる。突然の推しの再供給に激しく動揺しながらも、先輩として一定の距離を保とうとするすずねだったが、かりんはアイドル時代と変わらぬ完璧なルックスでぐいぐいと距離を縮めてくる。ビジネス（百合営業）なのか本気（ガチ）なのか翻弄されるうちに、すずねは彼女を「ひとりの女性」として意識し始めていく。声優業界を舞台に贈る、先輩×後輩のガールズラブコメディ。", en_d: "Suzune Mamiya, a young voice actress, is still mourning the retirement of her absolute favorite idol, Karin Kanetsuki. Out of nowhere, Karin enters Suzune's agency as a rookie voice actress. While Suzune struggles to maintain a professional distance from her idol, Karin aggressively closes the gap between them. Constantly teased and left wondering if it's all just 'business' or genuine affection, Suzune slowly begins to see Karin as an individual woman. A delightful voice-acting industry Yuri romantic comedy between a senior and her junior.", ko_d: "최애 아이돌 카네즈키 카린의 졸업을 슬퍼하는 신인 성우 센구우 스즈네. 그런 그녀의 앞에 카린이 신인 성우로 나타난다. 갑작스러운 최애의 재등장에 심하게 동요하면서도 선배로서 일정한 거리를 유지하려 하는 스즈네였지만, 카린은 아이돌 시절과 다름없는 완벽한 외모로 성큼성큼 거리를 좁혀온다. 비즈니스(백합 영업)인지 진심인지 휘둘리는 사이, 스즈네는 그녀를 '한 사람의 여성'으로 의식하기 시작하는데……. 성우 업계를 무대로 펼쳐지는 선배×후배의 걸즈 러브 코미디.", amz: "https://amzn.to/4ri9Sq8" },
      { n: 53, t: "好きな子のいもうと", en_t: "My Crush's Little Sister", ko_t: "좋아하는 아이의 여동생", a: "犬甘 あんず (著), 塩こうじ (イラスト)", en_a: "Anzu Inukai (Author), Shiokouji (Illustrator)", ko_a: "이누카이 안즈 (저), 시오코우지 (일러스트)", d: "初恋の相手である優等生な先輩・花房渚に告白し、振られてしまった雨宮結叶。未練を断ち切れない結叶を見かねて、渚に瓜二つな不真面目の妹・海望（みひろ）が「お姉ちゃんへの想いを忘れさせてあげる」と、渚の代わりになる歪な関係を提案する。姉の格好をした海望とデートを重ね、渚の影を重ねて欲をぶつけ溺れていく結叶だったが、触れ合いを続けるうちに、身代わりではない海望自身の心と存在に次第に惹かれていく。姉妹の間で複雑にもつれる、切なく狂おしい百合三角関係ストーリー。", en_d: "Yuto Amamiya confesses her feelings to her first love, her elegant senior Nagisa Hanafusa, only to be rejected. Unable to move on, Yuto is approached by Nagisa's rebellious younger sister, Mihiro, who looks exactly like Nagisa. Mihiro offers a twisted compromise: 'I'll make you forget about my sister,' inviting Yuto to project her desires onto her. Yuto falls into a deep, drowning dependency—dating Mihiro while she dresses like Nagisa and crossing lines they shouldn't. However, through this physical and emotional intimacy, Yuto gradually finds herself genuinely falling for Mihiro herself, sparking an agonizing love triangle bound by family ties.", ko_d: "첫사랑 상대인 우등생 선배 하나부사 나기사에게 고백했다가 차여버린 아마미야 유토. 미련을 끊어내지 못하는 유토를 안타깝게 여긴, 나기사와 쏙 빼닮은 불량한 동생 미히로가 \"언니를 향한 마음을 잊게 해줄게\"라며 나기사의 대용이 되는 뒤틀린 관계를 제안한다. 언니의 차림을 한 미히로와 데이트를 거듭하며 나기사의 그림자를 겹쳐 욕망을 쏟아내며 빠져드는 유토였지만, 접촉을 계속할수록 대타가 아닌 미히로 자신의 마음과 존재에게 점차 끌리게 되는데. 자매 사이에서 복잡하게 얽히는, 애절하고도 미칠 듯한 백합 삼각관계 스토리.", amz: "https://amzn.to/4xoTXHX" },
      { n: 54, t: "あなたみたいに【連載版】", en_t: "Just Like You", ko_t: "당신처럼 [연재판]", a: "ユニ", en_a: "Yuni", ko_a: "유니", d: "念願のインテリアデザイナーになったものの、思うような成果を出せず自信を喪失していた柑奈（かんな）。精神的に追い詰められる中で、偶然にも理想を体現したような大人の女性・弥生（やよい）と出会う。優しく寄り添う弥生に悩みを打ち明けるうち、惹かれ合うように衝動的なキスを交わし、戸惑いながらもホテルで初めて女性と身体を重ねてしまう。一夜限りの関係と割り切れず激しく思い悩む柑奈だったが、後日、仕事の現場で衝撃の再会を果たすことに――。初めて女性に恋をした戸惑いと溺愛を描く、大人のオフィス百合ロマンス。", en_d: "Kanna achieved her dream of becoming an interior designer, but failing to deliver results has left her deeply anxious and ready to quit. In the midst of her despair, she crosses paths with Yayoi, a mature woman who embodies everything Kanna aspires to be. Opening up about her insecurities, the two grow closer until they share an impulsive kiss. Though Kanna has never loved a woman before, she cannot resist Yayoi's charm and spends an intimate night with her. Unable to brush it off as a mere one-night stand, Kanna finds her heart in turmoil—only to unexpectedly encounter Yayoi again through her work. A passionate adult workplace Yuri romance about a woman experiencing her first same-sex love.", ko_d: "염원하던 인테리어 디자이너가 되었지만 뜻대로 성과를 내지 못하고 자신감을 잃어버린 칸나. 정신적으로 몰리는 가운데, 우연히도 자신의 이상을 체현한 듯한 어른 여성 야요이를 만난다. 다정하게 곁을 지켜주는 야요이에게 고민을 털어놓는 동안, 서로 이끌리듯 충동적인 키스를 나누고 당황스러워하면서도 호텔에서 처음으로 여성과 몸을 섞게 된다. 하룻밤의 관계라고 선을 긋지 못하고 심하게 고민하는 칸나였지만, 훗날 일터에서 충격적인 재회를 하게 되는데──. 처음으로 여성에게 사랑에 빠진 당혹스러움과 깊은 애정을 그린 어른의 오피스 백합 로맨스.", amz: "https://amzn.to/4AhKuEY" },
      { n: 55, t: "この恋を星には願わない 1【電子限定特典付き】", en_t: "I Won't Ask the Stars for This Love", ko_t: "이 사랑을 별에게 빌지 않아 1 [전자한정 특전 포함]", a: "紫のあ", en_a: "Noa Murasaki", ko_a: "무라사키 노아", d: "幼い頃からずっと同じ時間を共有し、固い絆で結ばれてきた幼馴染の三人組、冬葵（ふゆき）、瑛莉（えり）、京（みやこ）。何気ない友達としての関係を穏やかに続けてきた彼らだったが、冬葵は密かに、瑛莉に対して友情以上の切ない恋心を抱き続けていた。そんな中、久しぶりに三人で出かけた遊園地でのことをきっかけに、冬葵は自分の秘めた恋が決して叶うことのないものであるという残酷な現実を悟ってしまい――。それぞれの「好き」という想いが複雑に交錯する、美しくもどこか淡く切ない、少女たちの青春群像百合ラブストーリー。", en_d: "Fuyuki, Eri, and Miyako are a trio of childhood friends who have spent almost every moment together since they were young, bound by an unbreakable platonic bond. However, underneath their peaceful everyday routine, Fuyuki secretly harbors a deep, aching romantic affection for Eri that goes far beyond mere friendship. One day, during a long-awaited trip to an amusement park, a sudden revelation forces Fuyuki to realize that her hidden love is destined to remain unrequited. Exploring the delicate, complicated tangles of silent longing, this beautifully melancholic school youth Yuri drama follows girls trapped in a web of intersecting feelings.", ko_d: "어릴 때부터 줄곧 같은 시간을 공유하며 단단한 유대로 묶여 온 소꿉친구 삼총사 후유키, 에리, 미야코. 평범한 친구 관계를 평온하게 지속해 온 그들이었지만, 후유키는 몰래 에리를 향해 우정 이상의 애절한 연심을 품고 있었다. 그러던 중 오랜만에 셋이서 놀러 간 유원지에서의 일을 계기로, 후유키는 자신이 품어온 비밀스러운 사랑이 결코 이루어질 수 없다는 잔인한 현실을 깨닫게 되는데──. 각자의 '좋아해'라는 마음이 복잡하게 교차하는, 아름다우면서도 어딘가 아련하고 애절한 소녀들의 청춘 군상 백합 러브 스토리.", amz: "https://amzn.to/4yEW1wq" }
    ]
  },
  {
    cat: "✨ 異世界・幻想の叙事詩", 
    en_cat: "✨Fantasy & Epic Narratives",
    ko_cat: "✨ 이세계·환상의 서사시",
    desc: "魔法、剣、そして過酷な運命が支配する非日常の世界。壮大な設定の中だからこそ、剥き出しになる絆の本質があります。時に命を懸け、時に世界の理を塗り替えながら、最愛の人のために戦う女性たちの高潔な姿を追います。現実を超越した美しさを求める方に。",
    en_desc: "A world of extraordinary circumstances governed by magic, swords, and harsh fates. Because it is within a grand setting, the essence of the bond is exposed. We follow the noble figures of women fighting for their beloved ones, sometimes risking their lives and sometimes rewriting the laws of the world. For those seeking beauty that transcends reality.",
    ko_desc: "마법, 검, 그리고 가혹한 운명이 지배하는 비일상의 세계. 장대한 설정 속이기 때문에 비로소 드러나는 유대의 본질이 있습니다. 때로는 목숨을 걸고, 때로는 세계의 이치를 다시 쓰며, 사랑하는 사람을 위해 싸우는 여성들의 고결한 모습을 쫓습니다. 현실을 초월한 아름다움을 추구하시는 분께.",
    works: [
      { n: 56, t: "転生王女と天才令嬢の魔法革命", en_t: "The Magical Revolution", ko_t: "환생 왕녀와 천재 영애의 마법 혁명", a: "南高春 / 鴉ぴえろ", en_a: "Haru Minamoto / Piero Karasu", ko_a: "미나모토 하루 / 카라스 피에로", d: "魔学と魔法で世界の理を塗り替えていく革命劇。", en_d: "A revolution rewriting the world's laws with magic.", ko_d: "마학과 마법으로 세계의 이치를 바꿔 나가는 혁명극.", amz: "https://amzn.to/4hwM8v4" },
      { n: 57, t: "私の推しは悪役令嬢。", en_t: "I'm in Love with the Villainess", ko_t: "내 최애는 악역 영애.", a: "青乃下 / いのり。", en_a: "Aonoshita / Inori.", ko_a: "아오노시타 / 이노리.", d: "推しの「悪役令嬢」に全霊の愛を捧げる転生記。", en_d: "Devoting entire love to her favorite villainess.", ko_d: "최애인 '악역 영애'에게 전령의 사랑을 바치는 환생기.", amz: "https://amzn.to/46vqsJC" },
      { n: 58, t: "裏世界ピクニック", en_t: "Otherside Picnic", ko_t: "다가세계 피크닉", a: "水野英多 / 宮澤伊織", en_a: "Eita Mizuno / Iori Miyazawa", ko_a: "미즈노 에이타 / 미야자와 이오리", d: "怪異が実在する「裏世界」を探索する濃密なバディ。", en_d: "An intense buddy story exploring the dangerous 'Otherside'.", ko_d: "괴이가 실존하는 '이면 세계'를 탐색하는 진한 버디물.", amz: "https://amzn.to/4yGQTYJ" },
      { n: 59, t: "機動戦士ガンダム 水星の魔女", en_t: "The Witch from Mercury", ko_t: "기동전사 건담 수성의 마녀", a: "サンライズ", en_a: "Sunrise", ko_a: "선라이즈", d: "「花婿」として「花嫁」を救うために戦う革新的百合。", en_d: "An innovative Yuri story set in the Gundam universe.", ko_d: "'신랑'으로서 '신부'를 구하기 위해 싸우는 혁신적인 백합.", amz: "https://amzn.to/4cSp7Ac" },
      { n: 60, t: "少女終末旅行", en_t: "Girls' Last Tour", ko_t: "소녀 종말 여행", a: "つくみず", en_a: "Tsukumizu", ko_a: "츠쿠미즈", d: "文明が滅びゆく世界で寄り添い、移動し続ける二人。", en_d: "Two girls traveling through a dying civilization.", ko_d: "문명이 멸망해 가는 세계에서 의지하며 계속 이동하는 두 사람.", amz: "https://amzn.to/3TfdvR8" },
      { n: 61, t: "処刑少女の生きる道", en_t: "The Executioner and Her Way of Life", ko_t: "처형소녀의 살아가는 길", a: "三ツ谷亮 / 佐藤真登", en_a: "Ryo Mitsuya / Mato Sato", ko_a: "미츠야 료 / 사토 마토", d: "殺意から本物の絆へ。過酷な運命を辿る旅。", en_d: "A journey from murderous intent to true bonds.", ko_d: "살의에서 진짜 유대로. 가혹한 운명을 더듬는 여정.", amz: "https://amzn.to/4AlnMfg" },
      { n: 62, t: "魔女の旅々", en_t: "Wandering Witch", ko_t: "마녀의 여행", a: "七緒一綺 / 白石定規", en_a: "Itsuki Nanao / Jougi Shiraishi", ko_a: "나나오 잇키 / 시라이시 죠기", d: "魔女イレイナの出会いと別れを綴る幻想オムニバス。", en_d: "The fantastical encounters and partings of Elaina.", ko_d: "마녀 이레이나의 만남과 이별을 엮어내는 환상 옴니버스.", amz: "https://amzn.to/4yPLK0J" },
      { n: 63, t: "魔法少女まどか☆マギカ", en_t: "Puella Magi Madoka Magica", ko_t: "마법소녀 마도카☆마기카", a: "Magica Quartet", en_a: "Magica Quartet", ko_a: "Magica Quartet", d: "絶望と奇跡。究極の献身と愛が胸を打つ。", en_d: "Despair and miracles. Ultimate devotion and love.", ko_d: "절망과 기적. 궁극의 헌신과 사랑이 심금을 울린다.", amz: "https://amzn.to/4iBjFoW" },
      { n: 64, t: "ひきこまり吸血姫の悶々", en_t: "The Vexations of a Shut-In Vampire Princess", ko_t: "은둔형 흡혈공주의 고민", a: "オリ口 / 小林湖底", en_a: "Origuchi / Kotei Kobayashi", ko_a: "오리구치 / 코바야시 코테이", d: "吸血鬼令嬢と部下たちが織りなす熱いドラマ。", en_d: "A hot drama of a vampire princess and her subordinates.", ko_d: "흡혈귀 영애와 부하들이 엮어내는 뜨거운 드라마.", amz: "https://amzn.to/4iGkddn" },
      { n: 65, t: "猫ノ山寧々子はネコになる", en_t: "Neneko Nekonoyama Turns Into a Cat", ko_t: "네코노야마 네네코는 고양이가 된다", a: "ひのはら (著), ミト (イラスト)", en_a: "Hinohara (Author), Mito (Illustrator)", ko_a: "히노하라 (저), 미토 (일러스트)", d: "猫になれる亜人の女子高生・寧々子は、人見知りで臆病な性格。唯一心を許せる姉の友人・ましろに憧れを募らせていたが、ある日彼女が吸血鬼であることを知る。寧々子は彼女の血液提供者（パートナー）として同棲を提案し――。恋に不器用な少女たちのピュアラブストーリー。", en_d: "Neneko, a shy high school girl who can transform into a cat, harbors a deep admiration for Mashiro, her older sister's mysterious friend. Upon discovering that Mashiro is actually a vampire, Neneko proposes moving in together as her blood donor and partner. A pure love story of two girls clumsy in romance.", ko_d: "고양이가 될 수 있는 아인 여고생 네네코는 낯을 가리고 소심한 성격이다. 유일하게 마음을 허락하는 언니의 친구 마시로를 동경해 왔지만, 어느 날 그녀가 흡혈귀라는 사실을 알게 된다. 네네코는 그녀의 혈액 제공자(파트너)로서 동거를 제안하는데──. 사랑에 서툰 소녀들의 퓨어 러브 스토리.", amz: "https://amzn.to/3Vlc18u" }
    ]
  },
  {
    cat: "✨ 異世界・幻想の叙事詩（つづき）", 
    en_cat: "✨Fantasy & Epic Narratives (Continued)",
    ko_cat: "✨ 이세계·환상의 서사시 (계속)",
    desc: "異なる種族、主従の誓い、あるいは悪役令嬢としての逆転劇。過酷で美しい異世界だからこそ、彼女たちの愛と執着はより気高く、深く燃え上がります。運命の鎖を解き放つ、新たな幻想譚の数々。",
    en_desc: "Different races, oaths of master and servant, or dramatic turnarounds as a villainess. Precisely because they are in a harsh and beautiful fantasy world, their love and obsession burn with greater nobility and depth. A new collection of fantasy tales that unshackle the chains of fate.",
    ko_desc: "서로 다른 종족, 주종의 맹세, 혹은 악역 영애로서의 역전극. 가혹하고 아름다운 이세계이기에 그녀들의 사랑과 집착은 더욱 고결하고 깊게 타오릅니다. 운명의 사슬을 풀어헤치는, 새로운 환상담의 무리.",
    works: [
      { n: 66, t: "リコリス・リコイル", en_t: "Lycoris Recoil", ko_t: "리코리스 리코일", a: "A-1 Pictures", en_a: "A-1 Pictures", ko_a: "A-1 Pictures", d: "対照的な二人の少女エージェントが織りなす、過激な日常と強固な絆。【アニメ版】", en_d: "An intense daily life and powerful bond between two contrasting young female secret agents. [Anime]", ko_d: "대조적인 두 소녀 에이전트가 엮어내는 과격한 일상과 강고한 유대. [애니메이션판]", amz: "https://amzn.to/4rgKvF4" },
      { n: 67, t: "狼の皮をかぶった羊姫", en_t: "The Princess Sheep in Wolf's Clothing", ko_t: "늑대 가죽을 뒤집어쓴 양 공주", a: "ミト", en_a: "Mito", ko_a: "미토", d: "肉食獣の「狼」でありながら、平和な羊の国で物静かな執事として働く六条（ろくじょう）アキ。穏やかな暮らしを気に入っていた彼女だったが、ひょんなことから羊の国の第三王女であるモモ＝シウダーファレスに深く気に入られ、彼女の専属家庭教師に指名されてしまう。純真無垢で天真爛漫、けれど時折大胆な表情を見せるお姫様と、彼女に振り回されつつも惹かれていく狼執事。ケモ耳の少女たちが織りなす、主従関係の甘く愛らしい異世界ガールズラブファンタジー。", en_d: "Aki Rokujo, a wolf who belongs to a predatory race, lives a quiet and peaceful life working as a butler in the Kingdom of Sheep. While she thoroughly enjoys her calm days, she unexpectedly catches the eye of Momo Ciudadjuarez, the third princess of the realm, and finds herself appointed as her personal tutor. Follow the adorable daily life of the innocent yet surprisingly bold sheep princess and her loyal, easily flustered wolf butler. A charming and sweet master-servant beast-ear Yuri fantasy.", ko_d: "육식동물인 '늑대'이면서도 평화로운 양의 나라에서 말없는 집사로 일하는 로쿠죠 아키. 평온한 삶을 마음에 들어 했던 그녀였지만, 어쩌다 보니 양 나라의 제3왕녀인 모모 시우다후아레스의 마음에 쏙 들어 그녀의 전속 가정교사로 지명되어 버린다. 순진무구하고 천진난만하지만 때때로 대담한 표정을 짓는 공주와 그녀에게 휘둘리면서도 점차 끌려가는 늑대 집사. 수인 귀를 가진 소녀들이 엮어내는 주종관계의 달콤하고 사랑스러운 이세계 걸즈 러브 판타지.", amz: "https://amzn.to/4dL3mCC" },
      { n: 68, t: "竜人ボディガードとお嬢様", en_t: "The Dragonoid Bodyguard and the Young Lady", ko_t: "용인 바디가드와 아가씨", a: "ふぁゆ瀬", en_a: "Fayuse", ko_a: "파유세", d: "密乃宝石商の一人娘・煌（きら）と、彼女を幼い頃から護り続けている竜人族のボディガード・天（てん）。かつては泣き虫だった煌だが、「天ちゃんにふさわしい主人になる」と一念発起し、交渉から採掘、溶接までこなす超アクティブな“パワー系お嬢様”へと大成長を遂げる。長命種ゆえに昔と変わらぬ姿で、時に暴走する煌をクールに見守る天。愛が重すぎるお嬢様と、彼女に過保護な竜人従者。主従でありながら時に護り護られる立場が逆転する、宝石のように強く輝く異種族百合ラブコメディ。", en_d: "Kira, the only daughter of the prominent Mitsuno jewelry merchants, has been protected since childhood by Ten, a cool-headed bodyguard from the dragonoid race. Once a helpless crybaby, Kira determined to become a master worthy of Ten, growing into a hyper-active 'power-type' young lady who can handle everything from business negotiations to mining and welding. As a long-lived species, Ten remains physically unchanged, quietly watching over her beloved mistress's wild antics. With a heavily devoted lady and a fiercely protective dragonoid servant, this sparkling interspecies Yuri comedy beautifully explores a shifting bond where the roles of protector and protected frequently flip.", ko_d: "미츠노 보석상의 외동딸 키라와 그녀를 어릴 적부터 지켜온 용인족 바디가드 텐. 한때는 울보였던 키레이지만, \"텐 쨩에게 어울리는 주인이 될 거야\"라며 일념발기하여 교섭부터 채굴, 용접까지 해내는 초활동적인 '파워계 아가씨'로 대성장을 이룬다. 장수 종족이라 옛모습 그대로인 채, 때때로 폭주하는 키라를 쿨하게 지켜보는 텐. 사랑이 너무 무거운 아가씨와 그녀에게 과보호하는 용인 종자. 주종이면서도 때때로 지키고 지켜지는 입장이 역전되는, 보석처럼 강하게 빛나는 이종족 백합 러브 코미디.", amz: "https://amzn.to/4AlXx8v" },
      { n: 69, t: "限界OLさんは悪役令嬢さまに仕えたい【電子単行本】", en_t: "The Overworked Office Lady Wants to Serve the Villainess", ko_t: "용한계 OL 씨는 악역 영애님을 모시고 싶어 [전자 단행본]", a: "ネコ太郎", en_a: "Nekotaro", ko_a: "네코타로", d: "理不尽な派遣切りに遭い、心身ともに疲れ果てていたOLの名鳥翠（なとり みどり）。絶望に暮れる彼女は、プレイ中だったノベルゲームの世界へ突然召喚されてしまう。しかも彼女を呼び出したのは、ゲーム内で数々の悪行を働き、破滅を迎えるはずの残虐非道な悪役令嬢ラピス・テネブラエだった。絶体絶命の状況下、翠はゲームの知識を駆使した「予知能力」でラピスの危機を救う。それを機にラピスに気に入られた翠は、彼女の専属秘書として雇われることになり……。悪役令嬢を幸せにするために全力で仕える、主従異世界百合ファンタジー。", en_d: "Midori Natori, a hard-working temporary office worker, hits rock bottom when she is suddenly and unfairly laid off. In the depths of her despair, she is accidentally summoned into the world of her favorite visual novel game. To her horror, her summoner is none other than Lapis Tenebrae—the notoriously cruel villainess destined for a tragic end. Facing execution, Midori uses her extensive knowledge of the game as 'prophecy' to save Lapis from an impending crisis. Deeply intrigued, Lapis appoints Midori as her personal secretary. Bound to save her beloved villainess from her dark fate, the dedicated ex-OL begins her new life in an enchanting master-servant Yuri fantasy.", ko_d: "부당한 파견 해고를 당해 심신이 지칠 대로 지쳐 있던 OL 나토리 미도리. 절망에 잠겨 있던 그녀는 플레이 중이던 소설 게임의 세계로 느닷없이 소환되어 버린다. 게다가 그녀를 불러낸 것은 게임 속에서 온갖 악행을 저지르고 파멸을 맞이할 운명인 잔혹부도덕한 악역 영애 라피스 테네브라에였다. 절체절명의 상황 속에서 미도리는 게임의 지식을 구사한 '예지 능력'으로 라피스의 위기를 구한다. 그것을 계기로 라피스의 마음에 든 미도리는 그녀의 전속 비서로 고용되는데……. 악역 영애를 행복하게 만들기 위해 전력을 다해 모시는, 주종 이세계 백합 판타지.", amz: "https://amzn.to/4ri9ecd" },
      { n: 70, t: "嫌われ魔女令嬢と男装皇子の婚約", en_t: "The Engagement of the Hated Witch Daughter and the Cross-Dressing Prince", ko_t: "미움받는 마녀 영애와 남장 황자의 약혼", a: "散葉 ちんみ", en_a: "Chinmi Chiriba", ko_a: "치리바 친미", d: "闇魔法の才能を持って生まれたがゆえに「魔女」と蔑まれ、家族からも街の人々からも迫害されてきたヴラッドリー家の末娘・イヴリス。挙句の果てに婚約者からも無慈悲に婚約破棄を突きつけられ、絶望のどん底にいた彼女の前に、隣国の麗しき男装皇太子・アルベルトが突如現れて求婚する。貴族の同性婚はあり得ないと激しく戸惑い拒絶しようとするイヴリスだったが、アルベルト（実は女性）からの距離感ゼロの猛烈な溺愛とアプローチに翻弄されていき……！？ 不遇な魔女令嬢とイケメン男装皇太子（♀）が織りなす、王宮主従ドタバタ異世界百合ラブコメディ。", en_d: "Born with a rare talent for dark magic, Yvelise, the youngest daughter of the Vladley family, has been shunned as a 'witch' and persecuted by her family and townsfolk alike. Dropped into the depths of despair after her fiancé callously calls off their engagement, an unexpected savior appears: Albert, the breathtakingly handsome prince from a neighboring empire, who suddenly proposes to her! Although Yvelise deeply opposes same-sex noble marriages and tries to reject the offer, she finds herself completely overwhelmed by the doting, fiercely aggressive affection from the charming, cross-dressing prince (who is secretly a woman). A high-energy, royal fantasy Yuri rom-com.", ko_t: "어둠 마법의 재능을 가지고 태어난 탓에 '마녀'로 멸시당하며 가족과 마을 사람들에게서 박해받아 온 블래들리 가문의 막내딸 이블리스. 결국 약혼자에게서도 무자비하게 파혼 통보를 받고 절망의 나락에 빠져 있던 그녀의 앞에, 이웃 나라의 아름다운 남장 황태자 알베르트가 느닷없이 나타나 청혼한다. 귀족의 동성혼은 있을 수 없다며 심하게 당황하고 거절하려던 이블리스였지만, 알베르트(사실은 여성)의 거리감 제로인 맹렬한 댁애와 어프로치에 휘둘려 가게 되는데……!? 불우한 마녀 영애와 훈남 남장 황태자(♀)가 엮어내는, 왕궁 주종 우당탕탕 이세계 백합 러브 코미디.", amz: "https://amzn.to/4gYkTcJ" },
    ]
  },
 
    {
      cat: "🏆 定番・美学の原点", 
      en_cat: "🏆The Origin of Classic Aesthetics",
      ko_cat: "🏆 정석·미학의 원점",
      desc: "「百合」という文化が積み上げてきた歴史の中で、決して外すことのできない金字塔。厳格な寄宿学校の伝統、変革を求める革命、そして様式美。これらの作品は、後世のクリエイターに多大な影響を与え続けています。ジャンルの根幹を知るための、避けては通れない名作群です。",
      en_desc: "A monumental achievement that can never be removed from the history of Yuri culture. Traditions of strict boarding schools, revolutions seeking change, and stylistic beauty. These works continue to exert a tremendous influence on creators of later generations. A group of masterpieces that cannot be avoided in order to know the roots of the genre.",
      ko_desc: "'백합'이라는 문화가 쌓아온 역사 속에서 결코 빼놓을 수 없는 금자탑. 엄격한 기숙학교의 전통, 변혁을 추구하는 혁명, 그리고 양식미. 이 작품들은 후세의 크리에이터들에게 지대한 영향을 계속해서 미치고 있습니다. 장르의 근간을 알기 위해 결코 지나칠 수 없는 명작 군단입니다.",
      works: [
        { n: 71, t: "マリア様がみてる", en_t: "Maria Watches Over Us", ko_t: "마리아님이 보고 계셔", a: "長沢智 / 今野緒雪", en_a: "Satoru Nagasawa / Oyuki Konno", ko_a: "나가사와 사토루 / 곤노 오유키", d: "精神的高潔さ。百合の様式美を完成させた聖典。", en_d: "The scripture that perfected the aesthetic of Yuri.", ko_d: "정신적 고결함. 백합의 양식미를 완성한 성전.", amz: "https://amzn.to/4iwBsh7" },
        { n: 72, t: "少女革命ウテナ", en_t: "Revolutionary Girl Utena", ko_t: "소녀혁명 우테나", a: "さいとうちほ / 幾原邦彦", en_a: "Chiho Saito / Kunihiko Ikuhara", ko_a: "사이토 치호 / 이쿠하라 쿠니히코", d: "少女たちの自立と解放を圧倒的ビジュアルで描く。", en_d: "Depicting girls' independence and liberation.", ko_d: "소녀들의 자립과 해방을 압도적인 비주얼로 그리다.", amz: "https://amzn.to/4yOGjiG" },
        { n: 73, t: "ストロベリー・パニック", en_t: "Strawberry Panic", ko_t: "스트로베리 패닉", a: "たくみなむち / 公野櫻子", en_a: "Namuchi Takumi / Sakurako Kimino", ko_a: "타쿠미 나무치 / 키미노 사쿠라코", d: "耽美な愛憎劇。かつてのブームの中核作。", en_d: "An aesthetic drama of love and hatred.", ko_d: "탐미적인 애증극. 한때 붐의 중핵을 이룬 작품.", amz: "https://amzn.to/4xywZOH" },
        { n: 74, t: "ささめきこと", en_t: "Sasameki Koto", ko_t: "속삭임", a: "いけだたかし", en_a: "Takashi Ikeda", ko_a: "이케다 타카시", d: "自身の指向に悩む「等身大」の葛藤を描いた金字塔。", en_d: "A landmark story about struggling with one's identity.", ko_d: "자신의 지향에 고민하는 '등신대'의 갈등을 그린 금자탑.", amz: "https://amzn.to/4xvyInO" },
        { n: 75, t: "あの娘にキスと白百合を", en_t: "A Kiss and a White Lily for Her", ko_t: "그 아이에게 키스와 백합을", a: "缶乃", en_a: "Canno", ko_a: "칸노", d: "多様な「百合の形」を網羅した入門に最適な一作。", en_d: "A great entry point covering various forms of Yuri.", ko_d: "다양한 '백합의 형태'를 망라한 입문에 최적격인 한 작품.", amz: "https://amzn.to/3TD8qlN" },
        { n: 76, t: "神無月の巫女", en_t: "Kannazuki no Miko", ko_t: "신무월의 무녀", a: "介錯", en_a: "Kaishaku", ko_a: "카이샤쿠", d: "輪廻の運命、激情の結末。多大な影響を与えた名作。", en_d: "A classic that influenced the genre with its tragic end.", ko_d: "윤회의 운명, 격정의 결말. 지대한 영향을 준 명작.", amz: "https://amzn.to/4AlTr05" },
        { n: 77, t: "飴色紅茶館歓談", en_t: "Chatting at the Amber Tea House", ko_t: "호박색 홍차가 환담", a: "藤枝雅", en_a: "Miyabi Fujieda", ko_a: "후지에다 미야비", d: "安らぎと癒やしの側面を体現した心地よい物語。", en_d: "A cozy story embodying peace and healing.", ko_d: "안식과 치유의 측면을 체현한 편안한 이야기.", amz: "https://amzn.to/4rlzylM" },
        { n: 78, t: "フラグタイム", en_t: "Fragtime", ko_t: "플래그 타임", a: "さと", en_a: "Sato", ko_a: "사토", d: "3分間だけ時間を止められる少女。不器用な恋。", en_d: "A girl who can stop time for three minutes.", ko_d: "3분 동안만 시간을 멈출 수 있는 소녀. 서툰 사랑.", amz: "https://amzn.to/4dbc6lx" },
        { n: 79, t: "ハッピーシュガーライフ", en_t: "Happy Sugar Life", ko_t: "해피 슈가 라이프", a: "鍵空とみやき", en_a: "Tomiyaki Kagisora", ko_a: "카기소라 토미야키", d: "純愛か狂気か。一途すぎる少女の衝撃の愛。", en_d: "Is it pure love or madness? A shocking story of devotion.", ko_d: "순애인가 광기인가. 한결같은 너무나도 소녀의 충격적인 사랑.", amz: "https://amzn.to/4rgLlBI" },
        { n: 80, t: "加瀬さん。シリーズ", en_t: "Kase-san Series", ko_t: "카세 양 시리즈", a: "高嶋ひろみ", en_a: "Hiromi Takashima", ko_a: "타카시마 히로미", d: "二人の成長と深まる愛を追い続けるファン必読作。", en_d: "A must-read following the growth of two girls' love.", ko_d: "두 사람의 성장과 깊어지는 사랑을 계속 쫓는 팬 필독작.", amz: "https://amzn.to/4rjKVe0" },
      ]
    },
    {
      cat: "📖 文芸・小説の深淵", 
      en_cat: "📖The Depths of Literature & Novels",
      ko_cat: "📖 문예·소설의 심연",
      desc: "絵のない言葉だけの世界だからこそ、読者の想像力は無限に広がります。著名な文芸作家たちが綴る、心理の細やかな襞、言葉の端々に宿る情念、そして社会的な障壁との葛藤。深い余韻を残す、大人の読書体験にふさわしい、文学的価値の高い作品を揃えました。",
      en_desc: "Because it is a world of words without pictures, the reader's imagination expands infinitely. We have gathered works of high literary value, written by famous literary authors, that depict the fine folds of psychology, the passions dwelling in every word, and the conflict with social barriers. Suitable for an adult reading experience that leaves a deep resonance.",
      ko_desc: "그림 없는 말뿐인 세상이기 때문에 독자의 상상력은 한없이 넓어집니다. 저명한 문예 작가들이 엮어내는 심리의 세밀한 주름, 말끝마다 깃드는 정념, 그리고 사회적 장벽과의 갈등. 깊은 여운을 남기는, 어른의 독서 체험에 걸맞은 문학적 가치가 높은 작품들을 모았습니다.",
      works: [
        { n: 81, t: "生のみ生のままで", en_t: "Nama no mi, Nama no mama de", ko_t: "있는 그대로 생생하게", a: "綿矢りさ", en_a: "Risa Wataya", ko_a: "와타야 리사", d: "圧倒的な筆致で描かれる、抗えない女同士の愛の衝動。", en_d: "An irresistible impulse of love between women.", ko_d: "압도적인 필치로 그려지는, 거역할 수 없는 여자들 사이의 사랑의 충동.", amz: "https://amzn.to/4AkMM6r" },
        { n: 82, t: "花物語", en_t: "Hana-monogatari", ko_t: "꽃이야기", a: "吉屋信子", en_a: "Nobuko Yoshiya", ko_a: "요시야 노부코", d: "大正時代、百合の歴史の「根」となった純粋な情操の美。", en_d: "Pure emotional beauty from the roots of Yuri history.", ko_d: "다이쇼 시대, 백합 역사의 '뿌리'가 된 순수한 정조의 미.", amz: "https://amzn.to/4AECSwL" },
        { n: 83, t: "独り舞", en_t: "Solo Dance", ko_t: "홀로 추는 춤", a: "李琴峰", en_a: "Li Kotomi", ko_a: "리 코토미", d: "性的指向に苦悩し、海を越えた女性の魂の到達点。", en_d: "The destination of a soul struggling with orientation.", ko_d: "성적 지향에 고뇌하며 바다를 건넌 여성 영혼의 도달점.", amz: "https://amzn.to/4iwW74C" },
        { n: 84, t: "コールミー・バイ・ノーネーム", en_t: "Call Me by No Name", ko_t: "콜 미 바이 노 네임", a: "斜線堂有紀 (著), くわばらたもつ (イラスト)", en_a: "Yuki Shasendo (Author), Tamotsu Kuwabara (Illustrator)", ko_a: "샤센도 유키 (저), 쿠와바라 타모츠 (일러스트)", d: "深夜のゴミ捨て場で出会った、美しく奔放で掴みどころのない女・古橋琴葉。彼女の魅力に囚われた世次愛は友達になることを拒まれ、代わりに奇妙な賭けを持ちかけられる。それは、仮初めの『恋人』になり、琴葉が改名する前の『本当の名前』を当てられたら友達になる、というもの。名前を当ててしまえば、この歪で幸福な恋人は終わる――。ぎこちなくも濃密に肌と心を重ね、関係を深めていく二人だったが、隠された名前に秘められた凄絶な過去と呪いが、二人の時間を切なく狂わせていく。俊英・斜線堂有紀が圧倒的筆致で放つ、狂おしいほどの執着と痛切なエロティシズムが炸裂する名前当て百合ミステリーの傑作長編。", en_d: "Protagonist Megumi Yotsugi meets Kotoha Furuhashi, a beautiful, ungraspable, and uninhibited woman at a garbage dump late at night. Intoxicated by her charm, Megumi seeks friendship but is flatly rejected. Instead, Kotoha proposes a bizarre wager: become temporary 'lovers,' and if Megumi can guess Kotoha's 'true name' from before her legal name change, she will grant her wish of friendship. However, guessing the name means ending this fragile, blissful romance. As they physically and emotionally entwine, deepening their dense yet awkward relationship, the horrific past and curse hidden behind the secret name refuse to let their happiness last. A masterfully written Yuri mystery novel layered with frantic obsession and poignant, sharp eroticism.", ko_d: "심야의 쓰레기장에서 만난, 아름답고 분포하며 잡을 곳 없는 여자 후루하시 코토하. 그녀의 매력에 사로잡힌 요츠기 메구미는 친구가 되는 것을 거부당하고, 대신 기묘한 내기를 제안받는다. 그것은 임시로 '연인'이 되어 코토하가 개명하기 전의 '진짜 이름'을 맞히면 친구가 된다는 것. 이름을 맞혀버리면 이 일그러지고 행복한 연인은 끝난다──. 서툴면서도 농밀하게 살결과 마음을 포개며 관계를 깊게 해 가는 두 사람이었지만, 숨겨진 이름에 숨겨진 참혹한 과거와 저주가 두 사람의 시간을 애절하게 미치게 만들어 간다. 준영 샤센도 유키가 압도적인 필치로 선보이는, 미치도록 집착과 통절한 에로티시즘이 작렬하는 이름 맞히기 백합 미스터리 걸작 장편.", amz: "https://amzn.to/4rlwCpi" },
        { n: 85, t: "ののはな通信", en_t: "Nonohana Tsushin", ko_t: "노노하나 통신", a: "三浦しをん", en_a: "Shion Miura", ko_a: "미우라 시온", d: "親友から恋人へ、そして別離へ。二人の女性の長い年月を手紙で描く恋愛小説。", en_d: "A love story told through letters, following two women from friendship to romance and separation across many years.", ko_d: "친구에서 연인으로, 그리고 이별로. 두 여성의 오랜 세월을 편지로 그린 사랑 이야기.", amz: "https://amzn.to/4j6ts6E" },
        { n: 86, t: "あなたがほしい je te veux", en_t: "Anata ga Hoshii: je te veux", ko_t: "당신을 원해: je te veux", a: "安達千夏", en_a: "Chinatsu Adachi", ko_a: "아다치 치나츠", d: "年下の友人・留美への同性愛の欲望を意識するカナ。男とは愛せず、女を愛しても抱き合うことを恐れる彼女の揺れる性愛と恋を描く、すばる文学賞受賞作。", en_d: "Kana becomes aware of her homosexual desire for her younger friend Rumi. A novel of love and sexuality depicting her complicated feelings toward women and men.", ko_d: "연하의 친구 루미에게 동성애적 욕망을 느끼는 카나. 남자는 사랑할 수 없고 여자를 사랑하면서도 관계를 두려워하는 그녀의 흔들리는 사랑과 욕망을 그린 스바루 문학상 수상작.", amz: "https://amzn.to/3VDxny0" },
        { n: 87, t: "雨の塔", en_t: "Tower of Rain", ko_t: "비의 탑", a: "宮木あや子", en_a: "Ayako Miyagi", ko_a: "미야기 아야코", d: "閉ざされた女子大学を舞台に、少女たちの愛情、執着、嫉妬が交錯する濃密な物語。", en_d: "A story of intense love, attachment, and jealousy among young women at an isolated women's university.", ko_d: "폐쇄된 여자대학교를 무대로 소녀들의 사랑과 집착, 질투가 교차하는 짙은 이야기.", amz: "https://amzn.to/4cUjrFN" },
        { n: 88, t: "荊の城", en_t: "Fingersmith", ko_t: "핑거스미스", a: "サラ・ウォーターズ", en_a: "Sarah Waters", ko_a: "세라 워터스", d: "ヴィクトリア朝の英国を舞台に、詐欺計画から始まる二人の女性の運命と愛を描く歴史ミステリ。", en_d: "A historical mystery about the fate and love of two women whose lives become entwined through a deception in Victorian England.", ko_d: "빅토리아 시대 영국을 배경으로 사기 계획에서 시작된 두 여성의 운명과 사랑을 그린 역사 미스터리.", amz: "https://amzn.to/4iDM3qE" },
        { n: 89, t: "ほかに誰がいる", en_t: "Who Else Is There?", ko_t: "그 밖에 누가 있을까", a: "朝倉かすみ", en_a: "Kasumi Asakura", ko_a: "아사쿠라 카스미", d: "同級生の少女への憧れが、恋情と執着へと変わっていく少女の危うい恋を描く物語。", en_d: "A story of a girl's dangerous love as her admiration for a female classmate transforms into intense longing and obsession.", ko_d: "동급생 소녀에 대한 동경이 사랑과 집착으로 변해가는 한 소녀의 위태로운 사랑을 그린 이야기.", amz:"https://amzn.to/4y4blDb" },
        { n: 90, t: "白い薔薇の淵まで", en_t: "To the Edge of the White Rose", ko_t: "하얀 장미의 끝까지", a: "中山可穂", en_a: "Kaho Nakayama", ko_a: "나카야마 카호", d: "二人の女性が激しく惹かれ合い、性愛と執着の果てまで進んでいく、濃密な女性同士の恋愛小説。", en_d: "An intense love story about two women drawn passionately to each other, exploring desire, sexuality, and obsession.", ko_d: "서로에게 강렬하게 끌리는 두 여성이 욕망과 성애, 집착의 끝까지 나아가는 짙은 여성 간 사랑 이야기.", amz: "https://amzn.to/4iIG049" },   
      ]
    },
    {
      cat: "アンソロジー：秘められた背徳と濃密な短編集", 
      en_cat: "Anthology: Secret Improprieties & Dense Short Stories",
      ko_cat: "앤솔로지: 숨겨진 배덕과 농밀한 단편집",
      desc: "『アンソロジー』のタイトルを冠した、一冊で多彩なシチュエーションを堪能できる珠玉の短編集。ちょっぴり大人でエロティックな背徳感、息が詰まるほど濃密な距離感、そして感情の揺らぎを凝縮した、甘く官能的な百合の世界へ誘います。",
      en_desc: "A collection of gems bearing the title 'Anthology,' allowing you to enjoy a variety of situations in a single volume. This category invites you into a sweet, sensual world of Yuri, condensed with slightly mature, erotic immorality, breathtakingly dense physical proximity, and fluctuating emotions.",
      ko_desc: "'앤솔로지'라는 타이틀을 걸고, 한 권으로 다채로운 시추에이션을 만끽할 수 있는 주옥같은 단편집. 조금은 어른스럽고 에로틱한 배덕감, 숨이 막힐 정도로 농밀한 거리감, 그리고 감정의 흔들림을 응축한, 달콤하고 관능적인 백합의 세계로 초대합니다.",
      works: [
        { n: 91, t: "隣の席が好きな人だった 学生百合アンソロジー", en_t: "The Person Sitting Next to Me Was My Crush: School Yuri Anthology", ko_t: "내 옆자리가 좋아하는 사람이었다 학생 백합 앤솔로지", a: "ネコ太郎 (著), 樫風 (著), 深海 紺 (著), 他", en_a: "Nekotaro, Kashikaze, Kon Fukami, et al.", ko_a: "네코타로 (저), 카시카제 (저), 후카미 콘 (저), 외", d: "新学期のクラス替えや席替え。もしも「好きな人と隣の席になれたら――」という、誰もが一度は夢見る青春の甘酸っぱいドキドキと憧れを凝縮した、全編描き下ろしの学生百合アンソロジー。教科書の貸し借り、ふとした瞬間に触れ合う肩、授業中の内緒の視線。期待と不安に胸を膨らませる少女たちの、瑞々しくもちょっぴり甘やかでピュアな恋の情景を、豪華作家陣が多彩なシチュエーションで紡ぐ珠玉の全8編。", en_d: "A brand-new school Yuri anthology centered around a dream everyone has had at least once during a classroom seat change: 'What if the person sitting next to me was my crush?' This collection perfectly captures the bittersweet flustered feelings and nervous excitement of youth through eight specially drawn stories. From sharing textbooks and accidental shoulder brushes to stealing secret glances during class, it explores the fresh, sweet, and pure romantic landscapes of high school girls. Beautifully woven by a luxury lineup of artists.", ko_d: "새 학기의 반 배정이나 자리 바꾸기. 만약 '좋아하는 사람과 짝이 된다면──'이라는, 누구나 한 번쯤 꿈꾸는 청춘의 새콤달콤한 두근거림과 동경을 응축한, 전편 신작 학생 백합 앤솔로지. 교과서 빌려주기, 문득 순간에 닿는 어깨, 수업 중의 남몰래 시선. 기대와 불안으로 가슴을 부풀리는 소녀들의 싱그럽고도 조금은 달콤하며 퓨어한 사랑의 풍경을, 호화 작가진이 다채로운 시추에이션으로 자아내는 주옥같은 총 8편.", amz: "https://amzn.to/4yKMSmc" },
        { n: 92, t: "泣き顔百合アンソロジー", en_t: "Crying Face Yuri Anthology", ko_t: "우는 얼굴 백합 앤솔로지", a: "緜 (著), 春花 あや (著), ゆでぱん (著), 他", en_a: "Wata (Author), Aya Haruka (Author), Yudepan (Author), et al.", ko_a: "와타 (저), 하루카 아야 (저), 유데판 (저), 외", d: "「女の子の泣き顔」という、フェティッシュでちょっぴり歪んだ愛好をテーマに掲げた、全7作完全描き下ろしのコンセプト百合アンソロジー。嬉し涙、悔し涙、あるいは胸が締め付けられるような切ない恋の涙から、情熱のあまり溢れ出る濃密な涙まで。様々なシチュエーションで感情を昂ぶらせ、美しい涙を流す少女たちの姿を気鋭の作家陣がフェティシズムたっぷりに描き出す、背徳的で愛おしい短編集。", en_d: "A conceptual, specially drawn Yuri anthology featuring seven short stories dedicated entirely to the fetishistic and slightly twisted theme of 'girls' crying faces.' From tears of joy and frustration to heart-wrenching tears of unrequited love, and even intense, emotional tears overflowed in moments of passion. This bittersweet and compelling collection captures girls letting their emotions run wild and shedding beautiful tears in a variety of situations, beautifully illustrated with deep fetishism by a talented lineup of artists.", ko_d: "'소녀의 우는 얼굴'이라는 페티시하고 조금은 비뚤어진 애호를 주제로 내걸은, 전 7작 완전 신작 컨셉 백합 앤솔로지. 기쁨의 눈물, 분함의 눈물, 혹은 가슴이 조여 오는 듯한 애틋한 사랑의 눈물부터, 정열 나머지 넘쳐흐르는 농밀한 눈물까지. 다양한 시추에이션에서 감정을 고조시키고 아름다운 눈물을 흘리는 소녀들의 모습을 기예의 작가진이 페티시즘 듬뿍 담아 그려내는, 배덕적이면서도 사랑스러운 단편집.", amz: "https://amzn.to/4Art5tN" },
        { n: 93, t: "ワンナイトラブ百合アンソロジー", en_t: "One-Night Stand Yuri Anthology", ko_t: "원나잇 러브 백합 앤솔로지", a: "つづら涼 (著), 川上しをん (著), ヨドカワ (著), 他", en_a: "Ryo Tsuzura, Shion Kawakami, Yodokawa, et al.", ko_a: "츠즈라 료 (저), 카와카미 시온 (저), 요도카와 (저), 외", d: "女性同士の一夜限りの過ちや情事をテーマに、実力派の豪華作家陣がビターでエロティックな関係性を描き出す、ちょっぴり大人向けのコンセプト百合アンソロジー。お酒の勢い、孤独の穴埋め、あるいはバーや小料理屋での偶然の出会い――。朝が来れば他人へと戻る、あるいは戻るはずだった二人の、火照る肌の温もりと、言葉にならない背徳的な衝動、そして夜の闇に溶けていく濃密な吐息を、様々な人間模様と共に生々しく官能的に切り取った珠玉の全7編。", en_d: "A conceptual, mature Yuri anthology dedicated to the bittersweet, erotic themes of one-night stands and fleeting love affairs between adult women. From coping with loneliness to chance encounters in cozy bars and restaurants, these seven stories explore the intense heat and wordless, heavy impulses of women crossing the line for just one night. Filled with flushed skin, raw sensuality, and the heavy atmosphere of relationships destined to dissolve when morning comes, this luxury lineup of artists masterfully captures the intimate, fleeting geometry of late-night desires.", ko_d: "여성 간의 하룻밤의 과오나 정사를 주제로, 실력파 호화 작가진이 비터하고 에로틱한 관계성을 그려내는, 조금은 어른을 위한 컨셉 백합 앤솔로지. 술김, 고독의 메움, 혹은 바나 소요리집에서의 우연한 만남──. 아침이 오면 남남으로 돌아가는, 혹은 돌아갈 예정이었던 두 사람의 상기된 피부의 온기와 말로 다 할 수 없는 배덕적 충동, 그리고 밤의 어둠 속으로 녹아드는 농밀한 한숨을 다양한 인간 군상과 함께 생생하고 관능적으로 포착해 낸 주옥같은 총 7편.", amz: "https://amzn.to/4h2jVfG" },
        { n: 94, t: "お酒のせいにはしませんから 百合×飲酒アンソロジー", en_t: "I Won't Blame It on the Alcohol: Yuri x Drinking Anthology", ko_t: "술 탓으로는 하지 않으니까 백합×음주 앤솔로지", a: "コミックニュータイプ (編集)", en_a: "Comic Newtype (Editor)", ko_a: "코믹 뉴타입 (편집)", d: "「お酒×百合」をテーマに、お酒の力を借りて縮まる大人の女性たちの距離感を艶やかに描き出す、完全描き下ろしのコンセプト百合アンソロジー。ほんのり色づくほろ酔いの頬、深酒の夜に見せるいつもと違う大胆な一面、そしてアルコールに背中を押されて零れ落ちる秘めていた本音。お酒のせいという言い訳の裏で、大人だからこそ踏み出せなかった一線を越えていく、エロティックでちょっぴりエモい濃密なエピソードを多数収録。豪華執筆陣が紡ぐ、読むほどに身も心もとろけるように酔いしれる珠玉の短編集。", en_d: "A specially drawn, themed Yuri anthology dedicated entirely to the alluring chemistry of 'drinking and adult women.' From the soft flush of being tipsy to the uninhibited, bold behavior brought out by late-night deep drinking, this collection captures the moments when hidden desires slip past a woman's lips under the influence. Shielded by the convenient excuse of alcohol, mature women finally step over the lines they never dared to cross before. Filled with an erotic, deeply emotional, and intoxicating atmosphere, this luxury lineup of artists presents a blissful volume that will leave you completely drunk on love.", ko_d: "'술×백합'을 주제로, 술의 힘을 빌려 좁혀지는 어른 여성들의 거리감을 요염하게 그려내는, 완전 신작 컨셉 백합 앤솔로지. 은은하게 물드는 취기 어린 뺨, 깊은 밤에 보이는 평소와 다른 대담한 일면, 그리고 알코올에 등 떠밀려 새어나오는 숨겨둔 진심. 술 탓이라는 변명 뒤에서 어른이기에 넘지 못했던 선을 넘어서는, 에로틱하고 조금은 감성적인 농밀한 에피소드를 다수 수록. 호화 집필진이 자아내는, 읽을수록 몸과 마음이 녹아내리듯 취하게 되는 주옥같은 단편집.", amz: "https://amzn.to/3THhjuB" },
        { n: 95, t: "私たちの恋が花開くとき 異世界恋愛百合アンソロジーコミック", en_t: "When Our Love Blooms: Another World Romance Yuri Anthology Comic", ko_t: "우리의 사랑이 꽃필 때 이세계 연애 백합 앤솔로지 코믹", a: "鴉ぴえろ (著), ミズユ (著), 池中織奈 (著), 他", en_a: "Piero Karasu, Mizuyu, Orina Ikenaka, et al.", ko_a: "카라스 피에로 (저), 미즈유 (저), 이케나카 오리나 (저), 외", d: "大人気の異世界ライトノベル作家陣の原作を実力派コミカライズ作家たちが美しく描き出す、異世界ファンタジーに特化した恋愛百合アンソロジー。追加課金制の契約彼女、無条件に愛される精霊の愛し子、メイドを困らせる破天荒な聖女、お嬢様と従者の絆、そして結婚という現実の壁に隔てられた愛の結末まで――。魔法や主従関係、貴族社会といった過酷で華やかな非日常の世界だからこそ、より一層瑞々しく、時に濃密に燃え上がる少女たちの気高い純愛と執着を詰め込んだ、読み応え抜群の珠玉の全5編を収録。", en_d: "A specialized fantasy romance Yuri anthology where popular isekai light novel authors and talented manga artists team up to bring mesmerizing tales to life. This volume features five rich stories set in extraordinary worlds: a temporary girlfriend under an add-on payment system, a beloved child of spirits receiving unconditional affection, an eccentric saint flustering her personal maid, a deep bond between a noble lady and her retainer, and the heavy fate of a love separated by political marriage. Within these harsh yet gorgeous settings of magic and strict social hierarchies, the pure love and suffocating obsessions of these noble girls bloom with dazzling brilliance.", ko_d: "대인기 이세계 라이트노벨 작가진의 원작을 실력파 코미컬라이즈 작가들이 아름답게 그려내는, 이세계 판타지에 특화된 연애 백합 앤솔로지. 추가 과금제 계약 그녀, 무조건적인 사랑을 받는 정령의 아이, 메이드를 곤란하게 하는 파천황 성녀, 영애와 종자의 유대, 그리고 결혼이라는 현실의 벽에 가로막힌 사랑의 결말까지──. 마법과 주종 관계, 귀족 사회라는 가혹하고 화려한 비일상의 세계이기 때문에 비로소 더욱 싱그럽고 때로는 농밀하게 타오르는 소녀들의 고결한 순애와 집착을 가득 채운, 읽을거리 만점의 주옥같은 총 5편 수록.", amz: "https://amzn.to/4cNOdjF" },
        { n: 96, t: "マッチングアプリ百合アンソロジー", en_t: "Matching App Yuri Anthology", ko_t: "매칭 앱 백합 앤솔로지", a: "吉田 ばな (著), ヨドカワ (著), 秋月 かづ (著), 他", en_a: "Bana Yoshida, Yodokawa, Kazu Akizuki, et al.", ko_a: "요시다 바나 (저), 요도카와 (저), 아키즈키 카즈 (저), 외", d: "「マッチングアプリでの出会い」をテーマに、画面越しの『いいね』から始まる様々な女性同士の恋模様を切り取った、完全描き下ろしのコンセプト百合アンソロジー。偶然アプリで繋がってしまった親友や、普段交わるはずのないギャル、密かに憧れるアイドル、果てはまさかの魔法少女まで――。多種多様なシチュエーションのなか、画面上のプロフィールから現実の対面へと進むステップでのドキドキ感、相手の素顔を知る瞬間の甘酸っぱい高揚感を、総勢7名の豪華作家陣が現代的かつピュアに描き出す、今最もリアルでエモい運命の出会い系短編集。", en_d: "A specially drawn, modern-themed Yuri anthology centered around 'meetings on matching apps,' capturing various romance stories that ignite from a single digital 'Like.' This collection follows girls connecting through a screen: a close friend accidentally matched, a gyaru who would normally live in a different social circle, a secretly admired idol, and even a magical girl! Across seven stories illustrated by a talented lineup of artists, it beautifully captures the heart-fluttering tension of moving from online profiles to face-to-face encounters, and the sweet excitement of discovering each other's true selves in this contemporary, fate-driven short story volume.", ko_d: "'매칭 앱에서의 만남'을 주제로, 화면 너머의 '좋아요'에서 시작되는 다양한 여성 간의 사랑 양상을 포착한, 완전 신작 컨셉 백합 앤솔로지. 우연히 앱으로 이어져버린 절친이나 평소 엮일 리 없는 갸루, 남몰래 동경하는 아이돌, 심지어 설마하던 마법소녀까지──. 다종다양한 시추에이션 속에서 화면상의 프로필에서 현실의 대면으로 나아가는 단계의 두근거림, 상대의 맨얼굴을 알게 되는 순간의 새콤달콤한 고양감을 총 7명의 호화 작가진이 현대적이고 퓨어하게 그려내는, 지금 가장 리얼하고 감성적인 운명의 만남계 단편집.", amz: "https://amzn.to/4y12qCa" },
        { n: 97, t: "レズ風俗アンソロジー", en_t: "Lesbian Brothel Yuri Anthology", ko_t: "레즈 풍속 앤솔로지", a: "焔 すばる (著), 岩見 樹代子 (著), 他", en_a: "Subaru Homura, Kiyoko Iwami, et al.", ko_a: "호무라 스바루 (저), 이와미 키요코 (저), 외", d: "「女性専用の風俗店」という究極の癒やしと肉体的快楽の空間を舞台に、欲望と感情が濃密に交錯する瞬間を切り取ったコンセプト百合アンソロジー。日常に疲れ果てて扉を叩いた客と、すべてを優しく包み込むプロのキャスト。あるいは、指名というビジネスの関係の裏側で密かに育まれていく、本気の執着や秘められた独占欲――。お互いの肌の温もりに溺れ、甘く熟した吐息を重ね合わせるエロティックな情事から、傷ついた心が身体の交わりによって解きほぐされていく切なくもエモい救済の物語まで、実力派の豪華作家陣8名がそれぞれの視点で艶やかに描き出す、淫らでどこか愛おしい至高の大人向け短編集。", en_d: "Set in the ultimate space of physical pleasure and emotional healing—a women-only adult service parlor—this themed Yuri anthology captures the deeply intense moments where raw desire and genuine affection intersect. It features exhausted everyday women seeking comfort and the professional escorts who gently embrace them, alongside stories of burning obsessions and hidden possessiveness that quietly develop behind a commercial transaction. From erotic affairs where women drown in the warmth of each other's skin and heavy, passionate sighs, to moving tales of emotional salvation where wounded hearts are unraveled through intimate physical contact, this high-end volume for adult audiences features eight talented artists masterfully delivering an enticing, beautifully decadent experience.", ko_d: "'여성 전용 풍속점'이라는 궁극의 치유와 육체적 쾌락의 공간을 무대로, 욕망과 감정이 농밀하게 교차하는 순간을 포착한 컨셉 백합 앤솔로지. 일상에 지쳐 문을 두드린 손님과 모든 것을 다정하게 감싸 안는 프로 캐스트. 혹은 지명이라는 비즈니스 관계의 이면에서 남몰래 싹트어 가는 진심 어린 집착이나 숨겨진 독점욕──. 서로의 피부의 온기에 빠져 달콤하고 무르익은 한숨을 겹쳐가는 에로틱한 정사부터, 상처받은 마음이 몸의 결합에 의해 풀려나가는 애틋하면서도 감성적인 구원의 이야기까지, 실력파 호화 작가진 8명이 각자의 시선으로 요염하게 그려내는, 음탕하면서도 왠지 사랑스러운 지고의 어른용 단편집.", amz: "https://amzn.to/4dbcEI7" },
        { n: 98, t: "異世界転生百合アンソロジー", en_t: "Isekai Reincarnation Yuri Anthology", ko_t: "이세계 환생 백합 앤솔로지", a: "南方 純 (著), 井原 リオ (著), きぃやん (著), 他", en_a: "Jun Minakata, Rio Ihara, Kiyanyan, et al.", ko_a: "미나카타 준 (저), 이하라 리오 (저), 키이야ㄴ (저), 외", d: "「異世界転生・転移」というファンタジーの王道シチュエーションを舞台に、未知の世界へと放り出された少女たちが紡ぐ新たな愛と絆の形を集めた完全描き下ろしのコンセプト百合アンソロジー。目が覚めるとゲームの悪役令嬢になっていた、あるいは魔法が満ちる異世界で特別な聖女として召喚された――。現代の常識が通用しない過酷で華やかな非日常の世界だからこそ、出会った二人の女性の距離感は急速に縮まり、時に運命に抗うための強い執着へと変わっていく。甘く情熱的な主従関係から、ちょっぴりエロティックで官能的な異世界での情事まで、気鋭の豪華作家陣7名がそれぞれの色彩で描き出す、ドラマチックでエモいガールズニューワールドの珠玉の全8編。", en_d: "Set against the classic fantasy backdrop of 'Isekai reincarnation and teleportation,' this specially drawn, themed Yuri anthology captures the fresh forms of love and romance woven by girls thrust into unknown realms. Whether waking up as a notorious video game villainess or being summoned as a revered saint into a world overflowing with magic—these extraordinary, gorgeous settings strip away modern common sense, causing the physical and emotional distance between two women to rapidly close, turning their initial confusion into a fierce obsession to defy fate together. From sweet, passionate master-servant bonds to slightly erotic and sensual late-night encounters in a fantasy land, seven talented artists masterfully present eight dramatic, deeply emotional tales of a dazzling girls' new world.", ko_d: "'이세계 환생·전이'라는 판타지의 왕도 시추에이션을 무대로, 미지의 세계로 내던져진 소녀들이 자아내는 새로운 사랑과 유대의 형태를 모은 완전 신작 컨셉 백합 앤솔로지. 눈을 떠보니 게임의 악역 영애가 되어 있었다, 혹은 마법이 가득한 이세계에서 특별한 성녀로서 소환되었다──. 현대의 상식이 통하지 않는 가혹하고 화려한 비일상의 세계이기에 비로소, 만난 두 여성의 거리감은 급속도로 좁혀지고 때로는 운명에 맞서기 위한 강한 집착으로 변해간다. 달콤하고 정열적인 주종 관계부터 조금은 에로틱하고 관능적인 이세계에서의 정사까지, 기예의 호화 작가진 7명이 각자의 색채로 그려내는, 드라마틱하고 감성적인 걸즈 뉴 월드의 주옥같은 총 8편.", amz: "https://amzn.to/3UZDooD" },
        { n: 99, t: "浮気・NTR百合アンソロジー", en_t: "Infidelity & NTR Yuri Anthology", ko_t: "바람·NTR 백합 앤솔로지", a: "しのぎあさ (著), 森 (著), 遮二無二 (著), 他", en_a: "Asa Shinogi, Mori, Shanimuni, et al.", ko_a: "시노기 아사 (저), 모리 (저), 샤니무니 (저), 외", d: "「浮気」「寝取られ（NTR）」という、背徳感と罪悪感の極致に焦点を当てた、ちょっぴり大人向けのビターで官能的なコンセプト百合アンソロジー。彼氏や夫がいるはずの身でありながら、あるいは大切な親友という一線がありながら、別の女性の甘い誘惑と愛撫に抗えず、泥沼の快楽へと堕ちていく少女たちの焦燥と歪んだ愛情。秘密の共有、罪の意識でさらに火照る肌、そしてお互いを激しく求め合う濃厚なベッドシーンまで――。タブーに踏み込んだからこそ剥き出しになる、生々しくエロティックな独占欲と執着を、実力派の豪華作家陣がエモく艶やかに描き出す珠玉の全6編。", en_d: "A bitter, sensual, and highly mature Yuri anthology pushing the boundaries of taboo by focusing on the raw guilt and thrilling immorality of 'infidelity' and 'Netorare (NTR).' Despite having boyfriends, husbands, or long-time best friends, these women find themselves completely powerless against the sweet seductions and intimate caresses of another woman, gradually drowning in a quagmire of forbidden physical pleasure. Shielded by shared secrets and fueled by a burning consciousness of sin, they clash in intensely dense, erotic bedroom encounters. This provocative collection features six dark, deeply emotional stories illustrated by talented artists who masterfully capture the raw, obsessive possessiveness exposed only when crossing the ultimate line.", ko_d: "'바람', '네트라레(NTR)'라는 배덕감과 죄책감의 극치에 초점을 맞춘, 조금은 어른을 위한 비터하고 관능적인 컨셉 백합 앤솔로지. 남친이나 남편이 있을 터인 몸이면서도, 혹은 소중한 절친이라는 선이 있으면서도, 다른 여성의 달콤한 유혹과 애무에 거역하지 못하고 진흙탕의 쾌락으로 타락해 가는 소녀들의 초조함과 일그러진 애정. 비밀의 공유, 죄의식으로 한층 달아오르는 피부, 그리고 서로를 격렬하게 갈구하는 진한 베드신까지──. 금기에 발을 들였기 때문에 비로소 적나라해지는, 생생하고 에로틱한 독점욕과 집착을 실력파 호화 작가진이 감성적이고 요염하게 그려내는 주옥같은 총 6편.", amz: "https://amzn.to/3SVAEIh" },
        { n: 100, t: "ボーイッシュな彼女に沼ってく！？ 百合アンソロジー", en_t: "Falling Deeply for a Boyish Girl?! Yuri Anthology", ko_t: "보이시한 그녀에게 빠져든다!? 백합 앤솔로지", a: "あいそえる (著), 石ト悠良 (著), おぎしろ (著), 他", en_a: "Aisoeru, Yura Ishito, Ogishiro, et al.", ko_a: "아이소에루 (저), 이시토 유라 (저), 오기시로 (저), 외", d: "「ボーイッシュ・ガールクラッシュ」をテーマに、中性的でかっこいい女性に心奪われ、狂おしいほど溺れていく少女たちの恋模様を描いた、完全描き下ろしのコンセプト百合アンソロジー。学校や職場で憧れの的である中性的なあの娘、普段は男前なのにふとした瞬間に女の子らしい顔を見せるギャップ、そして強引にリードされているはずが、いつの間にか熱い吐息を重ねてベッドの中に囲い込まれていく濃密な主導権の逆転劇まで。ドキドキするようなかっこよさと、隠されたお色気、そして狂おしいほどの執着を豪華作家陣が瑞々しくもエロティックに描き出す、身も心も魅了される珠玉の短編集。", en_d: "A specially drawn themed Yuri anthology dedicated to 'boyish and girl-crush' characters, exploring the intoxicating romances of girls who fall hopelessly and deeply in love with cool, androgynous women. Whether it is the handsome, school-wide idol who drops her guard to reveal a surprisingly cute, feminine side, or the thrill of being confidently led only for the dynamic to shift behind closed doors amid heavy, shared breaths—this volume is packed with heart-racing tension. A talented lineup of artists masterfully delivers a rich blend of cool charm, hidden sensuality, and frantic obsession that will leave you completely captivated.", ko_d: "'보이시·걸크러시'를 주제로, 중성적이고 멋진 여성에게 마음을 빼앗겨 미치도록 빠져들어 가는 소녀들의 사랑 양상을 그린, 완전 신작 컨셉 백합 앤솔로지. 학교나 직장에서 동경의 대상인 중성적인 그 아이, 평소에는 씩씩한데 문득 순간에 여자아이다운 얼굴을 보이는 갭, 그리고 강제로 리드당하고 있을 터인데 어느새 뜨거운 한숨을 겹치며 침대 속에 갇히게 되는 농밀한 주도권의 역전극까지. 두근거리는 멋짐과 숨겨진 섹시함, 그리고 미치도록 집착을 호화 작가진이 싱그럽고도 에로틱하게 그려내는, 몸과 마음이 매료되는 주옥같은 단편집.", amz: "https://amzn.to/4xHWWeY" }
      ]
    },
  ];
      
